### ISSUE TITLE
Add New Buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1]
First-time contributors are welcome!
Add new button styles that you find helpful.

Currently, there are the following button style types: 
1. Basic: Normal looking buttons
2. Button Styles: styles for the buttons
3. Animated: Different animations for buttons.
4. Hover: Buttons that have a hover effect
5. Icons: Buttons that have icons in them.
6. Social Buttons: Login buttons for different social media platforms
7. Special Buttons: buttons that have a special twist to them.

Either add something under those types or create new ones.
You can check the current ones on the [website](https://sbuttons.github.io/sbuttons/).
For some help on how to add or change button styles, you can learn more on the [contributing guide](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md)

To check for new ideas added by contributors to implement, check the [button-idea](https://github.com/sButtons/sbuttons/labels/button-idea) label and the [ideas](https://github.com/sButtons/sbuttons/discussions?discussions_q=category%3AIdeas) in discussions.

To submit a new button idea, please create a [new discussion](https://github.com/sButtons/sbuttons/discussions/new) under the ideas category.

**Comment by yashgupta18** [comment]
hey can i contribute?

**Comment by shahednasser** [comment]
Yes go ahead!

**Comment by yashgupta18** [comment]
On it. Thanx

**Comment by yashgupta18** [comment]
Hey i added a basic button.
I ran npm run prettier
But npm run watch is showing error.
What to do?

**Comment by yashgupta18** [comment]
Done. Pull Request send.

**Comment by ayushgaur03** [comment]
Hello...I would like to contribute...Can I?

**Comment by shahednasser** [comment]
Sure go ahead @ayushgaur03 ! This issue has the label "Always Open" and anyone can work on it!

**Comment by ayushgaur03** [comment]
@shahednasser hey I am trying to add a new color button...can u guide me in this??

**Comment by gShahr** [comment]
Hello. I am looking to contribute.

**Comment by shahednasser** [comment]
Awesome @gShahr this contribution has the "Always Open" label and so anyone can work on it at any time. If you have a certain idea you'd like to implement then go ahead and do it. If you need any ideas you can check out the button ideas file, where everyone adds their ideas so that someone can implement them!

**Comment by ruchikamuddinagiri** [comment]
Hey! I am beginner and I am looking to contribute to this issue!

**Comment by shahednasser** [comment]
Hi @ruchikamuddinagiri please go ahead! this issue has the "Always Open" label and so anyone can work on it at any time. 

If you have a button idea you'd like to implement then go ahead and do it. If you need any ideas you can check out the button ideas file, where everyone adds their ideas so that someone can implement them! You can also add your own ideas! All these count as contributions.

Please checkout our contribution guide for more help. You can also ask me for any assistance.

**Comment by alkatrivedi** [comment]
I wanted to work on this issue. May I?

**Comment by shahednasser** [comment]
@alkatrivedi sure go ahead! Please refer to previous replies to learn more about this issue.

**Comment by preeti-create** [comment]
add new buttons of discussion

**Comment by preeti-create** [comment]
add this button **sbtn click-btn btn-rounded black-btn**    for discussion

**Comment by tushar2407** [comment]
Hi .!
Looking forward to making a valuable contribution. 
Can I contribute here?

**Comment by shahednasser** [comment]
Hi @preeti-create if you're giving us button ideas, please consider contributing by adding them in the button ideas file so that everyone can see it and maybe someone will work on it!

**Comment by shahednasser** [comment]
Hi @tushar2407 yes you can contribute! If you have any button ideas you can implement them or add them to the button ideas file. If you don't have specific ideas, you can check out the file for ideas and implement them! There are also other things you can contribute to. Please check out the list of issues and the contribution guide.

**Comment by Tushar11Raj** [comment]
Hey can I add thumbs up button? with animation

**Comment by khushali77** [comment]
Can I contribute to this issue?

**Comment by shahednasser** [comment]
Yes of course @Tushar11Raj @khushali77

**Comment by aayushi221** [comment]
Hey can I work on one of your ideas from the list -
Icon Button | A button with icons enlargement and shrink effect on hover.

**Comment by shahednasser** [comment]
Yes sure @aayushi221 !

**Comment by justDOindev** [comment]
I would love to help! Has the Neumorphic button idea been assigned?

**Comment by shahednasser** [comment]
Hi @justDOindev no one has been assigned to it so you can work on it!

**Comment by modaserMoj** [comment]
I was thinking of doing a button where it disappears and reappears on click, is it open?

**Comment by shahednasser** [comment]
@modaserMoj I'm not really sure what you mean by that but you can submit a PR for it and I can see then how it looks!

**Comment by chaitanya4vedi** [comment]
@shahednasser Can i help on this? I would like to add some animated buttons.

**Comment by shahednasser** [comment]
Yes of course @chaitanya4vedi go for it.

**Comment by ashirbad29** [comment]
do I need to learn less before contributing

**Comment by shahednasser** [comment]
Hi @ashirbad29 if you're contributing by adding new buttons then yes you do. Less is very easy though so you can learn it as you add the new button!

If you prefer to contribute without learning less, check out issues with the label [website](https://github.com/shahednasser/sbuttons/labels/website) or [documentation](https://github.com/shahednasser/sbuttons/labels/documentation). You can also go through the website and report any bugs you find!

**Comment by ibhavikamalhotra** [comment]
I want to add a new and interactive button . Can i work on it ?

**Comment by shahednasser** [comment]
@ibhavikamalhotra yes of course!

**Comment by chelsi-001011** [comment]
Hey @shahednasser , I would like to add the toggle button. I had one question in mind you want something like this right
![iOS-inspired-Toggle-Switch-For-Angular](https://user-images.githubusercontent.com/57683338/94711598-eeecab00-0365-11eb-82ff-b90184c569b8.gif)

**Comment by shahednasser** [comment]
@chelsi-001011 you can do it however you want but we're currently not adding any javascript to sButtons so maybe just implement the "toggled" as `:active` and when it's not active then it's not toggled

**Comment by shahednasser** [comment]
@chelsi-001011 on a second thought I think it would be best to make two types of buttons, one the main button which is untoggled and then do the toggled button which should maybe have the class ".toggled" this would make it easier to use in other projects

**Comment by chelsi-001011** [comment]
@shahednasser  okay! Will begin working on the toggle button then. 😄

**Comment by shreyamodi1999** [comment]
Hey! I am new to open sourcing and good with styling. Can I contribute here?

**Comment by shahednasser** [comment]
@shreyamodi1999 of course! Please go ahead.

**Comment by preity-p** [comment]
hey! is anyone working on the 3D keyboard button idea added by @Charu271 under the "Animated" section or can i try contributing towards it?

**Comment by shahednasser** [comment]
Hi @preity-p no one is working on it you can go ahead!

**Comment by Charu271** [comment]
I am working on it and about to create pull request. Facing some issue with
upstream

**Comment by shahednasser** [comment]
@preity-p it seems that @Charu271 is working on it so please find another idea to work on

**Comment by shahednasser** [comment]
@Charu271 what issues are you facing?

**Comment by Charu271** [comment]
Conflict in pull request. I followed the same commands as mentioned in
readme but still getting this error

**Comment by shahednasser** [comment]
@Charu271 this is probably due to changes that have been merged while you were working on it. Please open a pull request so I can look at what the conflicts are.

**Comment by Charu271** [comment]
Okay

**Comment by Charu271** [comment]
I have created the pull request. Kindly let me know why I was facing this
issue

**Comment by abdullah2205** [comment]
hi, let me try adding a snake border button

**Comment by climbingryan** [comment]
Hi, this my first time hearing about and participating in hacktober fest, but I wanna try my hand at the "Transparent on hover" button idea.

**Comment by preity-p** [comment]
> @preity-p it seems that @Charu271 is working on it so please find another idea to work on

alright, sure!

**Comment by shahednasser** [comment]
> hi, let me try adding a snake border button

Hi @abdullah2205 someone is working on this

**Comment by BaihakiTanjung** [comment]
i can contribute bro ?

**Comment by shahednasser** [comment]
sure @BaihakiTanjung please look through "BUTTONS_IDEAS.md" if you need any ideas to work on!

**Comment by preity-p** [comment]
hey, i opened a pull request for the "sleek button" under the "hover" section. there was an issue with the same, please check it when possible.

**Comment by aayushi221** [comment]
Hey opened a pull a request under the name "Shrink-over-hover" Kindly review. @shahednasser

**Comment by Thusal06** [comment]
Hi, Can I work on this?

**Comment by chaitanya4vedi** [comment]
@aayushi221 I see you implemented your portfolio using Bootstrap but your portfolio is not actually responsive. You can add `<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">` at the header section below <title> to see how it looks on different devices. Or if you want I can help you in this with some Suggestions.

**Comment by VishakhaAwasthi01** [comment]
Hello, I want to add Radio Button and buttons that get unfilled on hover.

**Comment by jamieleo93** [comment]
Hey - I'm contributing for the first time, I've read the guidelines. Here goes nothing! 

Thanks for providing a good starter project 👍

**Comment by shahednasser** [comment]
> Hello, I want to add Radio Button and buttons that get unfilled on hover.

Hi @VishakhaAwasthi01 someone is already working on something similar. If you would like to submit new ideas please add a new issue.

**Comment by VishakhaAwasthi01** [comment]
Can I add a minus button? And a drop down button?

**Comment by shahednasser** [comment]
The minus button I think is unnecessary for now but you can add the drop down button. Please make sure you don't use any javascript to do it.

**Comment by VishakhaAwasthi01** [comment]
I just have to design the button or also have to show drop down dummy list?

**Comment by shahednasser** [comment]
Yea you should show the drop down list as well, maybe on hover. Just add something like "item 1", "item 2"

**Comment by VishakhaAwasthi01** [comment]
okay I am working on it

**Comment by mayankmohak** [comment]
I have a new idea in "add to cart" buttons the cart icon move to place order when clicked.
I am working on this idea, will you merge this.

**Comment by shahednasser** [comment]
@mayankmohak sounds like a good idea, but don't add any on click events as this is just a CSS project. Only do the hover effect.

**Comment by sanyud24** [comment]
Hey,can I contribute with neomorphism designed  & some 3d buttons?

**Comment by shahednasser** [comment]
Hi @sanyud24 you can check the [button-idea](https://github.com/shahednasser/sbuttons/labels/button-idea) label for ideas sent by other contributors. You can comment on unassigned issues to be assigned. If you would like to add a new idea, you can also create a "New Button Idea" issue.

**Comment by ankitaugale23** [comment]
> First-time contributors are welcome!
> Add new button styles that you find helpful.
> 
> Currently, there are the following button style types:
> 
> 1. Basic: Normal looking buttons
> 2. Hover: Buttons that have a hover effect
> 3. Animated: Different animations for buttons.
> 4. Icons: Buttons that have icons in them.
> 
> Either add something under those types or create new ones.
> You can check the current ones on the [website](https://shahednasser.github.io/sbuttons/).
> For some help on how to add or change button styles, you can learn more on the [contributing guide](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md)
> 
> To check for new ideas added by contributors to implement, check the [button-idea](https://github.com/shahednasser/sbuttons/labels/button-idea) label

can I work on this? to add some buttons in the basic buttons section.

**Comment by chelsi-001011** [comment]
@shahednasser  hey! I had a query, Do I have to add HTML of the buttons in the website? I might have to do that since I'm using <span> inside the <button> for creating the dots.
And if so then toggle button will be added under special buttons right? 

Here is a screenshot of the buttons.
![Screenshot 2020-10-02 at 4 34 30 PM](https://user-images.githubusercontent.com/57683338/94916924-2de94080-04cd-11eb-839f-8384223c8be3.png)

**Comment by MeerHamza1421** [comment]
hey 👋, can I contribute on it for hacktoberfest ????

**Comment by chaitanya4vedi** [comment]
@shahednasser Can we use Bootstrap in this. Because I see the website lacks a bit of smoothness and sometimes breaks while adding a new feature. If you don't mind I can implement the whole website using Bootstrap and submit a PR.

**Comment by shahednasser** [comment]
> > First-time contributors are welcome!
> > Add new button styles that you find helpful.
> > Currently, there are the following button style types:
> > 
> > 1. Basic: Normal looking buttons
> > 2. Hover: Buttons that have a hover effect
> > 3. Animated: Different animations for buttons.
> > 4. Icons: Buttons that have icons in them.
> > 
> > Either add something under those types or create new ones.
> > You can check the current ones on the [website](https://shahednasser.github.io/sbuttons/).
> > For some help on how to add or change button styles, you can learn more on the [contributing guide](https://github.com/shahednasser/sbuttons/blob/master/CONTRIBUTING.md)
> > To check for new ideas added by contributors to implement, check the [button-idea](https://github.com/shahednasser/sbuttons/labels/button-idea) label
> 
> can I work on this? to add some buttons in the basic buttons section.

We don't need any new basic buttons at the moment. Please look at the button ideas label for ideas to work on or submit new ideas

**Comment by shahednasser** [comment]
> @shahednasser hey! I had a query, Do I have to add HTML of the buttons in the website? I might have to do that since I'm using "span" tag inside the "button" tag for creating the dots.
> And if so then toggle button will be added under special buttons right?
> 
> Here is a screenshot of the buttons.
> ![Screenshot 2020-10-02 at 4 34 30 PM](https://user-images.githubusercontent.com/57683338/94916924-2de94080-04cd-11eb-839f-8384223c8be3.png)

Can you instead of the spans use something like ":before" or ":after"? We're trying to make the button as simple as possible. Let me know if you can.

And yes the button should be under special

**Comment by shahednasser** [comment]
> hey , can I contribute on it for hacktoberfest ????

Yes of course!

**Comment by shahednasser** [comment]
> @shahednasser Can we use Bootstrap in this. Because I see the website lacks a bit of smoothness and sometimes breaks while adding a new feature. If you don't mind I can implement the whole website using Bootstrap and submit a PR.

The website already has bootstrap, if you want to make changes to the looks of it then you can submit a PR and I'll look at it.

**Comment by shahednasser** [comment]
@chaitanya4vedi can you please submit a new issue with what changes you want to do exactly?

**Comment by chaitanya4vedi** [comment]
> @chaitanya4vedi can you please submit a new issue with what changes you want to do exactly?

Sure.

**Comment by ankitaugale23** [comment]
hey, can I add a button that will change its shape after hovering over it?

**Comment by ankitaugale23** [comment]
I have added one issue and I would like to work on it could you please assign it to me? https://github.com/sButtons/sbuttons/issues/568

**Comment by chelsi-001011** [comment]
@shahednasser  Thanks! I learned about "::after" and "::before" and it worked! I'll be adding the buttons under special and making my pr soon!

**Comment by shahednasser** [comment]
Yes we only need two buttons. You can hide block and rounded buttons with shouldHaveRoundedType and shouldHaveBlockType when adding it to button examples section (we're still working on adding it to the contributing guidelines as it is a new feature)

**Comment by chelsi-001011** [comment]
@shahednasser  Created a pull request. please review it! 😄

**Comment by abhishekrawe** [comment]
I wanted to work on this issue. May I?

**Comment by islam36** [comment]
i want to work on this issue. May i make a new button ?

**Comment by shahednasser** [comment]
@abhishekrawe please submit a new idea in an issue to be approved.

**Comment by carlacentenor** [comment]
Hello! I would like to contribute.  Can I?

**Comment by SahanAmarsha** [comment]
I could add new button styles

**Comment by shahednasser** [comment]
@SahanAmarsha if you have a button idea please submit it by first by creating a "new button idea" issue

**Comment by BrianAnakPintar** [comment]
Hi can I contribute?

**Comment by maityankan10** [comment]
hey can I contribute for hacktoberfest, I am new in it

**Comment by shahednasser** [comment]
@BrianAnakPintar @maityankan10 of course you can! You can comment on unassigned issues to claim them or you can create a "new button idea" issue if you have any that you would like to work on.

**Comment by shahednasser** [comment]
Hi @jamieleo93 yes you can! You can either find unassigned issues or create a "new button idea" issue you would like to work on or see implemented.

The link of the website has changed but I forgot to change it in this issue. You can find it [here](https://sbuttons.github.io/sbuttons/)

**Comment by Hyma200** [comment]
Thanks!

**Comment by developerzone** [comment]
Hi,

I want to take up this. Let me know if I can proceed.

**Comment by shahednasser** [comment]
@developerzone you can look for unassigned issues or create a "new button idea" issue if you have an idea you would like to implement or see implemented.

**Comment by SARVESHKHANDELWAL** [comment]
Hi,can i contribute?

**Comment by SARVESHKHANDELWAL** [comment]
Can you please assign to me.

**Comment by AniketDGiri** [comment]
Hello, I would like to contribute, can I?

**Comment by shahednasser** [comment]
Hi @SARVESHKHANDELWAL @AniketDGiri  you can contribute by creating a "new button idea" issue if you have an idea that you would like to implement or see implemented, or you can comment on unassigned issues to contribute.

**Comment by I3han** [comment]
hey can I contribute for hacktoberfest, I am new in it

**Comment by shahednasser** [comment]
@I3han yes you can! If you have an idea then you submit a "new button idea" issue or you can look for unassigned issues to contribute to

**Comment by sayalitandel** [comment]
Hey @shahednasser! This is the second PR of my life, I have added a trash button in the Icon Button category. I would be glad if you would review it. Thank you.

**Comment by japjotsingh13** [comment]
hey can i contribute to this for hacktoberfest

**Comment by shahednasser** [comment]
Sure @japjotsingh13 you can either create a "new button idea" issue that you would like to work on or check unassigned issues to work on them

**Comment by harjotkarwal** [comment]
Hi ! I'm beginner and learning code. I'm new to Open Source. Assign me any issue.

**Comment by shahednasser** [comment]
@harjotkarwal please comment on an unassigned issue or create a "new button idea" issue if you have any that you would like to work on.

**Comment by crnguyen** [comment]
hi, can I contribute?

**Comment by shahednasser** [comment]
sure @crnguyen you can either create a "new button idea" issue that you would like to work on or go through unassigned issues and comment on them to work on them.

**Comment by RgnDunes** [comment]
Hey, I think I can add some buttons with animation effects on hover. I'll love to contribute.

**Comment by shahednasser** [comment]
Hello @RgnDunes you can always create a "new button idea" issue and once approved you can work on it.

**Comment by atenasadat** [comment]
Hey, can I contribute here? I'll love to contribute.

**Comment by shahednasser** [comment]
hello @atenasadat of course you can! You can either check the issues in the repository, or if you have any new button ideas, please create a [new discussion](https://github.com/sButtons/sbuttons/discussions/new) with the category idea and once approved you can work on it.

**Comment by atenasadat** [comment]
Thanks @shahednasser . I have new animation button idea .

**Comment by Pratiksha1-2020** [comment]
Hey can I contribute here. Its my first time in contributing to open source. I will love to do some work.

**Comment by harshitaaaaaa** [comment]
@shahednasser  Hey, I am Harshita. I am new to open-source and learning to contribute. I've edited the button styling and added hover effects. I have created a pull request. Please review it.

**Comment by shahednasser** [comment]
Hello @Pratiksha1-2020 if you have any button idea please submit them in a [new discussion](https://github.com/sButtons/sbuttons/discussions/new) under the category ideas. You can also check out available issues to help!

**Comment by gankita163** [comment]
Hello @shahednasser I am new here and learning to contribute. can i contribute here .
