### ISSUE TITLE
Replace base-icon-btn with icon-btn 

### ISSUE THREAD

**Issue by HADES-01** [sButtons/sbuttons#1002]
**Feature Description.**
The current name `base-icon-btn` is too long it should be reduced to something like `icon-btn`.

**Describe the solution you'd like**
Whoever chooses to do it shall make changes to the class name and  file name [here](https://github.com/sButtons/sbuttons/blob/master/src/components/icon/_base-icon-btn.less) and class name in [`button-example.js`](https://github.com/sButtons/sbuttons/blob/master/assets/js/buttons-examples.js).

**Additional notes**
Just make sure nothing else breaks !!!

**Comment by crnguyen** [comment]
I would like to work on this. Can you assign to me?

**Comment by HADES-01** [comment]
@crnguyen Sure, Go ahead.

**Comment by ramkrishn123** [comment]
I would like to work on this.

**Comment by shahednasser** [comment]
Hi @ramkrishn123 someone is assigned to this. Please look for issues that are unassigned
