### ISSUE TITLE
Make loading-btn animation smoother

### ISSUE THREAD

**Issue by HADES-01** [sButtons/sbuttons#1003]
**1 - Describe the bug**
The loading animation in the some of the loading buttons is not smooth i.e. it snaps back to original position which looks weird.

**2 - Expected behavior of what should have happened (if applicable)**
Simple solution is to just add `alternate` to the loading animations of the buttons that have this problem [here](https://github.com/sButtons/sbuttons/blob/master/src/components/animated/_loading-btn.less).
 
**3 - Screenshots (if applicable)**
![captured](https://user-images.githubusercontent.com/52060608/97720705-963c3980-1aee-11eb-98cd-c6cf17f9a4b7.gif)

**Comment by karleypetracca** [comment]
You can assign me to this one. 😃
