### ISSUE TITLE
Example and Documentation page Responsiveness issue

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#1006]
**1 - Describe the bug** In the Examples and documentation section The heading is overlapping with the bellow section 

**2 - Expected behavior of what should have happened (if applicable)** It should not overlap

**3 - Screenshots (if applicable)**
![WhatsApp Image 2020-10-30 at 21 05 04](https://user-images.githubusercontent.com/58779604/97725382-203ad100-1af4-11eb-91a7-ff9a8752403f.jpeg)
![WhatsApp Image 2020-10-30 at 21 15 40](https://user-images.githubusercontent.com/58779604/97726432-34cb9900-1af5-11eb-88e0-1a9e3a8396e3.jpeg)

**4 - Additional notes** Mobile Samsung A30 browser Google Chrome

**Comment by Soumi150** [comment]
I would like to work on this.
