### ISSUE TITLE
Logo Should not be hidden on small screen

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#1007]
**Is your feature request related to a problem? Please describe.** The logo from the nav should not be hidden

![WhatsApp Image 2020-10-30 at 21 15 56](https://user-images.githubusercontent.com/58779604/97726637-72302680-1af5-11eb-92fc-26ca38f702fe.jpeg)

**Comment by redpfire** [comment]
i can work on this one

**Comment by redpfire** [comment]
please assign me and let me know if everything's alright :)

**Comment by redpfire** [comment]
ouch i already see a problem with the implementation...
it works on Home:
![image](https://user-images.githubusercontent.com/17385340/97768035-81789980-1b20-11eb-93b8-0e9dea92e1c0.png)

but on the other pages we have a button there and it breaks:
![image](https://user-images.githubusercontent.com/17385340/97768054-aec54780-1b20-11eb-8a0a-1c5cb47a6495.png)

should the logo be hidden when there's a button there or how do you guys see it?
