### ISSUE TITLE
[BUTTON IDEA]: floral hover button

### ISSUE THREAD

**Issue by crnguyen** [sButtons/sbuttons#1008]
**1. Name of button**: Floral hover button

**2. Description**: Button that shows a floral background when you hover over it

**3. Button Type (Animated, Special, etc...)**: hover, styles

**4. Will you work on it?**: yes

**Comment by shahednasser** [comment]
Sounds good @crnguyen you may work on it

**Comment by shahednasser** [comment]
Make sure the button type is animation

**Comment by shahednasser** [comment]
Hi @crnguyen are you still working on this?

**Comment by crnguyen** [comment]
yes, just took a little break

**Comment by shahednasser** [comment]
No problem @crnguyen just checking. Take your time.
