### ISSUE TITLE
Do not hide the "To the Top of the Page" button beneath the footer

### ISSUE THREAD

**Issue by glebkema** [sButtons/sbuttons#1010]
**1 - Describe the bug**
When you scroll down the page, the round button in the lower right corner of the screen hides behind the footer.
For example: https://sbuttons.github.io/sbuttons/documentation.html#base

**2 - Expected behavior of what should have happened (if applicable)**
This button should remain on top of any other elements and sections on the page.

**3 - Screenshots (if applicable)**
![bug-totop-button-under-footer](https://user-images.githubusercontent.com/3881568/97748115-3e510300-1aed-11eb-97c2-4f23605371ad.png)

**4 - Additional notes**
It looks like the `z-index` property needs to be adjusted.

**Comment by kushagra-shukla** [comment]
I can do this. Assign me.

**Comment by glebkema** [comment]
@kushagra-shukla Thanks for your willingness to help out, but you seem too experienced for this issue  :)
https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md#important-notes
> Issues that have the label first-timers-only is made for beginners who have contributed to less than 5 repositories. This is a way to help people who are new to open source and contributing.

**Comment by kushagra-shukla** [comment]
> Issues that have the label first-timers-only is made for beginners who have contributed to less than 5 repositories.
>Thanks for your willingness to help out, but you seem too experienced for this issue :)

I have only worked on my projects or group projects and haven't really done any open source contribution 😄. This seemed quick and easy. Sorry I saw your comment after I did my PR. Should I close this PR?

**Comment by glebkema** [comment]
@kushagra-shukla Thanks for your efforts! We will be glad if you can help with any other tasks!

**Comment by RishiAgar** [comment]
I can take this up. Assign me.

**Comment by RishiAgar** [comment]
I can pick this up. Assign me.

**Comment by Fogeinator** [comment]
Hihi, I was wondering if this could be my first contribution? I've never done open source before, so I might ask a bit more questions 😅

**Comment by shahednasser** [comment]
Yes @Fogeinator you can work on it and if you have any questions you can always ask

**Comment by Fogeinator** [comment]
Thanks!! Btw, I was told not to edit the main.css file - which one should I update instead? 😅
