### ISSUE TITLE
Enhance sidebar behavior when reaching the footer

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1012]
The sidebar currently is hidden behind the footer, we need a better behavior for this to make the design look better.

**Comment by EnechukwuChibuike** [comment]
Can I do this?

**Comment by shahednasser** [comment]
Yes @EnechukwuChibuike I'll assign you

**Comment by VinayakChopra** [comment]
Hi, Can I work on this?

**Comment by shahednasser** [comment]
Yes @VinayakChopra you can

**Comment by VinayakChopra** [comment]
Hi, @shahednasser I have created a pull request with a fix for the given issue, kindly check the same.

**Comment by TomWBush** [comment]
I could try to add media query to Vinayak's solution if he is not still working on this.

**Comment by VinayakChopra** [comment]
@TomWBush I am not working on this now and you may go ahead(@shahednasser I hope you agree too).
