### ISSUE TITLE
JS error on the main page of the site

### ISSUE THREAD

**Issue by glebkema** [sButtons/sbuttons#1013]
**1 - Describe the bug**
The browser console shows a Javascript-error on the home page of the site:
https://sbuttons.github.io/sbuttons/index.html
```
Uncaught TypeError: Cannot read property 'left' of undefined
    at S.fn.init.$.fn.isOnScreen (index.js:18)
    at checkSidebar (index.js:71)
    at HTMLDocument.<anonymous> (index.js:153)
    at e (jquery-3.5.1.min.js:2)
    at t (jquery-3.5.1.min.js:2)
```

**2 - Expected behavior of what should have happened (if applicable)**
The error must be fixed as soon as possible, as it stopped working all the scripts on this page.

**3 - Screenshots (if applicable)**
![bug js on mhome-page](https://user-images.githubusercontent.com/3881568/97749954-35156580-1af0-11eb-8737-76d43d78f0bd.png)

**4 - Additional notes**

**Comment by MSTEWARDSON** [comment]
I would like to try and fix this issue.

**Comment by glebkema** [comment]
@MSTEWARDSON OK. I have assigned this issue to you.

**Comment by MSTEWARDSON** [comment]
Update on the issue.

I've narrowed down a few details for this issue. It only happens on the home page. The function call that creates this error comes from the checkSidebar() function within index.js when it calls the isOnScreen() function on the footer element.

Atm Im working into possible solutions to the problem.

**Comment by MSTEWARDSON** [comment]
Alright I have made a PR to fix this issue. Any feedback or suggestions would be appreciated.

Thanks.
