### ISSUE TITLE
Add support for Dark Mode for buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1014]
We need to add support for dark mode, as a lot of the buttons need better support for dark mode, not just for our website, but for the users as well.

This issue will be divided between contributors where each contributor can take up a button to add dark mode support to it. 

Adding the dark mode support need to be done in the following way:

1. Adding support when the parent is `[data-theme="dark"]`
2. Adding support when the button has the class `dark-mode`

So, for each button when adding the support for dark mode, you need to apply it to the above 2. For help on it you can refer to [hatch button's code](https://github.com/sButtons/sbuttons/blob/master/src/components/icon/_hatch.less) as it adds support for them (except adding the `dark-mode` class)

The following buttons need support. Please comment below to take up a button:

- [x] Dashed Button (White and Black Colors) **Taken by @singhtalwinder**
- [x] Glow Button **Taken by @singhtalwinder**
- [x] Neon Border **Taken by @chiragkava**
- [x] Outline (Black and White Colors) **Taken by @shahednasser**
- [x] Stack (Remove white color's border) **Taken by @shahednasser**
- [x] Atom (Yellow, Black and White Colors) **Taken by @shahednasser**
- [x] Diagonal Background (Black and White Colors) **Taken by @TomWBush**
- [x] Expanding Border **Taken by @TomWBush**
- [x] Fill (All types) (Black and White Colors) **Taken by @TomWBush**
- [x] Ripple (Black and White Colors) **Taken by @TomWBush**
- [x] Snake Border **Taken by @TomWBush**
- [x] Transparent on Hover (Black Color) **Taken by @modaserMoj**
- [x] Base Icon (When the icon is with a transparent background, make it white) **Taken By @katyabakun**
- [x] Star Icon (similar to above) **Taken by @TomWBush**
- [x] Hatch (It support the media query and data-theme but doesn't have a `dark-mode` class so that needs to be added). **Taken by @farhanfajarr**
- [x] Colored On Hover **Taken by @farhanfajarr**

**Comment by dotsandchipsandthings** [comment]
Hi @shahednasser can I work on this?

**Comment by singhtalwinder** [comment]
Hey, can I do dashed button?:smiley:

**Comment by theRoushan** [comment]
Can I Fix this Issue?

**Comment by shahednasser** [comment]
Sure @singhtalwinder !

**Comment by shahednasser** [comment]
@theRoushan of course but can you pick a button to work on?

**Comment by muskuu** [comment]
Hi, can I please do the neon border button?

**Comment by shahednasser** [comment]
@muskuu yes sure go ahead!

**Comment by singhtalwinder** [comment]
@shahednasser 
**The Yellow dashed button has a black text color instead of yellow color. Is it expected behavior?**

Here's a screenshot

![Screenshot (3)](https://user-images.githubusercontent.com/61012185/97946450-76d43380-1db0-11eb-907a-251c92acfa8e.png)

Also, how should buttons behave in dark mode?
Should I change the black button to the white button and vice versa in dark mode?

**P.S. Thanks for assigning me**

**Comment by shahednasser** [comment]
Hi @singhtalwinder I think there's a problem with the button, as it should be similar to outline button so the text should be yellow. I'll raise an issue on this, so please just work on the rest of the colors mentioned. Thanks!

**Comment by muskuu** [comment]
![image](https://user-images.githubusercontent.com/13404218/98166084-e2331800-1f0c-11eb-8e03-ebc43764f312.png)

@shahednasser 
Hi, I have made changes to _neon-border.less on my local system with regards to dark mode.
But I am unable to understand this step. Thanks In advance.

**Comment by shahednasser** [comment]
Hi @muskuu . After making the changing in Less files you need to compile them so the changes can be added to `dist/sbuttons.css`

**Comment by singhtalwinder** [comment]
Can I take the glow button?

**Comment by shonali2600** [comment]
Hi, can I do the base icon?

**Comment by shahednasser** [comment]
Yes @shonali2600

**Comment by TomWBush** [comment]
I can do Diagonal Background, Fill, and Ripple.
I also have a question and a concern. For expanding border, I thought it already looked okay. Do you want to make the background transparant? And for the completed dash button, the text on the yellow-btn is almost invisible. And the black-btn looks exactly the same as the white-btn; it just doesn't have the animation.

**Comment by shahednasser** [comment]
Thank you @TomWBush . As for expanding border we need to change the color of the border on dark mode, as it isn't really visible.

As for the dashed button, we had a different issue for the yellow button and someone was working on it but they've basically disappeared. If you would like to work on it as well that's fine. as for the black btn it is supposed to look like that in dark mode, as a black button will be no good.

**Comment by shonali2600** [comment]
Hi @shahednasser, I'm having trouble finding the CSS of Base icon buttons. Can you please help me out as I'm new to open source.

**Comment by TomWBush** [comment]
> Hi @shahednasser, I'm having trouble finding the CSS of Base icon buttons. Can you please help me out as I'm new to open source.

It's src/components/icon/_icon-btn.less.

**Comment by shahednasser** [comment]
@shonali2600 as @TomWBush it's in the src directory. We use less in this repository and then compile it to CSS.

**Comment by shahednasser** [comment]
**UPDATE**

After testing the buttons that now support dark mode I have found a bug on the website which is that the dark mode styling will apply on browsers/devices that have dark mode enabled, even when the website is on 'light' mode. This can cause an issue to anyone that uses their website as well if they don't support dark mode or have, like us, a toggle for dark/light modes.

So, now it's not required to add the dark mode media query to the buttons and I will edit the original issue description. I will also remove all of the dark mode media queries that have been added prior to this.

Thank you all.

**Comment by modaserMoj** [comment]
I made a pull request for  Transparent on Hover (Black Color) on #1151

**Comment by TomWBush** [comment]
I can do the last three.

**Comment by shahednasser** [comment]
Which last three @TomWBush ? Some of them are taken

**Comment by TomWBush** [comment]
> Which last three @TomWBush ? Some of them are taken

Oh sorry, I mean the last three available.

**Comment by shahednasser** [comment]
great @TomWBush you can work on them

**Comment by shahednasser** [comment]
Hello @muskuu @shonali2600 are you still working on the buttons or should we leave them unassigned for others?

**Comment by muskuu** [comment]
@shahednasser I'm sorry I'm not able to do it. Thank you for the opportunity. You can unassign me. Thanks.

**Comment by katyabakun** [comment]
Hi, @shahednasser if there are any buttons that are still unassigned I would be happy to help with them.

**Comment by TomWBush** [comment]
> Hi, @shahednasser if there are any buttons that are still unassigned I would be happy to help with them.

Neon Border and Base Icon are currently available. Please pick one or both.

**Comment by shahednasser** [comment]
@muskuu no problem thank you for letting me know.

**Comment by shahednasser** [comment]
Hello @katyabakun as @TomWBush mentioned there are two buttons available. Please choose one and let us know to assign it to you.

**Comment by chiragkava** [comment]
Can I take Neon border?

**Comment by shahednasser** [comment]
Sure @chiragkava

**Comment by katyabakun** [comment]
@shahednasser Could you assign me to Base Icon, if it is still unassigned?

**Comment by shahednasser** [comment]
Since @shonali2600 hasn't replied, @katyabakun you can work on it.
