### ISSUE TITLE
Tab's text on hover in dark mode should not change

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1016]
In the examples page when it is dark mode, the text on hover becomes white so it's not readable.

**Comment by felops** [comment]
Is this bug when you hover on the tab? I could solve it (:

**Comment by felops** [comment]
Does this bug happens when you hover on the tab? I could fix it (:

**Comment by eg180** [comment]
I'd like to try. Thank you

**Comment by Mani-07** [comment]
@shahednasser - I am interested on this. Can you assign to me?

**Comment by Mani-07** [comment]
@shahednasser - I have fixed issue and raised PR. Can you check and let me know if an concern.
https://github.com/sButtons/sbuttons/pull/1052

**Comment by shahednasser** [comment]
Assigning @felops for commenting first
