### ISSUE TITLE
Paper curl button's background should be transparent on curl

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1017]
In Paper curl button when you hover the background of the "curl" is white but it should be transparent (you can see it when you switch to dark mode)

**Comment by ZeroniaFX** [comment]
Hi can you assign this to me please? Thanks!

**Comment by Mani-07** [comment]
@shahednasser - Can you assign this issue to me?

**Comment by Mani-07** [comment]
@shahednasser  - I have fixed this issue. please check below link.
https://deploy-preview-1046--clever-boyd-7dd108.netlify.app/examples.html#papercurl
