### ISSUE TITLE
Weird behavior in blue "next button"

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1018]
In the Next Button color blue, there's weird behavior on hover. This only happens in the blue color of this button

![sButtons-Simple-and-Creative-Buttons (3)](https://user-images.githubusercontent.com/27354907/97751439-ff29ae80-1afa-11eb-905b-17bd836e85fb.png)

**Comment by AndreJesusBrito** [comment]
Hi @shahednasser, I tested this in some browsers and I'm not getting that problem.
Can you please give some more information?

**Comment by divyanshutewari17** [comment]
@shahednasser  can I work on it?

**Comment by pragapraga** [comment]
@shahednasser - As commented by @AndreJesusBrito , I am also not able to reproduce. Can you please provide more information?

**Comment by shahednasser** [comment]
@AndreJesusBrito @pragapraga thank you for informing me about this. It didn't happen before but it suddenly started happening on my laptop.

@divyanshutewari17 can you reproduce this?

**Comment by divyanshutewari17** [comment]
@shahednasser I saw it once (after that I requested to work on the issue), but I am not seeing it anymore.

**Comment by shahednasser** [comment]
@divyanshutewari17 hmm that's weird. I'll leave this issue open for now in case this problem comes back again. Thank you.
