### ISSUE TITLE
Make flash button's animation faster

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1019]
The animation for the flash button is currently slow, it should be faster.

**Comment by felops** [comment]
Hi @shahednasser, could I pick this one?

**Comment by redpfire** [comment]
i could work on that. as i can see the animation is 2s long now. how much faster should it be in your opinion?

**Comment by redpfire** [comment]
oh, well, nvm then

**Comment by ramkrishn123** [comment]
I want to fix this issue.
