### ISSUE TITLE
Make margin below "extra large" buttons smaller

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1020]
The margin below "extra large" buttons is big. It should be smaller. (Change needs to be done in `assets/css/index.css` as this is in the website, not in the button's code)

**Comment by d3fau7t** [comment]
Could I pick this up?

**Comment by pragapraga** [comment]
Shall i pickup ? @shahednasser

**Comment by eg180** [comment]
Good morning. I am interested in helping. Thank you. :)

**Comment by shahednasser** [comment]
@d3fau7t you may work on this as you commented first

**Comment by d3fau7t** [comment]
@shahednasser Does this change actually need to take place in `assets/css/examples.css`?
