### ISSUE TITLE
change "SButtons" to "sButtons" in examples page

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1021]
In the heading of the examples page, "SButtons" should be changed to "sButtons"

**Comment by sleekyom** [comment]
Hi @shahednasser I will fix this now

**Comment by shahednasser** [comment]
I'll assign you @sleekyom

**Comment by sleekyom** [comment]
Thank you

**Comment by sleekyom** [comment]
@shahednasser I'm getting this error 
remote: Permission to sButtons/sbuttons.git denied to sleekyom.
fatal: unable to access 'https://github.com/sButtons/sbuttons.git/': The requested URL returned error: 403

**Comment by sleekyom** [comment]
Yes I will do that right away
