### ISSUE TITLE
Add animated class to animated buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1022]
Most animated button's animation only happens on hover, we need to add an `animated` class that triggers the animation without hovering over the button. And when the animation class is added make sure that the animation is not also triggered on hover. In order to avoid repeated code in the buttons, please move the animation or transition to a mixin and call it where it is needed.

Also, some button's animation needs to be continuous, others don't. I have indicated below which is continuous and which isn't 

This issue is going to be split between contributors. Each contributor can take up a button from the list below. Please comment before taking up a button, choosing which between you will be working on.

The following buttons need the `animated` class:
- [x] Atom (continuous) **Taken by @karleypetracca**
- [x] Aura (continuous) **Taken by @TomWBush**
- [x] Bounce (continuous) **Taken by @TomWBush**
- [x] Diagonal Background on Hover (not continuous) **Taken by @TomWBush**
- [x] Expanding Border (not continuous) **Taken by @TomWBush**
- [x] Fill Buttons All Types (not continuous) **Taken by @TomWBush**
- [x] Flash (continuous) **Taken by @TanmayJain17**
- [x] Hinge (not continuous) **Taken by @kalimah-apps**
- [x] Invert (not continuous) **Taken by @karishmapatel27**
- [x] Liquid (not continuous) **Taken by @A3vk**
- [x] Neon (not continuous) **Taken by @kyawkyawsoezhu**
- [x] Next (not continuous) **Taken by @kyawkyawsoezhu**
- [x] Nudge (continuous) **Taken by @modaserMoj**
- [x] Paper Curl (not continuous) **taken by @TomWBush**
- [x] Previous (not continuous) **taken by @TomWBush**
- [x] Pudding (not continuous) **Taken by @AbdulMAbdi**
- [x] Pulse (not continuous) **Taken by @AbdulMAbdi**
- [x] Rainbow (continuous) **Taken by @A3vk**
- [x] Ripple (not continuous) **Taken by @abid1998**
- [x] Scale (not continuous) **Taken by @abid1998**
- [x] Shake (continuous) **Taken By @kyawkyawsoezhu**
- [x] Shine (continuous) **Taken by @kyawkyawsoezhu**
- [x] Skew (not continuous) **Taken by @Hassan-Ib**
- [x] Snake Border (not continuous) **Taken by @rad10wave**
- [x] Splash (continuous) **Taken by @modaserMoj**
- [x] Spring (continuous) **Taken by @modaserMoj**
- [x] Transparent on Hover (not continuous) **taken by @ChristopherMarques**
- [x] Vibrate (continuous) **Taken by @modaserMoj**

**Comment by karleypetracca** [comment]
I will take the atom button. Thanks

**Comment by shahednasser** [comment]
Great @karleypetracca you can go ahead

**Comment by karleypetracca** [comment]
One additional consideration on this @shahednasser : will there be a plan to put something like `shouldHaveAnimatedType` into the `buttons-examples.js`?  I imagine it would default to false, unless the value is there in the examples list.  That way it can be turned on for each button as each new button's `.animated` css class gets completed, and for those completed buttons, can show the class exists.

**Comment by shahednasser** [comment]
@karleypetracca I don't think it's necessary for the website at the moment, as it could make it laggy. We could maybe decide in the future to do that, but only play the animation when the button is on screen? This is just an idea but I'm not sure we will work on it at the moment, but thank you for the suggestion!

**Comment by Hrshk15** [comment]
I'll take the rainbow button.

**Comment by shahednasser** [comment]
Great @Hrshk15 thanks!

**Comment by adsingh14** [comment]
Indeed ! 

I've an idea to improve the UI/UX of animated buttons. I can add the toggle animated class functionality in such way that it won't affect the other contributors work. Will discuss this further on your acknowledgement.

**Comment by TomWBush** [comment]
How many of them can I take? I will take Aura and Bounce if I can take more than one. Thank you!

**Comment by shahednasser** [comment]
@adsingh14 great but toggle button is not on the list above so please choose one of the buttons from the list and let me know which

**Comment by shahednasser** [comment]
sure @TomWBush you can

**Comment by TomWBush** [comment]
I can take the next three, Diagonal Background on Hover, Expanding Border, Fill Buttons All Types.

One question I have is that Expanding Border does not seem to have a continuous animation on hover. Do you want me to make it continuous for the animated class?

**Comment by shahednasser** [comment]
Thanks @TomWBush . No I think that was a mistake, it's not supposed to be continuous. I'll edit that.

**Comment by adsingh14** [comment]
@shahednasser I wasn't talking about toggle button from the list. I was suggesting adding toggle functionality button for animated buttons.

**Comment by shahednasser** [comment]
@adsingh14 oh do you mean on the website adding a toggle functionality that adds or removes the `animated` class? That's a good idea. Can you open a new issue with it please with it?

**Comment by yuwangcs** [comment]
@shahednasser hello, can I take flash, hinge, invert?

**Comment by shahednasser** [comment]
Yes @yuwangcs you can

**Comment by sjohnston92** [comment]
@shahednasser Hey there can I take the Liquid and Transparent on Hover buttons?

**Comment by modaserMoj** [comment]
@shahednasser can I take spring and splash?

**Comment by kyawkyawsoezhu** [comment]
hi @shahednasser, I would like to take **Splash**, **Spring**

**Comment by sjohnston92** [comment]
Hey @shahednasser can I work on the Liquid and Transparent on Hover buttons?

**Comment by shahednasser** [comment]
@modaserMoj @kyawkyawsoezhu @sjohnston92 I've assigned you all to the buttons you have chosen

**Comment by modaserMoj** [comment]
@shahednasser Can I also take nudge and vibrate?

**Comment by shahednasser** [comment]
Yes @modaserMoj you can

**Comment by kyawkyawsoezhu** [comment]
@shahednasser I would also like to take **Neon**, **Next**

**Comment by shahednasser** [comment]
Sure @kyawkyawsoezhu go ahead

**Comment by AbdulMAbdi** [comment]
@shahednasser Can I take pudding and pulse?

**Comment by shahednasser** [comment]
Yes @AbdulMAbdi you can

**Comment by Tharunkumar001** [comment]
@shahednasser  can i take ripple and scale

**Comment by shahednasser** [comment]
Yes @Tharunkumar001 you can

**Comment by TomWBush** [comment]
I can do Paper Curl and Previous.

**Comment by Hassan-Ib** [comment]
can i do the skew and i have questions

**Comment by shahednasser** [comment]
@Hassan-Ib I have assigned you the skew. Let me know what questions you have.

**Comment by thaditi** [comment]
Hi @shahednasser  ! Can I take Snake Border?

**Comment by Harsh-GitCollab** [comment]
Can I take Snake Border ?

**Comment by shahednasser** [comment]
Since @thaditi replied first, they can work on it. 

@Harsh-GitCollab Please pick another button to work on (I cleared some buttons that were assigned to others but they've taken to long to send a PR). Thank you!

**Comment by yuwangcs** [comment]
@shahednasser Hello, I have opened a pull request for hinge, invert and flash. Thanks

**Comment by harshitaaaaaa** [comment]
@shahednasser I was trying making a brown-color button for all the types but I'm facing a problem that the button is not getting displayed. I've made necessary changes in almost all the files and I'am unable to figure out which one I'm missing. Can you please help me out?

**Comment by shahednasser** [comment]
Hello @harshitaaaaaa . Please submit new discussions with your questions. As for new button colors, we are currently not accepting any new colors as it requires a lot of changes through all buttons.

**Comment by tirlochanarora16** [comment]
Hey, can I also contribute to this project?

**Comment by ahammadunny** [comment]
Hi Shahed,
Are there any buttons left for modification( like add animation class)? According to your list above, the only unassigned one is SNAKE BORDER. But in the comments, I see that it has been assigned to somebody. Please assign me to some button so that I can start working on it. Thank you.
Ahammadunny Pathiaseril.

**Comment by ChristopherMarques** [comment]
Hello @shahednasser, 
warm hugs! 😊

I'd like to work on this project too, what buttons is not assigned to anyone?
Can I take one? Thank you.

**Comment by shahednasser** [comment]
Hello @ahammadunny and @ChristopherMarques , I have cleared some button assignments due to the fact that some contributors failed to deliver. Please let me know if you'd like to work on any of them and which ones you'd like to work on.

**Comment by ChristopherMarques** [comment]
Hello again @shahednasser, I would like to work on "Transparent on Hover" button... 
Can I work on this? 

Thanks 😃

**Comment by shahednasser** [comment]
Yes @ChristopherMarques you can!

**Comment by TomWBush** [comment]
Hi @shahednasser ,

I did paper curl and previous a while ago, and the PR was merged #1201. But I think you never marked them as completed.

**Comment by shahednasser** [comment]
Hi @TomWBush thank you for reminding me! I've been away for a while. I'll mark it as completed

**Comment by nagasaisriya** [comment]
Hello @shahednasser , can I work on Rainbow button?

**Comment by matoupi-2** [comment]
Hi @shahednasser,
I'd like to work on this project, what buttons is not assigned to anyone ?
Can I take one?

**Comment by satcasm** [comment]
Hi 
I'd like to try on flash button . Can you assign it to me?

**Comment by emily876** [comment]
I want to work on rainbow and hinge button . Can you assign me that !!

**Comment by shahednasser** [comment]
Hello @satcasm and @emily876 , sorry for the delay but you may work on the button

**Comment by shahednasser** [comment]
Unassigning everyone from the remaining buttons as no one submitted PRs

**Comment by kalimah-apps** [comment]
@shahednasser I can work on the hinge animation.

**Comment by karishmapatel27** [comment]
Hi @shahednasser
I'd like to contribute to this project, may I know which buttons are still available?

**Comment by princeo1** [comment]
Hi @shahednasser ,I want to contribute here ,can you let me know which one is available?

**Comment by shahednasser** [comment]
Hi @kalimah-apps I have assigned you to hinge

**Comment by shahednasser** [comment]
Hello @karishmapatel27 @princeo1 the ones that are not checked off and do not have next to them "taken by" are available. Please comment which ones you'd like to work on to be assigned to them

**Comment by karishmapatel27** [comment]
Hi @shahednasser, thank you for coming back to me.  I would like to work on Invert please.

**Comment by shahednasser** [comment]
Great I have assigned you the button

**Comment by princeo1** [comment]
Thank you for replying @shahednasser I would like to work on rainbow

**Comment by shahednasser** [comment]
Great @princeo1 you're assigned

**Comment by ArnoldGee** [comment]
Hi @shahednasser I'm new to the project and would like to contribute. Please feel free to assign me a task ✅

**Comment by shahednasser** [comment]
Hi @ArnoldGee please choose a button from the list if you want to work on it!

**Comment by TanmayJain17** [comment]
Hi @shahednasser  I would also like to contribute here . Can I work on the Flash Button ?

**Comment by shahednasser** [comment]
Hello @TanmayJain17 yes you can I'll assign you

**Comment by A3vk** [comment]
Hello @shahednasser can I work on the Liquid and the Rainbow button?

**Comment by abid1998** [comment]
Hello @shahednasser  can i take these
Rainbow (continuous)
Ripple (not continuous)
Scale (not continuous)
button ?

**Comment by shahednasser** [comment]
@A3vk I have assigned you Liquid and Rainbow
@abid1998 I have assigned you Ripple and Scale.

Thank you

**Comment by rad10wave** [comment]
Hey @shahednasser can i take the Snake Border ?

**Comment by shahednasser** [comment]
Hello @rad10wave yes I'll assign you
