### ISSUE TITLE
Copy button hover color change issue in dark mode

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#1035]
**1 - Describe the bug** When hover on copy button in the documentation page there remains some white colors on corner that is looking odd . so you can just remove the white corner 
![Screenshot (368)](https://user-images.githubusercontent.com/58779604/97769937-e64de700-1b54-11eb-961e-54fb58cae75e.png)

**Comment by isonnymichael** [comment]
hi @dsnehasish74 , thank you for reporting the bug. Would you like to work on it ? I will asign you

**Comment by dsnehasish74** [comment]
No I open this  issue for the beginners . So if any beginner is interested to work on it you just assign this to them

**Comment by isonnymichael** [comment]
@dsnehasish74 ok, thank you

**Comment by Mani-07** [comment]
@dsnehasish74  - I am new to this. I can take this issue? Can you assign to me?

**Comment by dsnehasish74** [comment]
@Mani-07  Yahh you can start working , I am assigning it to you

**Comment by Mani-07** [comment]
@dsnehasish74 - Please add hacktoberfest Tag so that i can claim for this PR. Let me know if any concern.

**Comment by Mani-07** [comment]
@dsnehasish74  - I have fixed this issue and raised PR. Can you check once?

**Comment by dsnehasish74** [comment]
@Mani-07  I already checked that it was ok . @shahednasser  will merge it to the main branch . Thank you for your work
