### ISSUE TITLE
Improve style of links

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1060]
Links in the documentation page are indistinguishable from normal text, it should be changed to have a different style than normal text. You can see what I mean in the [Download CSS File](https://sbuttons.github.io/sbuttons/documentation.html#downloadcss) part of the documentation.

Also, in dark mode the color of the link is black which doesn't look good so that should be fixed as well.

**Comment by mayankmohak** [comment]
Hi i would like to fix this...

**Comment by shahednasser** [comment]
Great @mayankmohak I'll assign you
