### ISSUE TITLE
Hatch buttons perspective bug

### ISSUE THREAD

**Issue by AndreJesusBrito** [sButtons/sbuttons#1072]
**1 - Describe the bug**
When the icon of an hatch button gets active the icon does not return to default position on hover out

Steps:
1- hover in a hatch button
2- click it
3 - hover out

**2 - Expected behavior of what should have happened (if applicable)**
On hover out is expected the icon to return to default position

**3 - Screenshots (if applicable)**
![bug](https://user-images.githubusercontent.com/35274086/97784638-ee7b4600-1b97-11eb-9aa2-fcff9a8e2b96.jpg)

**Comment by shahednasser** [comment]
Oh nice catch thanks! Would you like to be assigned to this?

**Comment by AndreJesusBrito** [comment]
@shahednasser sure.
