### ISSUE TITLE
Button name highlighted in different from button which appear on screen

### ISSUE THREAD

**Issue by DhrutikPatel** [sButtons/sbuttons#1073]
**1 - Describe the [bug**] : Button name highlighted in different from button which appear on screen for some button ex. when you click on **Gradient button** in subtopic then when it toogle to Gradient button heading page but the subtopic is highlight to **(Extra-small) next button**.

**2 - Expected behavior of what should have happened (if applicable)** Button name highlighted should be same as currently appearing button heading.

**3 - Screenshots (if applicable)**

**4 - Additional notes** : I think is it taking reference as buttom screen but instead in should take reference as center of screen to change the subtopic.

**Comment by shahednasser** [comment]
Thank you @DhrutikPatel for pointing this out. We have someone currently working on this.

**Comment by shahednasser** [comment]
@isonnymichael are you working on this or should we leave this open for other contributors?

**Comment by shahednasser** [comment]
Hi @DhrutikPatel would you like to work on this?
