### ISSUE TITLE
Inconsistent loading button labels

### ISSUE THREAD

**Issue by d3fau7t** [sButtons/sbuttons#1075]
**1 - Describe the bug**
Labels for loading buttons are inconsistent with what the button displays.

**2 - Expected behavior of what should have happened (if applicable)**
Buttons with loading animation on the left side should be labeled "loading left", and those on the right side should be labeled "loading right".

**3 - Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/57768970/97788994-17e1a500-1b8b-11eb-9769-54fccbb18f39.png)

**4 - Additional notes**
Found in `assets/js/buttons-examples.js`

**Comment by Wei-J-Huang** [comment]
I will try to fix this.

**Comment by shahednasser** [comment]
Hello @d3fau7t thank you for noticing this. Actually the change need to be made in `assets/js/buttons-examples.js`. Let me know if you would like to work on this.

**Comment by jlieow** [comment]
Hi can I attempt to fix the bug?

**Comment by shahednasser** [comment]
Sure @jlieow go ahead
