### ISSUE TITLE
sButton logo on top left should redirect to home page

### ISSUE THREAD

**Issue by DhrutikPatel** [sButtons/sbuttons#1085]
**1 - Describe the bug** sButton logo on top left when clicked not redirecting to home page

**2 - Expected behavior of what should have happened ** sButton logo on top left when clicked should redirecting to home page

**Comment by SARVESHKHANDELWAL** [comment]
Can I work on this??

**Comment by shahednasser** [comment]
As @SARVESHKHANDELWAL pointed out this is not necessary, however I guess people are used to clicking the logo to go to the homepage so from a UX perspective this is useful. Will put this up as a low priority issue.

**Comment by jlieow** [comment]
Can I attempt to fix this?

**Comment by DhrutikPatel** [comment]
@shahednasser should I fix it ?

**Comment by shahednasser** [comment]
Sure @jlieow go ahead
