### ISSUE TITLE
please help in compiling less

### ISSUE THREAD

**Issue by mayankmohak** [sButtons/sbuttons#1086]
i am  trying to compile less using `npm run compile` but when did so all the less files are re-written.

Pasting here the complete log of what i got
$ `npm run compile`

> sbuttons@1.0.4 compile C:\Users\Mayank Mohak\Desktop\workspace\git\sbuttons
> lessc src/sbuttons.less dist/sbuttons.css && npm run prettier
>  
> sbuttons@1.0.4 prettier C:\Users\Mayank Mohak\Desktop\workspace\git\sbuttons
 prettier --write "src/**/*.less" "dist/sbuttons.css" "assets/**/*.css" "assets/**/*.js"
src\_variables.less 278ms
src\components\_animated.less 49ms
src\components\_basic.less 293ms
src\components\_hover.less 139ms
src\components\_icon.less 9ms
src\components\_social.less 90ms
src\components\_special.less 30ms
src\components\_styles.less 180ms
src\components\animated\_arrow.less 146ms
src\components\animated\_atom.less 154ms
src\components\animated\_aurapulse.less 63ms
src\components\animated\_bounce.less 28ms
src\components\animated\_diagonalBackground.less 46ms
src\components\animated\_expanding.less 72ms
src\components\animated\_fill.less 110ms
src\components\animated\_flash.less 121ms
src\components\animated\_hinge.less 16ms
src\components\animated\_invert.less 8ms
src\components\animated\_liquid.less 69ms
src\components\animated\_loading-btn.less 210ms
src\components\animated\_neon.less 46ms
src\components\animated\_nudge.less 73ms
src\components\animated\_papercurl.less 22ms
src\components\animated\_pudding.less 24ms
src\components\animated\_pulse.less 96ms
src\components\animated\_rainbow.less 51ms
src\components\animated\_ripple.less 148ms
src\components\animated\_scale.less 7ms
src\components\animated\_shake.less 37ms
src\components\animated\_shine.less 131ms
src\components\animated\_skew.less 6ms
src\components\animated\_snake.less 35ms
src\components\animated\_splash.less 40ms
src\components\animated\_spring.less 17ms
src\components\animated\_transparentOnHover.less 30ms
src\components\animated\_vibrate.less 76ms
src\components\icon\_base-icon-btn.less 89ms
src\components\icon\_grow.less 18ms
src\components\icon\_hatch.less 35ms
src\components\icon\_star.less 15ms
src\components\social\_apple.less 7ms
src\components\social\_bitbucket.less 13ms
src\components\social\_discord.less 24ms
src\components\social\_facebook.less 7ms
src\components\social\_flickr.less 46ms
src\components\social\_github.less 11ms
src\components\social\_gitlab.less 7ms
src\components\social\_google.less 13ms
src\components\social\_instagram.less 24ms
src\components\social\_linkedin.less 9ms
src\components\social\_microsoft.less 16ms
src\components\social\_reddit.less 11ms
src\components\social\_snapchat.less 13ms
src\components\social\_steam.less 7ms
src\components\social\_tumblr.less 16ms
src\components\social\_twitter.less 17ms
src\components\social\_weibo.less 94ms
src\components\social\_whatsapp.less 8ms
src\components\special\_code-btn.less 73ms
src\components\special\_handwritten-btn.less 28ms
src\components\special\_neumorphic.less 46ms
src\components\special\_play-game.less 46ms
src\components\special\_rainbow-border.less 26ms
src\components\special\_retro.less 45ms
src\components\special\_toggle.less 94ms
src\components\special\_win95.less 14ms
src\components\styles\_click.less 16ms
src\components\styles\_dashed.less 112ms
src\components\styles\_disabled.less 7ms
src\components\styles\_glossy-btn.less 63ms
src\components\styles\_glow.less 23ms
src\components\styles\_gradient.less 61ms
src\components\styles\_key.less 52ms
src\components\styles\_neon-border.less 42ms
src\components\styles\_outline.less 39ms
src\components\styles\_rounded-bottom.less 9ms
src\components\styles\_rounded-diagonal-tl.less 9ms
src\components\styles\_rounded-diagonal-tr.less 8ms
src\components\styles\_rounded-top.less 9ms
src\components\styles\_stack.less 115ms
src\components\styles\_striped.less 41ms
src\components\styles\_xlarge.less 7ms
src\components\styles\_xsmall.less 5ms
src\sbuttons.less 8ms
dist\sbuttons.css 6411ms
assets\css\documentation.css 154ms
assets\css\examples.css 120ms
assets\css\footer.css 50ms
assets\css\header.css 285ms
assets\css\index.css 29ms
assets\css\main.css 383ms
assets\css\variables.css 9ms
assets\js\buttons-examples.js 1765ms
>assets\js\index.js 1354ms

Mayank Mohak@MAYANK MINGW64 ~/Desktop/workspace/git/sbuttons (temp)
$ `git status`
>On branch temp
Your branch is up to date with 'origin/temp'.
>  
>Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   assets/css/documentation.css
        modified:   assets/css/examples.css
        modified:   assets/css/footer.css
        modified:   assets/css/header.css
        modified:   assets/css/index.css
        modified:   assets/css/main.css
        modified:   assets/css/variables.css
        modified:   assets/js/buttons-examples.js
        modified:   assets/js/index.js
        modified:   dist/sbuttons.css
        modified:   src/_variables.less
        modified:   src/components/_animated.less
        modified:   src/components/_basic.less
        modified:   src/components/_hover.less
        modified:   src/components/_icon.less
        modified:   src/components/_social.less
        modified:   src/components/_special.less
        modified:   src/components/_styles.less
        modified:   src/components/animated/_arrow.less
        modified:   src/components/animated/_atom.less
        modified:   src/components/animated/_aurapulse.less
        modified:   src/components/animated/_bounce.less
        modified:   src/components/animated/_diagonalBackground.less
        modified:   src/components/animated/_expanding.less
        modified:   src/components/animated/_fill.less
        modified:   src/components/animated/_flash.less
        modified:   src/components/animated/_hinge.less
        modified:   src/components/animated/_invert.less
        modified:   src/components/animated/_liquid.less
        modified:   src/components/animated/_loading-btn.less
        modified:   src/components/animated/_neon.less
        modified:   src/components/animated/_nudge.less
        modified:   src/components/animated/_papercurl.less
        modified:   src/components/animated/_pudding.less
        modified:   src/components/animated/_pulse.less
        modified:   src/components/animated/_rainbow.less
        modified:   src/components/animated/_ripple.less
        modified:   src/components/animated/_scale.less
        modified:   src/components/animated/_shake.less
        modified:   src/components/animated/_shine.less
        modified:   src/components/animated/_skew.less
        modified:   src/components/animated/_snake.less
        modified:   src/components/animated/_splash.less
        modified:   src/components/animated/_spring.less
        modified:   src/components/animated/_transparentOnHover.less
        modified:   src/components/animated/_vibrate.less
        modified:   src/components/icon/_base-icon-btn.less
        modified:   src/components/icon/_grow.less
        modified:   src/components/icon/_hatch.less
        modified:   src/components/icon/_star.less
        modified:   src/components/social/_apple.less
        modified:   src/components/social/_bitbucket.less
        modified:   src/components/social/_discord.less
        modified:   src/components/social/_facebook.less
        modified:   src/components/social/_flickr.less
        modified:   src/components/social/_github.less
        modified:   src/components/social/_gitlab.less
        modified:   src/components/social/_google.less
        modified:   src/components/social/_instagram.less
        modified:   src/components/social/_linkedin.less
        modified:   src/components/social/_microsoft.less
        modified:   src/components/social/_reddit.less
        modified:   src/components/social/_snapchat.less
        modified:   src/components/social/_steam.less
        modified:   src/components/social/_tumblr.less
        modified:   src/components/social/_twitter.less
        modified:   src/components/social/_weibo.less
        modified:   src/components/social/_whatsapp.less
        modified:   src/components/special/_code-btn.less
        modified:   src/components/special/_handwritten-btn.less
        modified:   src/components/special/_neumorphic.less
        modified:   src/components/special/_play-game.less
        modified:   src/components/special/_rainbow-border.less
        modified:   src/components/special/_retro.less
        modified:   src/components/special/_toggle.less
        modified:   src/components/special/_win95.less
        modified:   src/components/styles/_click.less
        modified:   src/components/styles/_dashed.less
        modified:   src/components/styles/_disabled.less
        modified:   src/components/styles/_glossy-btn.less
        modified:   src/components/styles/_glow.less
        modified:   src/components/styles/_gradient.less
        modified:   src/components/styles/_key.less
        modified:   src/components/styles/_neon-border.less
        modified:   src/components/styles/_outline.less
        modified:   src/components/styles/_rounded-bottom.less
        modified:   src/components/styles/_rounded-diagonal-tl.less
        modified:   src/components/styles/_rounded-diagonal-tr.less
        modified:   src/components/styles/_rounded-top.less
        modified:   src/components/styles/_stack.less
        modified:   src/components/styles/_striped.less
        modified:   src/components/styles/_xlarge.less
        modified:   src/components/styles/_xsmall.less
>        modified:   src/sbuttons.less
> 
>no changes added to commit (use "git add" and/or "git commit -a")
`
please anyone explain how to do it as i got fed up trying things.

**Comment by shahednasser** [comment]
Hi @mayankmohak don't worry it shows at first that all files are modified but when you make the commit only the files that are actually modified get committed. There's no problem here. Let me know if you need any additional help.

**Comment by mayankmohak** [comment]
>warning: LF will be replaced by CRLF in src/components/styles/_outline.less.
>The file will have its original line endings in your working directory

I got this when i `git add any file` the changes.

**Comment by shahednasser** [comment]
That's not a problem don't worry @mayankmohak this is related to the end of file

**Comment by mayankmohak** [comment]
thanks a lot dear it was to small thing but due to thinking it big it was difficult for me. **btw thanks a lot**
