### ISSUE TITLE
One Button of social buttons in animated buttons section the text is not visible.

### ISSUE THREAD

**Issue by SARVESHKHANDELWAL** [sButtons/sbuttons#1087]
**1 - Describe the bug**
 The text of white background/colored button in **social buttons** of animated buttons section is not visible.

**2 - Expected behavior of what should have happened** 
 The text should be visible of the button, it should not be **blank button**, the reason is that the background color and text color got same due to that it is not visible.

**3 - Supported Screenshot** 
<img width="934" alt="11" src="https://user-images.githubusercontent.com/62640264/97829050-ca7e4880-1cee-11eb-9649-6b3c0cde4e37.png">

**Comment by shahednasser** [comment]
Thank you @SARVESHKHANDELWAL but there's already an issue on this #1000
