### ISSUE TITLE
In footer the examples button should not redirect to github page.

### ISSUE THREAD

**Issue by SARVESHKHANDELWAL** [sButtons/sbuttons#1088]
**Is your feature request related to a problem? Please describe.**
The examples button should not redirect to github page instead of that it should redirect to examples page.
**Describe the solution you'd like**

**Additional notes**

**Comment by SARVESHKHANDELWAL** [comment]
Please close this i added this issue in bug .

**Comment by shahednasser** [comment]
@SARVESHKHANDELWAL you can close this yourself by the way since you are a Member
