### ISSUE TITLE
In footer the examples button should not redirect to github page.

### ISSUE THREAD

**Issue by SARVESHKHANDELWAL** [sButtons/sbuttons#1089]
**1 - Describe the bug**
Is your feature request related to a problem? Please describe.
The examples button should not redirect to github page instead of that it should redirect to examples page.

**4 - Additional notes**
Can i fix this bug??

**Comment by shahednasser** [comment]
Hi @SARVESHKHANDELWAL there's already an issue on this #994 and it has been resolved.
