### ISSUE TITLE
On home page the documentation button is not proper ,it should cover complete dark background.

### ISSUE THREAD

**Issue by SARVESHKHANDELWAL** [sButtons/sbuttons#1090]
**1 - Describe the bug**
On home page the documentation button is not proper ,it should cover complete dark background,as some part is in white background and some in dark.

**2 - Expected behavior of what should have happened (if applicable)**
Making the uniform dark background for documentation button ,we look good instead of half on other and some part on other color background.

**3 - Supported Screenshots** 
<img width="919" alt="12" src="https://user-images.githubusercontent.com/62640264/97830526-424e7200-1cf3-11eb-9ec1-42bcb051fcd4.png">

**Comment by shahednasser** [comment]
Thank you @SARVESHKHANDELWAL but there's already an issue on it #1079 and someone is working on it.
