### ISSUE TITLE
Add copy to clipboard button for code in home page

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1097]
Just like in the documentation page there's a copy to clipboard button for code blocks, the same should be added to code blocks on the homepage.

**Comment by Yashs911** [comment]
Hi @shahednasser I would like to work on this issue

**Comment by mrSidSat** [comment]
### **_Can i work on this issue..??_**

**Comment by shahednasser** [comment]
Yes @Yashs911 since you commented first you can go ahead
