### ISSUE TITLE
Improper spacing between icons and text in social buttons

### ISSUE THREAD

**Issue by hmankodiya** [sButtons/sbuttons#1099]
**1 - Describe the bug** : I found out that there was an improper spacing between the text and login icon in the **social button's block menu.** 

**2 - Expected behavior of what should have happened (if applicable)**: Proper spacing as provided in the basic menu / round menu is expected as shown below.
![image](https://user-images.githubusercontent.com/52171362/97904805-09e87b80-1d67-11eb-9f32-5afbfd30b72a.png)

**3 - Screenshots (if applicable)**: The icon here appears very close to the text.
Here i have shown only few buttons, other buttons like these are also facing the same issue.
![image](https://user-images.githubusercontent.com/52171362/97904238-35b73180-1d66-11eb-98f1-39e52d7e2f3d.png)

**4 - Additional notes**: Increasing the padding might solve the issue.

**Comment by shahednasser** [comment]
I'm not really seeing this problem on my end. Can you provide more info on this (screen width, device and browser, etc...). Please also make sure that this is not due to the cache (by hard refreshing it) as I think we had this problem before and we resolved it. Thank you!

**Comment by hmankodiya** [comment]
Yes you are right , it seems that there is a problem with my browser (Google Chrome) , i saw it on Firefox  and it's all right firefox. 
Thank You for your guidance.

**Comment by shahednasser** [comment]
@hmankodiya is it a cache issue or something else that needs to be worked on?

**Comment by hmankodiya** [comment]
It seems to be not working while using   Google Chrome or even Microsoft Edge but works fine on Firefox, i even  tried browsing it out on chrome of different PCs  but still the same issue prevails.     

As for cache issue, i cleared the browsing history and the cache but it doesn't seem to work .

**Comment by shahednasser** [comment]
Can you provide me with the screen width?

**Comment by hmankodiya** [comment]
yes the screen width of my laptop is 15.6 in with a screen resolution of 1920 x 1080

**Comment by shahednasser** [comment]
I'm still not seeing this @hmankodiya on my side but will leave this up in case anyone can reproduce this. You can also submit a PR for this if you have a fix.
