### ISSUE TITLE
Change text color of yellow dashed button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1105]
Yellow dashed button's text is currently black, it should be changed to yellow (similar to the concept of outline button).

**Comment by mayankmohak** [comment]
I would like to do this.

**Comment by shahednasser** [comment]
Sure go ahead @mayankmohak

**Comment by mayankmohak** [comment]
Actually it is not the problem only with dashed it is common in all yellow button.

Can you please explain me this code for what it is made **dark text** in yellow btn . `color: @darkText !important;`

full code ref.  src/components/_basic.less
```
.yellow-btn {
  .colorRule(@yellow);

  &:not(.fill-color-btn):not(.ripple-btn):not(.outline-btn):not(.transparent-btn):not(.diag-btn):not(.neu-btn),
  &.transparent-btn:not(:hover) {
    color: @darkText !important;
  }
}
```

**Comment by shahednasser** [comment]
@mayankmohak the buttons that have a background color (not transparent) not the text to be black.

**Comment by mayankmohak** [comment]
Well then there could be a better way of doing it.

While going through code i realized more things as unnecessary there were darkText applied for yellow which could be replaced by white as similar to other buttons so made changes accordingly.
@shahednasser  have a look.
