### ISSUE TITLE
Choose different images for Documentation and Examples pages

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1106]
The image that we are currently using in the home page is from [Undraw](https://undraw.co/illustrations), we want different images for each of Documentation and Examples pages. Make sure that the images use the same colors as the one on the homepage.

**Comment by DhrutikPatel** [comment]
Hello @shahednasser can I work on it?

should I show you the images here which I am going to add to website or should I directly add it to website?

**Comment by shahednasser** [comment]
@DhrutikPatel yes you can. You can show them in the PR.
