### ISSUE TITLE
Changes to text in home page

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1109]
The following changes need to be made in the homepage in the "sButtons CDN" section:

1. change "SButtonCDN" to "sButtons CDN" in the section content.
2. Change the URL of the CDN in the code block to "https://cdn.jsdelivr.net/gh/sbuttons/sbuttons/dist/sbuttons.css" and in "sButtons CDN" add a link to it.

**Comment by MitchWijt** [comment]
working on it!

**Comment by DhrutikPatel** [comment]
Hello @shahednasser can I work on it?

**Comment by shahednasser** [comment]
Sorry for the late reply @DhrutikPatel if you still want to work on it then yes go ahead
