### ISSUE TITLE
[BUTTON IDEA]: puff -btn

### ISSUE THREAD

**Issue by adrsh79086** [sButtons/sbuttons#1113]
**1. Name of button**: 
puff btn
**2. Description**: 
on hover the effect is working,
[ezyzip (1).zip](https://github.com/sButtons/sbuttons/files/5483037/ezyzip.1.zip)

**3. Button Type (Animated, Special, etc...)**:
animated

**4. Will you work on it?**:
 i have worked

**Comment by shahednasser** [comment]
Hi @adrsh79086 thank you for always submitting new ideas. I need the opinions of other members on this one. What do you think @HADES-01 @dsnehasish74 ?
