### ISSUE TITLE
Bug in Atom Button

### ISSUE THREAD

**Issue by DhrutikPatel** [sButtons/sbuttons#1114]
**1 - Describe the bug** when we click one atom button animation start but on second click its animation is not stoping.

**2 - Expected behavior of what should have happened (if applicable)** one first click animation should start and on second click it should stop.

**Comment by shahednasser** [comment]
Nice catch. I think this is due because the animation is added on active state as well. Would you like to work on it?

**Comment by DhrutikPatel** [comment]
yes, I will try to fix it.

**Comment by harjotkarwal** [comment]
@DhrutikPatel @shahednasser I think that's not a bug but functionality like the other animated buttons. For refrence, check Aura Pulse button under animated category.

**Comment by shahednasser** [comment]
I'm not seeing the issue in Aura pulse button @harjotkarwal

**Comment by TomWBush** [comment]
The animation stops when you click outisde the button.

**Comment by shahednasser** [comment]
@TomWBush that's true but I think what @DhrutikPatel means is that instead of the animation occuring on `:hover`, it's also occuring on `:active`

**Comment by shahednasser** [comment]
Hello @DhrutikPatel are you still working on this?

**Comment by TomWBush** [comment]
I can work on this

**Comment by shahednasser** [comment]
You can go ahead @TomWBush
