### ISSUE TITLE
Buttons that have more than 3 class names are not displayed properly

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1123]
On the examples page under each button we have class names for that button. Each button should be preceded with a `.` but buttons that have more than 3 classes only has a `.` before the first three class names.

**Comment by adrsh79086** [comment]
I can work on this

**Comment by shahednasser** [comment]
I'll assign you @adrsh79086

**Comment by shahednasser** [comment]
Hi @adrsh79086 any update on this?

**Comment by TomWBush** [comment]
I cannot seem to reproduce the bug. Can you see my screenshot to see if I'm understanding the issue correctly?
<img width="564" alt="Screen Shot 2020-11-13 at 11 27 25 AM" src="https://user-images.githubusercontent.com/34357020/99095512-3724fd00-25a3-11eb-870b-5789f9794fd4.png">

**Comment by shahednasser** [comment]
You can see the problem in [base icons](https://sbuttons.github.io/sbuttons/examples.html#base-icon) and [loading buttons](https://sbuttons.github.io/sbuttons/examples.html#loading). It seems like it's only happening in some cases?

**Comment by TomWBush** [comment]
I've located the issue. If adrsh79086 is no longer working on this, I can fix this real quick.

**Comment by adrsh79086** [comment]
i am working on it

**Comment by Hanaffi** [comment]
@shahednasser  Can you assign me it?

**Comment by Hanaffi** [comment]
@shahednasser  Can you assign it to me?

**Comment by Hanaffi** [comment]
Done.
https://github.com/sButtons/sbuttons/pull/1155

**Comment by shahednasser** [comment]
Hello @Hanaffi but @adrsh79086 is working on it. Please work on unassigned issues.

**Comment by Hanaffi** [comment]
@shahednasser  Thats unfair.
He has been working on it for 15 days! 
That was enough. please reassign it to me and check my PR.

**Comment by shahednasser** [comment]
@Hanaffi please don't say that this is unfair, as you can clearly see someone is assigned to this issue but you chose to work on it. When you want to contribute you should check unassigned issues and comment on them to claim them.
As for the time given, we try to give people the time needed for them to resolve the issue, as this repository is focused on helping contributors.

@adrsh79086 are you still working on this?

**Comment by Hanaffi** [comment]
@shahednasser  Do you think that this one needs 15 days to solve?

**Comment by shahednasser** [comment]
It's not about what I think @Hanaffi . This is a place that encourages people to contribute, not pressure them.

However, as @adrsh79086 hasn't replied, I'll check your PR. But please don't do this again.
