### ISSUE TITLE
[BUTTON IDEA]: Toggle Slide Button using already sButtons designs

### ISSUE THREAD

**Issue by Meffy678** [sButtons/sbuttons#1146]
**1. Name of button**: CustomToggle (?)

**2. Description**: So the idea is a "button" that has several toggle options as a slider version. 

**3. Button Type (Animated, Special, etc...)**: You should be able to use all the button designs that sButtons already has as designs for the slider.

_Please note that this picture is only for reference purpose and is a very early version!_
<img src="https://user-images.githubusercontent.com/55047855/99082837-f807a380-25c4-11eb-971d-b762102c9f11.png" height="30%" width="30%">

**4. Will you work on it?**: Yes, i will work on it.

Feedback will be very appreciated! Especially for the name.

**Comment by shahednasser** [comment]
Hello @Meffy678 thank you for the suggestion! To be honest I'm not a big fan of the idea, as I don't see a use for it. Also, it requires javascript but this is a CSS only project. If you have other suggestions please submit other issues!
