### ISSUE TITLE
[BUTTON IDEA]: Animated Bubble Disperse Button

### ISSUE THREAD

**Issue by richieracoon** [sButtons/sbuttons#1147]
**1. Name of button**:  Animated Bubble Disperse Button

**2. Description**: 

The Button should behave as following:
On last step the bubbles disperse and fade away. 

<img src="https://user-images.githubusercontent.com/46709532/99084479-48800080-25c7-11eb-802b-358bd1be7fe8.png" height="80%" widht="80%">

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Hi @richierubel thank you for the idea. I like it but without the click part, as it requires javascript and this is a CSS only project. Can you do the first two parts only with only CSS?

**Comment by richierubel** [comment]
Hello Shahed,

I'd really like to work on the bottom and I'm confident to do the first 
part CSS-only.

Kind regards,

Richie

**Comment by shahednasser** [comment]
@richierubel unfortunately the bottom part requires javascript and at the moment this is a CSS only project. I'll assign you to this.

**Comment by richieracoon** [comment]
I'm very sorry that I couldn't work on the issue because I was very busy studying, but as the semester progresses I've got more time again and would really really like to work on the issues again? Is it possible to reopen it?
@shahednasser

**Comment by shahednasser** [comment]
Hello @richieracoon of course. I'll reopen it and you can work on it.

**Comment by richieracoon** [comment]
Hello Shahed,
as I looked further into the Idea I realized that it cant be done without JavaScript at all. I'm sorry but I think this Issue should be closed for good.

**Comment by shahednasser** [comment]
Sure @richieracoon we'll reopen it if you find another way
