### ISSUE TITLE
Sidebar on small devices

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1161]
On small devices, the sidebar is cropped at the top (it needs some padding). Also when it is opened in the beginning of the page (when the screen is still on the header) it does not have a background color.

These bugs are only happening between screen widths 991px and 451px

![Screenshot from 2020-11-20 09-40-44](https://user-images.githubusercontent.com/27354907/99773197-bc189500-2b14-11eb-8c04-852cb2c3f3a7.png)

**Comment by JithinAji** [comment]
Hi @shahednasser 

Can you check again I think this one has been corrected already.

**Comment by shahednasser** [comment]
@JithinAji it seems the transparent background is fixed, however there's still the problem with the margin in the specified screen width, and another problem is when the sidebar is opened on a small device and then the screen is enlarged the sidebar is visible at the top of the page.

**Comment by JithinAji** [comment]
Can you please assign this to me. I will try to fix this as soon as I can.
