### ISSUE TITLE
[BUTTON IDEA]:REFLECTION BUTTON

### ISSUE THREAD

**Issue by mrSidSat** [sButtons/sbuttons#1168]
**1. Name of button**: 
Reflect button
**2. Description**: 
Its a simple button but looks good 
**3. Button Type (Animated, Special, etc...)**:
Simple button
**4. Will you work on it?**:
yes
![reflect  Button](https://user-images.githubusercontent.com/58354243/99978919-8bfb1b80-2dcc-11eb-83a7-8940e68a3c5c.png)

**Comment by shahednasser** [comment]
@mrSidSat is that different than the glossy button?

**Comment by mrSidSat** [comment]
![reflect-button](https://user-images.githubusercontent.com/58354243/100307391-bb2bab80-2fcb-11eb-8160-5db7066fbf09.png)
![glossy-button](https://user-images.githubusercontent.com/58354243/100307436-d4345c80-2fcb-11eb-8b77-bdce3b11f2da.png)

### _I think there are sure some differences_

**Comment by shahednasser** [comment]
I think they're pretty similar so unfortunately, I don't think we should work on it. Feel free to submit another idea if you have any!
