### ISSUE TITLE
Add documentation for dark mode class

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1187]
Now that dark mode is almost finished, we need to add in the documentation how it can be used. The documentation needs to be added in the README and the documentation page on the website.

The documentation should indicate that a button can be used in dark mode either by adding the `.dark-mode` class to the button, or by adding the attribute `data-theme="dark"` to a container element like the body element.

**Comment by alok1929** [comment]
@shahednasser hello ,im new at this but i could try , can i know how i can get started with this as soon as possible,thanks in adavance

**Comment by shahednasser** [comment]
Hello @alok1929 . I suggest you read the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/9f26af8f73aca60bc53f6654dfc5a9bb3e575ab1/CONTRIBUTING.md) first to get a general idea of the repository's structure. As I mentioned in the issue, you will need to edit the README.md and documentation.html. The content should be similar. You just need to add that a button can be used for dark mode if the class `dark-mode` is added to it or if the attribute `data-theme="dark"` is added to a parent element.
I'll assign you. if you need any help let me know.

**Comment by alok1929** [comment]
hello @shahednasser i am working on the #1187 issue and to add the dark mode button,should the code be <button class=".dark-mode"></button>.I think its wrong ,could you please send the correct code

**Comment by alok1929** [comment]
hey @shahednasser  ,im working on #1187 and im not finding what code should be added for the dark mode class , i tried adding it as a <code><button class="dark-mode" type="button"></button></code>but its just showing a blank button,i would like help with writing this

**Comment by alok1929** [comment]
hey @shahednasser ,im working on #1187 and im not finding what code should be added for the dark mode class , i tried adding it  as ` <button class=".dark-mode">dark-mode</button>` but  its just showing a blank button,i would like help with writing th

**Comment by shahednasser** [comment]
Hello @alok1929 . to add the dark mode class it should be something like this:

```
<button class="sbtn dashed-btn white-btn dark-mode">Dark Mode</button>
```

You shouldn't add . in front of the class.

**Comment by alok1929** [comment]
Thank you

**Comment by alok1929** [comment]
What should it be to add it as an attribute ,as data theme="dark",should it
be in the body element tag or someplace else , please do tell.

**Comment by shahednasser** [comment]
You need to write in the documentation that it can be for any container element of the button. You can use this as an example:

```
<body data-theme="dark">
   <button class="sbtn dashed-btn white-btn">Dark Mode</button>
</body>
```

**Comment by alok1929** [comment]
Thank you for the clarification. I'll add this to readme.md as well.This is
my first issue,so will try my best

**Comment by harshitaaaaaa** [comment]
Hey @shahednasser I'm learning to contribute in open-source. I've added documentation for dark button in both documenttion.html and README.md . However, I'm unable to understand it's use, like if we click on dark mode button it doesn't toggle the file to dark-mode.

**Comment by shahednasser** [comment]
Hello, @harshitaaaaaa . I'm not really sure I understand what you mean. Please clarify more but do it in a [new discussion](https://github.com/sButtons/sbuttons/discussions/new)
