### ISSUE TITLE
Add dark mode button in mobile view

### ISSUE THREAD

**Issue by HeinKhantZaw** [sButtons/sbuttons#1214]
**Is your feature request related to a problem? Please describe.**
Although there's a dark mode button in desktop view, there's no such button in mobile view.

**In Mobile**
![132466590_136485754911363_2900910703364895533_n](https://user-images.githubusercontent.com/40730345/102743697-612dc400-4386-11eb-8955-1d92fbb1b1fb.jpg)

**In desktop**
![image](https://user-images.githubusercontent.com/40730345/102743762-8ae6eb00-4386-11eb-989b-982b3e05b453.png)

**Describe the solution you'd like**
I think we should add this dark mode feature for mobile phone users too.

**Comment by shahednasser** [comment]
Good idea @HeinKhantZaw would you like to work on it?

**Comment by HeinKhantZaw** [comment]
ok, I'll give a try.

**Comment by ritik307** [comment]
@HeinKhantZaw I think its a great idea . I would like to work on this issue .
**Describe the solution you'd like**
I would like to add the dark mode button on the top right corner.
