### ISSUE TITLE
Paper Curl Button animation ficker

### ISSUE THREAD

**Issue by bw-space** [sButtons/sbuttons#1222]
**1 - Describe the bug**
When hovering near the bottom right of the paper curl button, there is a flickering animation, of random open and close of paper curl
**2 - Expected behavior of what should have happened (if applicable)**
Hovering at any part of the button should show the paper curl animation once.
**3 - Screenshots (if applicable)**

**4 - Additional notes**

**Comment by shahednasser** [comment]
Thank you @bw-space for reporting this bug. Would you like to work on it?
