### ISSUE TITLE
[BUTTON IDEA]: Striped Button Click Animation

### ISSUE THREAD

**Issue by bw-space** [sButtons/sbuttons#1223]
**1. Name of button**: 
Striped Button
**2. Description**: 
We can create a new Animated version of the Striped Button, when its clicked upon, a strip animation can play, like the strips moving diagonally towards the bottom left.
**3. Button Type (Animated, Special, etc...)**:
Animated
**4. Will you work on it?**:
Yes

**Comment by shahednasser** [comment]
Sounds good @bw-space would you like to work on it?

**Comment by dumbcoder7** [comment]
Is someone solving this issue? There is no assignee @shahednasser @bw-space ? I see the `up-for-grabs` label. But the author has mentioned that they are interested to work. Please clarify if possible.

**Comment by bw-space** [comment]
@shahednasser due to some work commitments, I am unable to work on this issue, please assign someone who is interested. Thanks for understanding.

**Comment by J-16** [comment]
Hey, can I work on this?

**Comment by dumbcoder7** [comment]
I wanna work on it too

**Comment by J-16** [comment]
No prob mate, take it :-)

**Comment by adityaraute** [comment]
I have created the button, where the animation plays on hovering.
Here is the animation. 
![captured](https://user-images.githubusercontent.com/43912470/105613408-508ac680-5de8-11eb-8334-5ff57b8c381f.gif)


I shall be raising a PR soon.
