### ISSUE TITLE
[BUTTON IDEA]: button shadow of familiar color of the button go into disco mode while hover.

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1224]
button shadow of familiar color of the button go into disco mode while hover.

_Originally posted by @ritvikmahajan17 in https://github.com/sButtons/sbuttons/discussions/1221_

**Comment by ritvikmahajan17** [comment]
can you assign this to me ? :)

**Comment by harshad71** [comment]
when you press button it will squeeze the color 
and when you release it will reversed .
kind a funny idea 😄

**Comment by shahednasser** [comment]
@ritvikmahajan17 I have assigned it to you
