### ISSUE TITLE
Disable horizontal scrolling of website on small devices

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1226]
On small devices, the website can be scrolled horizontally. This issue is not seen on resizing the window to a smaller width, but on using mobile devices and trying to scroll horizontally.

**Comment by mg143pavankumar** [comment]
can you assign this to me ?

**Comment by dsnehasish74** [comment]
@mg143pavankumar  yes you can start working on it .

**Comment by MattMarquise** [comment]
Has it been fixed yet? Typically this can be achieved by simply adding the 
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
within your `<head>` section. If that doesn't fix this issue there a couple other tricks that should likely solve this.

**Comment by nemanjagaric** [comment]
Hello can you assign me?

**Comment by MattMarquise** [comment]
@nemanjagaric I'm not sure if anyone has been properly assigned or has fixed this issue.

**Comment by mg143pavankumar** [comment]
I had fixed it @MattMarquise

**Comment by MattMarquise** [comment]
Okay @mg143pavankumar. We can close this issue then

**Comment by mg143pavankumar** [comment]
Ya you can. @MattMarquise

**Comment by MattMarquise** [comment]
@mg143pavankumar You have to have made a pull request for this issue in order to close this.

**Comment by mg143pavankumar** [comment]
@MattMarquise  I had already made a pull request. You can check it in pull request section

**Comment by MattMarquise** [comment]
@mg143pavankumar It appears you haven't linked it in this issue yet. That is what closes it

**Comment by mg143pavankumar** [comment]
@MattMarquise  I had already made pull request. But it is not yet merged.

**Comment by MattMarquise** [comment]
Okay. it should be merged once repo admins come to it
