### ISSUE TITLE
Improve Footer Design

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1237]
I think it would look better if the footer design changed. The logo should be moved to the left, and the notice that's currently at the left would be put below it.

It should also be containered instead of full width. In addition, the icons and links on the right should have the text aligned to the left.

**Comment by manish193** [comment]
Hi @shahednasser, I would like to work on this enhancement.

**Comment by shahednasser** [comment]
Sure @manish193 I will assign you

**Comment by manish193** [comment]
I made some changes, but the text item under the logo does not seem right. So instead I interchanged the position of logo and text. 
I left aligned links.
Now it seems much cleaner than before

![Footer](https://user-images.githubusercontent.com/47421953/106306287-da70de80-6283-11eb-8db8-6ac3cba75c32.png)

**Comment by shahednasser** [comment]
Unassigning @manish193 due to inactivity

**Comment by Bc-coding** [comment]
Hi Shahednasser, is anyone working on this footer enhancement? if not, please could I give it a go?

**Comment by shahednasser** [comment]
Hello @Bc-coding no one is working on it, I'll assign you

**Comment by navoditbharat** [comment]
Can you assign this issue to me?

**Comment by shahednasser** [comment]
Hello @navoditbharat someone else is working on this, please find an unassigned issue to work on
