### ISSUE TITLE
Fix alignment for Image in Documentation Page

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1238]
In the [documentation](https://sbuttons.github.io/sbuttons/documentation.html) page, the image should be aligned more center with the text (similar to how the home page is). Either the alignment of the image or the size should be changed.

**Comment by tnahddisttud** [comment]
Hey! I would like to contribute. Please assign it to me.

**Comment by shahednasser** [comment]
Hello @tnahddisttud sorry for the delay. I'll assign you the issue

**Comment by ParseSnip** [comment]
Has the issue been resolved?

**Comment by shahednasser** [comment]
Hello @ParseSnip someone is currently assigned to it. If you would like to contribute please check out other issues we have in the repo!

**Comment by shahednasser** [comment]
hi @tnahddisttud are you working on this?

**Comment by tnahddisttud** [comment]
> hi @tnahddisttud are you working on this?

I'm really sorry, I have been busy with some tests. I promise to get it done by Sunday. Really sorry for the delay.

**Comment by tnahddisttud** [comment]
Hello @shahednasser, I have created a pull request.

**Comment by tnahddisttud** [comment]
I have made the requested changes. Please check
