### ISSUE TITLE
Fix click on download link scroll

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1239]
In documentation page, when clicking on the download link "click here" under [download CSS file](https://sbuttons.github.io/sbuttons/documentation.html#downloadcss) link, it scrolls to the beginning of the page. This is due to the fact that link is set to `#`. It should be changed to the id of its container to prevent the scroll.

**Comment by jleckron** [comment]
I would also like to resolve this issue.

**Comment by shahednasser** [comment]
Hello @jleckron I'll assign you
