### ISSUE TITLE
Change link to variables file

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1241]
In the documentation page under [Modify Button Colors](https://sbuttons.github.io/sbuttons/documentation.html#modify) the link to the variables file goes to `sbuttons.less` instead. The text should be changed to "_variables.less" and the link as well.

**Comment by jleckron** [comment]
I can resolve this as well.

**Comment by shahednasser** [comment]
Hello @jleckron let's give some time for someone else to try it out. If no one does I'll assign you!
