### ISSUE TITLE
Add padding prior to text that's below buttons in documentation

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1242]
In the documentation page when there's a text that's below a button (for example [basic buttons](https://sbuttons.github.io/sbuttons/documentation.html#basic)) padding should be added above the text. This should be done to all same cases throughout the page.

**Comment by jleckron** [comment]
Hi, I would like to attempt to solve this!

**Comment by jleckron** [comment]
I have a fix and a PR ready to go. Please let me know if I need to be officially assigned before I submit PR. (This is my first open-source contribution)

**Comment by shahednasser** [comment]
Hello @jleckron you may submit the PR
