### ISSUE TITLE
Make content in documentation page containered

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1243]
The main content of the documentation page should be containered (placed inside div with class "container"). Furthermore, the classes of the sidebar should be changed to `col-md-3 d-md-block sidebar-div` and the classes for the second column (containing the main content) should be changed to `col-md-9 col-12`.

**Comment by fleventy-5** [comment]
Hey @shahednasser can I take this issue?

**Comment by shahednasser** [comment]
Sure @fleventy-5 go ahead

**Comment by fleventy-5** [comment]
Can you help me  I got a merge conflict error.

**Comment by shahednasser** [comment]
can you submit a PR again?
