### ISSUE TITLE
Change instruction block width

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1244]
Make the max width of `.instruction-block` 700px to match the code block.

**Comment by fleventy-5** [comment]
Hi , I'm new to open source  and would like to contribute. I have some experience in HTML, CSS and JS can i do anything to contribute to this  issue

**Comment by shahednasser** [comment]
Sure @fleventy-5 I'll assign you. Let me know if you need any help.

**Comment by fleventy-5** [comment]
Can you tell me the location of the css sheet name  containing ' .instruction-block' class I have clone the project to my local machine but i could not find the css sheet containing  the given class issue

**Comment by fleventy-5** [comment]
I got it the required sheet :) and i have set the max width to 700px what do i have to do after this?

**Comment by shahednasser** [comment]
You should submit a pull request. Please refer to our [contributing guidelines](https://github.com/sButtons/sbuttons/blob/d7a2cb416701d7f1cb751e3b0aa86f6694598df3/CONTRIBUTING.md) to learn more but if you still are not sure how to do it then let me know.

**Comment by fleventy-5** [comment]
Hi there @shahednasser  I have made the required changes and   pull request. I hope i have done it to the required specs.
