### ISSUE TITLE
Fix base icon button class in Documentation Page

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1245]
In documentation page under [Icon with no background](https://sbuttons.github.io/sbuttons/documentation.html#iconNoBg) change the class of the example button from `base-icon-btn` to `icon-btn`. This should be changed in the button and the code example

**Comment by pri1311** [comment]
Hie, Please assign me this issue.

**Comment by shahednasser** [comment]
Sure @pri1311 you can work on it
