### ISSUE TITLE
Replace br elements with padding in documentation page

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1246]
In documentation page, a lot of `<br>` elements are used instead of padding to create similar outcome. Replace all occurrences of `<br>` elements with padding as necessary.

**Comment by onwuvic** [comment]
@shahednasser can I take up this task?

**Comment by shahednasser** [comment]
Hello @onwuvic sure go ahead

**Comment by onwuvic** [comment]
@shahednasser Is `padding` the right CSS property to use or margin? I was thinking `margin` will be appropriate. What do you think?

**Comment by shahednasser** [comment]
@onwuvic if you think margin is better then use it I don't mind
