### ISSUE TITLE
Update CDN links

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1247]
Update CDN links throughout the website to the following link: https://cdn.jsdelivr.net/npm/sbuttons/dist/sbuttons.min.css

**Comment by davanu100** [comment]
Hey I am new to open source , but have been working on the required skills for a long time. I would like to contribute to your project

**Comment by shahednasser** [comment]
Hello @davanu100 sure I will assign you

**Comment by davanu100** [comment]
Could you tell me in brief ,what to do??

**Comment by shahednasser** [comment]
In the website (the html pages `index.html`, `documentation.html` and `examples.html`) we use the CDN link, for users to download. for example in the header the download link or in the documentation page in the text. We need to change the CDN link to the one I provided in the issue above.

**Comment by davanu100** [comment]
Ok, I'll get to it right now. Thanks.

**Comment by davanu100** [comment]
I have made the pull request. Please look into it and if there's an issue , let me know .
