### ISSUE TITLE
Submissions for projects that use sButtons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1255]
We need to add a page for projects that use sButtons and link to them. So, if anyone is using this project or is considering using it, please link it below this issue to be added on the list of projects that are using sButtons. This would be great to provide others an example of what using sButtons will look like in their projects.

**Comment by DurveshKumarPal** [comment]
Can I contribute to this project?

**Comment by shahednasser** [comment]
Hello @DurveshKumarPal of course you can! You can either by working on one of the open unassigned issues, submitting a new issue for a new button idea, enhancement, or bug fix.

This issue in particular is about adding projects that use sButtons to our website. So, if you have any submissions you can create a PR as detailed in the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/81c03f2f535361247f7831ecf77d701106ffa6d8/CONTRIBUTING.md)

**Comment by adarshnjena** [comment]
Can I work on this issue ?

**Comment by shahednasser** [comment]
Hello @adarshnjena thank you for your interest in contributing to sButtons. This issue is an issue that is always open and it means submitting new entries for projects that are using sButton.

If you know of a project that is using sButtons and you want to add it, then please go ahead!

**Comment by harmanpreet7916** [comment]
Hello! I am a beginner and I want to work on this issue. please help me to know more about the  issue

**Comment by shahednasser** [comment]
Hello @harmanpreet7916 thank you for your interest! Please refer to the previous comment on this thread.

**Comment by Bunny77K9** [comment]
I would like to work on this issue. Can you assign me to it?

**Comment by ginabeki** [comment]
I would like to work on this issue

**Comment by shahednasser** [comment]
Hi @ginabeki if you know of any projects using sButtons you can always send a PR to add them. You can refer to the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/23a4ca8114c36b56bfafc94219578e27793cee2c/CONTRIBUTING.md) to learn how to do that.
