### ISSUE TITLE
Move Loader in Examples Page below heading

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1257]
In the examples page, the loader that appears before the buttons are loaded is above the heading "Some Examples Of sButtons
" it should be below it.

**Comment by harshpandey002** [comment]
Hi @shahednasser,
I would like to resolve this issue, Please assign this to me.
Thanks

**Comment by shahednasser** [comment]
I have assigned you @harshpandey002

**Comment by harshpandey002** [comment]
Hi @shahednasser,

I've fixed the issue and created a pull request.
Kindly review and let me know if any change is required.

Thanks
