### ISSUE TITLE
Sidebar behavior before scroll

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1258]
Before scroll, the sidebar's width is larger than when scrolling. The sidebar's width should always be the same. This is in the documentation and examples pages.

**Comment by harshad71** [comment]
i would like to work on this issue  will you suggest me to get started?

**Comment by shahednasser** [comment]
Hello @harshad71 sure I'll assign you

**Comment by harshad71** [comment]
ok i m working on this issue

**Comment by shahednasser** [comment]
Hello @harshad71 any update on this?

**Comment by neelbavarva** [comment]
Is this issue open? I would like to work on it.
![simplescreenrecorder-2021-02-19_10 33 48](https://user-images.githubusercontent.com/62550592/108460534-df331c00-729e-11eb-950a-ac558cf0a097.gif)
This is what you want right?

**Comment by shahednasser** [comment]
As @harshad71 is not responding, I'll assign you @neelbavarva
