### ISSUE TITLE
Make shadow of Gradient Button smaller

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1259]
The shadow of [gradient button](https://sbuttons.github.io/sbuttons/examples.html#gradient) makes it out of place when used on a website. The box shadow should be smaller, making it look better.

**Comment by sawantvikram** [comment]
I want to work on this issue... can you assign it to me???

**Comment by shahednasser** [comment]
Sure @sawantvikram go ahead

**Comment by sawantvikram** [comment]
where is the issued  file

**Comment by shahednasser** [comment]
all changes to buttons should be made in `src` folder. Files in it are separated based on the type of the button. You can find the gradient button [here](https://github.com/sButtons/sbuttons/blob/master/src/components/styles/_gradient.less).

You can find out more by checking out the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/d7a2cb416701d7f1cb751e3b0aa86f6694598df3/CONTRIBUTING.md)

**Comment by sawantvikram** [comment]
should I create a new button???

**Comment by sawantvikram** [comment]
i have sent pull resquest please check it...

**Comment by shahednasser** [comment]
unassigning due to inactivity

**Comment by abid1998** [comment]
Hi is this still open ?

**Comment by shahednasser** [comment]
Hello @abid1998 yes it is would you like to work on it?

**Comment by abid1998** [comment]
Hi yes ! Can you explain me what needs to be done ?

**Comment by abid1998** [comment]
I went through the code once from what i understand i have to change 
&:hover {
    box-shadow: 0px 6px 4px @...;
  }
property to make it smaller? I am planning on making it 0px 4px 2px and trying. 
Should i also reduce also the default box-shadow size or just the hover one?

**Comment by shahednasser** [comment]
Hi @abid1998 please reduce its size for both default and hover. Choose what you feel fitting and I'll look over it when you submit a PR.

**Comment by abid1998** [comment]
@shahednasser great thanks alot !

**Comment by abid1998** [comment]
@shahednasser created a PR please check it.
