### ISSUE TITLE
Add "Copy" link icon to headings in documentation and examples pages

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1260]
In the documentation and examples pages, we need to add a "copy" link icon that copies the link of the current section for the user. 
I prefer a single function to handle both pages on click event for the copy icon.

You can use [this](https://fontawesome.com/icons/link) link icon. It should take the id of the section and add it to the end of the URL as hash (for example, https://sbuttons.github.io/sbuttons/examples.html#gradient)

**Comment by fleventy-5** [comment]
Can I take this one?

**Comment by shahednasser** [comment]
Sure @fleventy-5 go ahead

**Comment by fluffyP4nd4** [comment]
![img](https://user-images.githubusercontent.com/57084379/106310129-21150780-6289-11eb-9344-894ec41951c0.png)
Hey @shahednasser  I was able to add the link icon to all the example buttons. But I have to click the icon twice for the url to be copied. Do you have any solution for this problem??

**Comment by fleventy-5** [comment]
![img.png](https://user-images.githubusercontent.com/78148524/106310597-cfb94800-6289-11eb-8906-2e0a738c1102.png)
Hey @shahednasser  I was able to add the copy link to all the button examples . But I have to click the copy icon twice most of the time for the section url to be copied. Do you have any suggestions for this problem?
