### ISSUE TITLE
Add transition property to Rounded Bottom button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1262]
Transition property with value `all .2s` should be added to the [Rounded Bottom button](https://sbuttons.github.io/sbuttons/examples.html#rounded-bottom)

**Comment by angelascode** [comment]
I would like to work on this.  Please assign to me.  Thank you

**Comment by shahednasser** [comment]
Hello @angelascode sorry for the delay. I will assign you

**Comment by mainak-debnath** [comment]
Is this issue still up for grabs?I would like to give it a try

**Comment by shahednasser** [comment]
Hello @mainak-debnath since @angelascode isn't responding you can go ahead

**Comment by kshitij-18** [comment]
I am working on this

**Comment by kshitij-18** [comment]
I have made a pull request please check
