### ISSUE TITLE
Add transition property for Rounded Diagonal buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1263]
Transition property with value `all .2s` should be added to the [Rounded Diagonal buttons](https://sbuttons.github.io/sbuttons/examples.html#rounded-diagonal-tl) both top left and top right

**Comment by angelascode** [comment]
I'll resolve this issue also.  Please assign. Thanks

**Comment by shahednasser** [comment]
@angelascode I have assigned you the issue

**Comment by shahednasser** [comment]
Unassigning @angelascode due to inactivity

**Comment by mainak-debnath** [comment]
I can work on this one too

**Comment by shahednasser** [comment]
Sure @mainak-debnath I'll assign you
