### ISSUE TITLE
Add transition property to Rounded Top Buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1264]
Transition property with value all .2s should be added to the [Rounded Top buttons](https://sbuttons.github.io/sbuttons/examples.html#rounded-top)

**Comment by angelascode** [comment]
I'd like to resolve this issue.  Please assign.  Thanks.

**Comment by shahednasser** [comment]
@angelascode I have assigned you the issue

**Comment by harshpandey002** [comment]
Hi @shahednasser,
I'm learning to contribute to open sources, I'm familiar with the process but want to try those git commands for the first time so that I can gain some confidence before moving to big projects. So can I please work on this issue ?

**Comment by harshpandey002** [comment]
Hi @shahednasser,
I'm learning to contribute to open sources, I'm familiar with the process but want to try those git commands for the first time so that I can gain some confidence before moving on to big projects. So can I please work on this issue ?

**Comment by shahednasser** [comment]
Hello @harshpandey002 this issue is already assigned, please comment on an unassigned issue and I'd love to assign you!

**Comment by harshpandey002** [comment]
Thank you @shahednasser for the kind reply,

I have resolved this issue and created a pull request, 
you can decline the PR, I've no problem 😃 

Thanks Again !!

**Comment by shahednasser** [comment]
Unassigning @harshpandey002 due to inactivity

**Comment by shahednasser** [comment]
Hello @angelascode are you still working on this issue?

**Comment by Sarthak1306** [comment]
Hi, very new to contributing to Open Source and I'd like to resolve this issue!

**Comment by shahednasser** [comment]
As @angelascode is not responding I'll assign you @Sarthak1306
