### ISSUE TITLE
Create Page for Projects Using sButtons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1266]
We need to create a page for projects using sButtons. Submissions will be sent to issue #1255 . Currently the only project I know of is [this](https://github.com/ChristopherMarques/uuidGenerator) one, so you should create a page that includes this project for now, but make sure that all projects to be added will have the same format and design.

The page should have a header like the current pages on the website, but the sidebar is not necessary. The design for each of the projects that will be added is up to you. You can look through examples online for maybe card-like designs, maybe on codepen. Whatever you find best.

**Comment by ADHIKSHA** [comment]
Hey, Would love to work on this issue. Can you assign it to me?

**Comment by shahednasser** [comment]
Sure @ADHIKSHA go ahead

**Comment by lekandev** [comment]
Please if @ADHIKSHA is not working on it can I?

**Comment by Abir-Tx** [comment]
I would also love to work on it. Would be great if I get assigned to this
**Thanks**

**Comment by shahednasser** [comment]
@ADHIKSHA let us know if you're still working on this

**Comment by shahednasser** [comment]
Unassigning @ADHIKSHA due to inactivity

**Comment by Caleb335** [comment]
@shahednasser, Is there anyone still working on this?

**Comment by shahednasser** [comment]
@Caleb335 no one is working on it, I'll assign you

**Comment by Caleb335** [comment]
Awesome, thanks.

**Comment by Caleb335** [comment]
@shahednasser, should I just go along with any layout that I feel would be okay for this page?

**Comment by shahednasser** [comment]
@Caleb335 Yes I don't have any layouts or design in mind, but it should be easy to add a new project that uses sbuttons in the future. Maybe we should include in the contribution guidelines how to do that after you have a design set for displaying projects

**Comment by Caleb335** [comment]
Alright, I'd work on that.

**Comment by Caleb335** [comment]
Hi @shahednasser, I figured out the responsiveness of the navbar on mobile is affected due to the additional nav-item (i.e the projects) Take a look at the screenshot below. 

![Screenshot from 2021-02-19 17-41-27](https://user-images.githubusercontent.com/48127194/108533863-c562fa80-72d9-11eb-8500-033b934e4b60.png)


I would go on to hide the navlinks on mobile, such that when the hamburger menu is clicked it displays them. Let me know if you're okay with this approach.

Thanks

**Comment by Caleb335** [comment]
Hi @shahednasser, I'm waiting for your response on this.

**Comment by shahednasser** [comment]
Hi @Caleb335 sorry I was busy. Yes we have an open issue for the navbar and someone is assigned to it now, so don't worry about it

**Comment by Caleb335** [comment]
Alright then, no problem.
