### ISSUE TITLE
Add .hover class for force button hover appearance

### ISSUE THREAD

**Issue by cosay** [sButtons/sbuttons#128]
:hover is not trusted attribute so You can't set it programmatically (ex. using JS).
We can add a CSS class to handle this state.
It can be used for button hover animation, for triggering from another hover, etc.

This solution is used, for example, in bootstrap buttons (.active class).

If you think the idea is good, I can work on it. Just assign me  :)

**Comment by shahednasser** [comment]
I'm not sure I understand exactly what the issue is. Can you please elaborate more? Where can the issue be found or what is needed to be changed or fixed

**Comment by cosay** [comment]
This is a **new feature**. I would like to add a css .hover class for each button that has a :hover state.
This will allow you to change the button hover state using Javascript.

**Comment by cosay** [comment]
Example:

To every :hover pseudo-class like this:

```
&:hover {
    animation: pulse 1s infinite;
}
```

I would like to add a class .hover

```
&:hover,
&.hover {
    animation: pulse 1s infinite;
}
```

**Comment by shahednasser** [comment]
I'm not really sure what the purpose of this would be honestly. Plus, this would mean that we would have to add Javascript to the button's functionalities as well (i.e. if someone would use them, they would have to download the css and javascript).

**Comment by cosay** [comment]
No, we just add one class in CSS for each button (.hover class).
I will prepare an example to present what exactly is going on :)

**Comment by GoodnessOlawoore** [comment]
I think I understand this, kindly assign it to me.

**Comment by GoodnessOlawoore** [comment]
> I think I understand this, kindly assign it to me.

Thank you @shahednasser  , I will work on it

**Comment by shahednasser** [comment]
@GoodnessOlawoore any update on this?

**Comment by cosay** [comment]
> @GoodnessOlawoore any update on this?

I'll do it today :)

**Comment by cosay** [comment]
But not yet added for all buttons.
I will try to finish tomorrow :)

Example how to use this feature:
https://jsfiddle.net/cosay/3okb8rs0/
