### ISSUE TITLE
[BUTTON IDEA]: Icon Fill Button

### ISSUE THREAD

**Issue by BeniB98** [sButtons/sbuttons#1294]
**1. Name of button**: 
Icon Fill Button

**2. Description**: 
White Button with colored Icon and Border and black text. On Hover the text fills up with the color of the Icon. 

**3. Button Type (Animated, Special, etc...)**: 
Icon / Animated

**4. Will you work on it?**:
yes

**Comment by alok1929** [comment]
### should we do this with less itself or css and html, if its with less, i could try to do it, _please assign it to me_

**Comment by shahednasser** [comment]
Hello @BeniB98 I'm not sure about what the icon will look like, so either show me a pic or video of it or submit a PR and I'll have to decide then if I can accept it or not.

Either way I'll assign you

**Comment by BeniB98** [comment]
https://user-images.githubusercontent.com/49996504/107936628-29588c80-6f83-11eb-86a1-91ecb550b474.mp4

Hey @shahednasser, thanks for assigning me! I thought of something like this. What do you think about it?

**Comment by shahednasser** [comment]
I think the button looks good without the icon and maybe with some padding. If you can make the button but with different colors like in the website then that would be great.

**Comment by BeniB98** [comment]
Hey @shahednasser, i'm sorry but currently i don't have the time to work on the Issue. Maybe @alok1929, or anyone else, still want to work on it?

**Comment by shahednasser** [comment]
Sure I'll leave it open if anyone else wants to work on it

**Comment by alok1929** [comment]
I could try to do it , would like to be assigned for this @shahednasser

**Comment by shahednasser** [comment]
Sure @alok1929 I'll assign you

**Comment by shahednasser** [comment]
Hello @alok1929 are you still working on this?

**Comment by alok1929** [comment]
No I am not ,I have my exams going on ,so I might not be able to do it . .
....

**Comment by shahednasser** [comment]
Alright I'll be unassigning you in case someone else can take this up

**Comment by shahednasser** [comment]
Alright I'll be closing this for now then
