### ISSUE TITLE
Properly center button title

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1311]
Button titles are not properly centered, someone used margins instead of properly centering the title.

The title should be properly centered horizontally. You can look below for an example.

![Not centered title](https://user-images.githubusercontent.com/27354907/108503678-773ffe00-72bd-11eb-8e2d-1fb8eeb5fcdc.png)

**Comment by 3n1k0** [comment]
Hi @shahednasser, can I pick this up?

**Comment by shahednasser** [comment]
Hello @3n1k0 yes I'll assign you
