### ISSUE TITLE
Navbar Menu on small devices

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1312]
@JLambertazzo noticed some weird behaviour on the navbar when viewing on a small screen. 

The proposed change is to have a dropdown menu that shows only on smaller screens. The dropdown menu should include the links that are currently in the navbar.

_Originally posted by @JLambertazzo in https://github.com/sButtons/sbuttons/discussions/1299_

**Comment by dsnehasish74** [comment]
I want to solve this issue

**Comment by shahednasser** [comment]
I'll assign you @dsnehasish74
