### ISSUE TITLE
[BUTTON IDEA]:

### ISSUE THREAD

**Issue by tanzil786** [sButtons/sbuttons#1332]
**Dropdown buttons**: 

**Example of using a dropdown menu with a button:*: 

**The dropdown animation happen downward side**:

**Yes**:

**Comment by shahednasser** [comment]
Thank you for submitting this idea. Unfortunately, this idea requires javascript and this is a CSS-only project. Please submit any other idea you have that is related to it!

**Comment by shahednasser** [comment]
Thank you for submitting this idea. Unfortunately, this idea requires javascript and this is a CSS-only project. Please submit any other idea you have that is related to it!

**Comment by shahednasser** [comment]
Thank you for submitting this idea. Unfortunately, this idea requires javascript and this is a CSS-only project. Please submit any other idea you have that is related to it!
