### ISSUE TITLE
Footer link problem

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#1336]
**1 - Describe the bug** In the footer of the documentation and examples page the examples link is pointing to the github repo as it should pointing to the examples page of our website

**Comment by theBeginner86** [comment]
@dsnehasish74, May I work on this issue.

**Comment by dsnehasish74** [comment]
@theBeginner86  yes sure. I am assigning you this issue

**Comment by theBeginner86** [comment]
@dsnehasish74 
I have made the PR you may please check.
