### ISSUE TITLE
Improve project page

### ISSUE THREAD

**Issue by TomWBush** [sButtons/sbuttons#1344]
**Is your feature request related to a problem? Please describe.**
I have two suggestions regarding how to change the project panel in the new project page.
1. Remove the Demo button, and make the whole panel clickable and redirects to the demo page. The reason is that the panel has an onhover effect, so I think it's more intuitive to make the panel clickable.
2. Change "View on Github" to the Github icon.

**Additional notes**
If you agree with any of my suggestions, I can work on it.

**Comment by shahednasser** [comment]
Hi @TomWBush thank you for your suggestions. I'm actually working on redeveloping the entire website using React and TailwindCSS, you can check it out in the second branch. So, as if now let's not make improvements unless necessary. I will however take your comment into account when redeveloping the website!
