### ISSUE TITLE
Projects Using Sbuttons Page

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#1346]
**1 - Describe the bug**
When we hover a link of the dropdown menu of this projects page Its background turns into white that is looking bit odd rather I think the design should be like home page dropdown links.

**3 - Screenshots (if applicable)**
![Screenshot (545)](https://user-images.githubusercontent.com/58779604/111017270-5c523c80-83d8-11eb-94f5-b5643bcc5e6d.png)

**Comment by owen-young** [comment]
I am currently working on this issue.
