### ISSUE TITLE
Create 404 Page

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1352]
We have recreated the website using React and TailwindCSS. We currently have 4 pages: Home, Documentation, Examples, and Projects Using sButtons. 

We need to create a 404 page as a fallback for a URL that does not match any of these pages.

**Comment by ShrutiKatpara** [comment]
Hey @shahednasser , I would like to take this up. Thanks :)

**Comment by shahednasser** [comment]
Hello @ShrutiJha31 I'll assign you

**Comment by ShrutiKatpara** [comment]
Hey @shahednasser, I have created below 404 page for now. 
![image](https://user-images.githubusercontent.com/45987734/111526934-54eab480-8785-11eb-8a9a-3f51ef6a2731.png)

So, this is actually done using `Router` i.e. on client side. Is it the same way that you wanted it to be done ? Or whether we have to do it on server part using SPA ?

Thanks :)

**Comment by shahednasser** [comment]
We just need it client side. But please add something maybe an image in the middle to show it's 404 or something. You can undraw or anything you like.

Also, make sure the page follows the same format as other pages and that the footer sticks to the bottom of the page. Submit a PR once you're ready and I can help you out if needed.

**Comment by ShrutiKatpara** [comment]
Yeah, thanks. I will do it.

**Comment by ShrutiKatpara** [comment]
> We just need it client side. But please add something maybe an image in the middle to show it's 404 or something. You can undraw or anything you like.
> 
> Also, make sure the page follows the same format as other pages and that the footer sticks to the bottom of the page. Submit a PR once you're ready and I can help you out if needed.

hey, @shahednasser.
I was little unsure on which image to keep. Can you help me pick one from below two ? Or shall I go for some other ones ?
![image](https://user-images.githubusercontent.com/45987734/111535368-080bdb80-878f-11eb-9776-2f6267d1d0aa.png)
![image](https://user-images.githubusercontent.com/45987734/111536252-05f64c80-8790-11eb-8926-fa6bc9ec4d74.png)

Sorry for bothering for such small things and thanks for cooperation :)
