### ISSUE TITLE
Cannot refresh non-home page

### ISSUE THREAD

**Issue by TomWBush** [sButtons/sbuttons#1354]
**1 - Describe the bug**
When refreshing the site on any pages other than the home page, the website gives up with a 404 status.

**2 - Expected behavior of what should have happened (if applicable)**
The website should be able to refresh in any page.

**Comment by dsnehasish74** [comment]
I want to work on this issue. This can be done easily by adding the _redirect file in the public folder

**Comment by TomWBush** [comment]
Sure you can work on it.

**Comment by shahednasser** [comment]
Thank you for catching that @TomWBush !
