### ISSUE TITLE
Header Github button link issue

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#1355]
**1 - Describe the bug** In the header when we click on the GitHub button, it does not direct to the GitHub repo. In stead it redirects  to this bellow URL this is happening due to Link tag of react-router we can add a tag there

**3 - Screenshots (if applicable)**
![Screenshot (548)](https://user-images.githubusercontent.com/58779604/111517459-1819c000-877b-11eb-87f0-7b609682944d.png)

**4 - Additional notes**

**Comment by shahednasser** [comment]
Thank you for catching that! I fixed it, it should be available after the website builds
