### ISSUE TITLE
Drop Down Menu width in small devices.

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#1359]
**Is your feature request related to a problem? Please describe.** It would look more good if we can make the width a little bigger then these line breaks will not happen in the drop-down menu

![Screenshot (549)](https://user-images.githubusercontent.com/58779604/111859203-1ca1cc80-8965-11eb-98f3-071870c3fb30.png)

**Comment by shahednasser** [comment]
Sounds like a good idea. If you want to work on it assign yourself please

**Comment by dsnehasish74** [comment]
I want to open this issue for the beginers who want to contribute

**Comment by rad10wave** [comment]
Hey @shahednasser can you assign me?, I'll love to solve this issue.

**Comment by shahednasser** [comment]
I assigned you @rad10wave
