### ISSUE TITLE
Fix Documentation sidebar links

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1361]
In the sidebar of the documentation page, the sections are not ordered correctly in terms of levels. Some sections should be high levels but are places as submenu and vice versa.

This is easy to fix just by changing the `level` attribute passed to `SidebarLink` component in the Documentation page. When the level is the parent element, no `level` attribute should be passed. Then, children should be level 1, and as it goes deeper the levels increment by one.

**Comment by snapecode** [comment]
Hi @shahednasser,

I'd like to jump on this issue if possible. 
I'm having a little trouble loading up the dev server with the new react update though. I'm getting the " cannot Get / " error page.
I've Updated all my node packages, but I haven't worked with tailwind before. I'm pretty sure its just  a routing/server configuration issue. I'll keep working on getting it up but let me know if you're having the same issue or have a fix.

Thanks

**Comment by shahednasser** [comment]
Hello @snapecode I've tried cloning the repository, running `npm install` and `npm start` in the `website` directory and it worked fine. Please let me know if there are more details to your problem.

**Comment by snapecode** [comment]
My mistake, I was installing from the root not website.
I  cloned again and attempted to run  the server but i'm getting some errors.

so on `npm install` I get 2 warnings about the lockFileVersion and fsevents  :

<img width="1252" alt="Screen Shot 2021-03-22 at 3 20 23 PM" src="https://user-images.githubusercontent.com/16259573/112046272-32a8bc00-8b22-11eb-90b0-2d7687ebcace.png">

 

and on `npm start` i get some errors that look like they're related to error handling :

<img width="1420" alt="Screen Shot 2021-03-22 at 3 10 25 PM" src="https://user-images.githubusercontent.com/16259573/112045014-c1b4d480-8b20-11eb-9e93-c9ad4e076c63.png">

Any idea what I could be doing wrong? The install catch errors are pointing to babel_runtime and core-js modules, and the start error seems to be related to catch().

**Comment by snapecode** [comment]
My mistake, I was installing from the root not the website.
I also had to update my node and some dependencies, but i've got it running.

Ill start working on this, could you assign it to me please.

**Comment by AshishRajIITI** [comment]
Hello @snapecode, I am beginning my open source contribution journey. I have good knowledge of CSS. So if u can assign this issue to me, I would be highly grateful. Also, please let me know this issue in detail. Thank You :)

**Comment by snapecode** [comment]
Hi @AshishRajIITI , I too am starting my first open source contributions and trying to get better at  push/pull/commit best practices. I'm almost done this issue, but I think there might still be an animation button still needed in another issue. I also think the site needs a few visual fixes, but @shahednasser is the lead on this project so pitch the ideas to her.

**Comment by AshishRajIITI** [comment]
@snapecode , thank you for the updates. Hope we both excel in our fields. Cheers...

**Comment by shahednasser** [comment]
Hello @AshishRajIITI if you find other unassigned issues then please comment on them. Also, if you or @snapecode find any issues on the website or in the buttons, please open a new issue with them
