### ISSUE TITLE
Make toggle button compatible with extra-small button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1366]
As the toggle button can be somewhat big for certain uses, we should make it compatible with the extra-small button. Meaning that if someone adds the `xsmall-btn` class to it, the button should become smaller while still maintaining its design and functionality correctly.

**Comment by abid1998** [comment]
@shahednasser i can take up this issue.

**Comment by shahednasser** [comment]
Hello @abid1998 . There aren't any similar issues from before, but what you need to do is in the less file that has the styling for the toggle button you need to add a case where it also has the class for `xsmall-btn` could be done by something like this:

```
&.xsmall-btn
```

and then inside it you should add styling to make the toggle button smaller. If you add the class to it now you can see that it gets smaller but it doesn't look good, so just make the adjustments that will make it look good.

Once you're done you need to add in the Documentation page under the "Toggle Button" section a subsection about making it smaller and just show the code with an example. For this one, just refer to the Documentation page and how it's done and you'll figure it out.

If you have any questions or need any other help please let me know.

**Comment by abid1998** [comment]
Not stale. Will be working on this on weekend.

**Comment by shahednasser** [comment]
Thank you for letting me know @abid1998

**Comment by iyerm2000** [comment]
Can others work on this issue as well or is it claimed?

**Comment by shahednasser** [comment]
Since @abid1998 hasn't been able to work on it, @iyerm2000 I'll assign you.

**Comment by iyerm2000** [comment]
Great! Thanks - I will be working on this with a partner. Would it be possible to assign her too? Her username is ehowden.

**Comment by shahednasser** [comment]
I can't assign someone if they don't comment on here (GitHub does not allow it) so I'll need them to comment as well.

**Comment by ehowden** [comment]
Hello! I am iyerm2000's partner!

**Comment by shahednasser** [comment]
Great @ehowden I've assigned you

**Comment by iyerm2000** [comment]
Hello - I am currently working on the issue and was wondering which less file contains the styling for the toggle button? Any direction is appreciated!

**Comment by shahednasser** [comment]
@iyerm2000 you can find it in /src/components/special/_toggle.less

**Comment by ehowden** [comment]
Hello! We picked this repo for a school project, but now that the other issues have been resolved, this project does not fit the scope of the project and we need to focus elsewhere. Therefore, we are unable to continue working on this project, we're sorry! @iyerm2000

**Comment by shahednasser** [comment]
Alright @ehowden thank you for informing me.

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. We just have to update the iframe tag to include the xsmall class to make button small, right.

**Comment by christopherfanning** [comment]
Can I take a crack at this issue? I think I have a working solution.

**Comment by shyam640** [comment]
Hey I would like to contribute in this . Is it open now also ?

**Comment by christopherfanning** [comment]
Not closed, Pull request pending.

**Comment by christopherfanning** [comment]
#1399

**Comment by christopherfanning** [comment]
@shahednasser I was still working on this issue, can you please re-open it so the pull request closes it?
