### ISSUE TITLE
Add Documentation for Animated Buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1368]
As we have finally finished adding the `animated` class to the buttons that have animations (refer to issue #1022 ), we need to add in the documentation how it should be used. 

The documentation should be added on the website and in the README. It should follow a similar structure as that of dark mode in the documentation. 

New contributors are welcome for this issue, however, please take the time to read the contributing guidelines, the documentation, and understand the project to be able to write the documentation. If you have any questions you can ask as well.

**Comment by snapecode** [comment]
HI @shahednasser , I will attempt to add the animated buttons documentation to the docs page and the readme. If I understand correctly, Ill also be adding the animated description as a level to the sidebar links on the docs page. Where do you think I should put it in the sidebar? (Before DarkMode, after basic buttons, before toggle buttons..??)

You have a bit of an explanation on how to use animated buttons in the contributor guidelines, I'll use that as a guide.

Please assign to me.

**Comment by shahednasser** [comment]
Hello @snapecode, you can add it before Dark Mode I think it'll be fitting there.

I'll assign you to this issue.
