### ISSUE TITLE
The Examples Page of the project doesn't include Footer.

### ISSUE THREAD

**Issue by AshishRajIITI** [sButtons/sbuttons#1369]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2021-03-29 232922](https://user-images.githubusercontent.com/67483270/112879670-16d78400-90e7-11eb-86ce-eb8f0653d14c.jpg)
There is no Footer present on the Examples page of the website.

**Describe the solution you'd like**
I would like to add a responsive footer to the Examples page of the website.

**Additional notes**
The footer will be the same one that is present on the landing page of the website.

**Comment by AshishRajIITI** [comment]
I would really like to contribute to this enhancement. Please assign me this. Thank you. :)

**Comment by shahednasser** [comment]
Hello @AshishRajIITI sure I will assign you

**Comment by kcbelford** [comment]
If this hasn't been resolved, I'd like to take a stab at it.

**Comment by carolinekistler** [comment]
Hi can I be assigned this ? Thanks!

**Comment by ehowden** [comment]
Hi @shahednasser my partner and I have been working on this as well. Easy fix but now we have the same problem of intersecting with the content! @iyerm2000

**Comment by shahednasser** [comment]
@carolinekistler I've assigned you

@ehowden since you guys are working on another issue and since someone else commented first I've assigned them first
