### ISSUE TITLE
Footer on Docs page of website intersects sidebar on the left

### ISSUE THREAD

**Issue by kcbelford** [sButtons/sbuttons#1373]
When you scroll down to the bottom of the Docs page on the sButtons website, the footer intersects the sidebar list on the left.
<img width="1437" alt="Screen Shot 2021-04-06 at 7 58 37 AM" src="https://user-images.githubusercontent.com/55203882/113732411-6b15d180-96ae-11eb-8e07-52179d64675e.png">

One solution could be to change the height of the sidebar which would initiate the scroll feature since the list is so long (scroll feature similar to the sidebar on the Examples page).

**Comment by shahednasser** [comment]
Thank you @kcbelford . Would you like to work on it?

**Comment by kcbelford** [comment]
@shahednasser yes I would love to work on this. Thank you!

**Comment by shahednasser** [comment]
Great @kcbelford I've assigned you

**Comment by WeryZebra-Yue** [comment]
Hello, I have a question, I am new to open source, to work on an issue do we need to get assigned or something?

**Comment by Caleb335** [comment]
> Hello, I have a question, I am new to open source, to work on an issue do we need to get assigned or something?

Hi @WeryZebra-Yue, 

Yes you need to be assigned to an issue. You can decide to create one, or pick anyone that is available.

**Comment by WeryZebra-Yue** [comment]
Thanks, @Caleb335 for information
