### ISSUE TITLE
Change the website to use the CSS in the repository

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1383]
At the moment, the website under `/website` uses the NPM package. This means that changes in submitted PRs cannot be previewed and any changes in sButtons can only be shown if deployed on NPM.

We need to make changes in the website so that instead of using the sButtons NPM package, it uses the files in this GitHub repository.

**Comment by swetharnaik** [comment]
Hi @shahednasser Am contributing to open source first time. If you are comfortable with it, can I take this up?
