### ISSUE TITLE
Fix copy button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1386]
In the Examples page, the copy button for the classes works fine, but it's copying the text as is. It should copy the text and replace all `.` with spaces

**Comment by grimxreaper** [comment]
Hi there! Would this be a fix in JS? I've been looking through the code base and see that most of the code is written in Less so I figured I would ask in case I could help out with this if you could point me to the file in which the change would be needed. Thank you @shahednasser !

**Comment by grimxreaper** [comment]
Awesome! To clarify, is the change requested to go from this copied:
`.sbtn.glow-btn.blue-btn`
to this:
`sbtn glow-btn blue-btn` ?

**Comment by shahednasser** [comment]
yes that's what we need. But also you need to be aware that this component is used in different parts of the website, not just in the examples page, so it shouldn't affect its usage elsewhere.

I'll assign you. Let me know if you need any help

**Comment by grimxreaper** [comment]
Ah okay, I will check for that.
I'm trying to test my changes but npm start opens a browser page with the message "Cannot GET/" and this message in the terminal. Have you encountered this error before?
<img width="625" alt="Screen Shot 2021-05-11 at 11 17 44 AM" src="https://user-images.githubusercontent.com/64915527/117841967-7cbd3c80-b24b-11eb-9aec-2f5c2cba1dfc.png">

**Comment by shahednasser** [comment]
You shouldn't be pushing to the upstream. Please refer to [this](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md#create-pull-request) section in the contributing guidelines
