### ISSUE TITLE
Website Description in Google Search

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1387]
If you search "sButtons" now, you'll see that the website has the description "You need to enable JavaScript to run this app." We need to replace this with good description.

You'll probably need to use something like [react-snap](https://github.com/stereobooster/react-snap)

**Comment by arunes** [comment]
I think adding longer meta description tag would fix the issue.

**Comment by shahednasser** [comment]
Hello @arunes unfortunately, that's not enough. It's not about the page having description (they already do), the pages need to be prerendered so that when Search engines like google can crawl them correctly

**Comment by arunes** [comment]
Hi @shahednasser, if the sole purpose of this issue to fix description on google. It should be fixed by changing the default meta description on the public/index html. 

Right now it is "sButtons"
`<meta name="description" content="sButtons">`

Later filled with react to this;
`<meta name="description" content="Simple buttons you can use easily for your next project.">`

As far as I see all the meta descriptions are same for all the pages. So instead of setting the meta description with react, maybe we can try to change meta on /public/index.html, because that's the first thing search engines crawl.

But of course if you need other/different meta information based on the page, this wouldn't work.

**Comment by shahednasser** [comment]
@arunes that's not entirly true, as Google would have used the description "sButtons" instead of what it currently shows, which is something regarding Javascript. This is because Google doesn't necessarily abide by "strictly use the description meta tag" it also crawls the website and sometimes uses the description they find fitting.

For this reason, we need to add pre-rendering for the website.

**Comment by arunes** [comment]
@shahednasser If google cannot find anything meaningful on meta description it looks for the page content, which is "You need to enable JavaScript to run this app."

I made it work for my personal website before, this is the search result;

This is the google search result, when you search "photogrado"
![image](https://user-images.githubusercontent.com/2902102/117992537-a25a4c80-b304-11eb-8f65-46804aadbb8e.png)

You can check the source code of the html page, google shows the meta description I have in the html.

I'm just trying to help, I think it wouldn't hurt to try.

**Comment by shahednasser** [comment]
@arunes i understand and it definitely won't harm, but what I'm saying this is not suitable as the only solution, because if Google decides to crawl the website instead of using the description, we'll still have the Javascript description

**Comment by 0xYoan** [comment]
Hello, it looks like @arunes is right. Google robot bypass all tags he doesn't find pertinent. Maybe the next most pertinent information after "sButtons" is "You need to enable JavaScript to run this app." on the page. You should try to add to current well-known description of the app into description tag to see if it works.

**Comment by shahednasser** [comment]
@0xYoan we need to change that, but I think we also need to add some pre-rendering to make sure that if Google decides to skip the description for whatever reason, there will be other content. This is also better for the SEO of the website.

**Comment by medhavisinha** [comment]
Hi, @shahednasser 
I would like to work on this issue. Is the issue still open?

**Comment by shahednasser** [comment]
Hi @medhavisinha sure i'll assign you

**Comment by medhavisinha** [comment]
@shahednasser thank you :)
I'll get to work on it and once I resolve it, I'll send a pull request.

**Comment by medhavisinha** [comment]
@shahednasser, as much as I can see from my side, there is no such issue happening as of right now. Please look into it once and let me know.

**Comment by shahednasser** [comment]
@medhavisinha that's because with Google, the description changes depending on what they think is best for the search query.

Can you at least change the description in `website/public/index.html`?

**Comment by medhavisinha** [comment]
@shahednasser ah, got it. and yes, definitely i can do that. i'll commit changes and send a pull request once i make changes.

**Comment by Divyanshj** [comment]
Is this issue still open ?
If no one is working on it then please assign it to me.

**Comment by shahednasser** [comment]
Hello @Divyanshj, @medhavisinha is working on it

**Comment by medhavisinha** [comment]
@shahednasser I have created a pull request. Please see whether it is right or not, and if it is right, then merge it and let me know. Thank you!

**Comment by shahednasser** [comment]
Unassigning @medhavisinha due to inactivity

**Comment by aaroosh-07** [comment]
can I take up this issue @shahednasser ?

**Comment by aaroosh-07** [comment]
@shahednasser I improve the content for meta description tag in index.html
