### ISSUE TITLE
Add documentation for rounded button radius

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1389]
We've now added helper classes for rounded buttons that allow changing the border radius. for example, `rounded-btn-5`. 

We need to add in the documentation page a section about this and about the helper classes with one example. This should also be added to the README.

**Comment by shahednasser** [comment]
@ThePotato10 let me know if you want to work on this

**Comment by ThePotato10** [comment]
@shahednasser I'll work on this. I'll get started as soon as I can

**Comment by ThePotato10** [comment]
Hi @shahednasser, sorry for kinda being inactive on this issue, I've had finals last week and this week too, so you can assign this issue to @RR-Sahoo or someone else

**Comment by RR-Sahoo** [comment]
@shahednasser I can work on this issue as my first contribution towards this project.

**Comment by shahednasser** [comment]
Sure @RR-Sahoo i'll assign you

**Comment by ayushi-2002** [comment]
Hey, I am new to open source. I want to work on this issue, let me know if it is possible.

**Comment by shahednasser** [comment]
As i've assigned @medhavisinha for another issue, I'll assign this one to @ayushi-2002

**Comment by ayushi-2002** [comment]
@shahednasser  can you please help me how to get started with the issue. Since, I am new to it, hence, I don't know much about it.

**Comment by shirishti** [comment]
hello!
I new to open source but I would like to contribute to it :)
Can I?

**Comment by shahednasser** [comment]
Hello @shirishti someone is already working on this. If you can find something else to work on then your contribution is appreciated!

**Comment by Divyanshj** [comment]
hey !
i am new to open source and eager to learn more that's why i want to contribute to this issue.
please let me know if I can handle any issue
