### ISSUE TITLE
Correction in punctuations and other small errors in ReadMe

### ISSUE THREAD

**Issue by ashu54-aseem** [sButtons/sbuttons#1398]
There are some punctuations and other small mistakes which can be improved. I would like to work on it.
Thanks

**Comment by shahednasser** [comment]
Hello @ashu54-aseem thank you for your interest! I will assign you to this issue, but please next time provide an example or two in the issue description.

If possible, please make these changes for the website as well under `website` directory.

**Comment by ashu54-aseem** [comment]
Yeah sure
