### ISSUE TITLE
Test sButtons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#141]
Try to use or test sButtons and give feedback on its usages or any issues you find. When you submit issues, please try to include screenshots or use cases that can help us understand it well.

**Comment by kanavpruthi** [comment]
sButtons means social buttons right? Is this a beginner's issue I can start working on?

**Comment by shahednasser** [comment]
Hello! sButtons is the name of the project, so by this issue I mean test all of the buttons.

This issue can be done by anyone and it's always open (can be done by multiple people) so go ahead!

**Comment by Pratyush-Saxena** [comment]
@shahednasser can i take up this one...

**Comment by apoorvakadam** [comment]
Hi! I was using hover buttons and I saw that buttons have a negligible change in their appearance after we hover on it. When it comes to the black button the hover effects are so diminished that it looks like a basic button.

![image](https://user-images.githubusercontent.com/32300994/94529774-c4acc780-0257-11eb-93f0-8562f62c94c8.png)

**Comment by shahednasser** [comment]
I see what you mean. Maybe we need to adjust the hover color based on the original color (make it lighter if it's dark like black, make it darker if it's light like blue). I'll look into it. Thank you.

@all-contributor please add @apoorvakadam for tests.

**Comment by shahednasser** [comment]
@all-contributors please add @apoorvakadam for tests.

**Comment by pbisen** [comment]
Hi! I was using the Hinge Buttons and felt that the hinge effect is tilting the button a bit too much, it covers the code below it in the process, maybe if we could decrease the hinge tilt it would be more aesthetically pleasing. 
![Screenshot (34)](https://user-images.githubusercontent.com/65162182/94798554-67537a80-03ff-11eb-98e2-2a698dbbfe5e.png)

**Comment by pbisen** [comment]
Hi! I was using the Hinge Buttons and felt that the hinge effect covers up the code below it making it feel less pleasing aesthetically. Otherwise the hinge effect is very well made. Could you please look into it. Thanks

![dd](https://user-images.githubusercontent.com/65162182/94798715-9c5fcd00-03ff-11eb-8585-dcd320de5cfb.png)

**Comment by shahednasser** [comment]
Hi @pbisen thank you for reporting this issue. Can you check you're running the latest version of sButtons? Because we have worked on a fix for this but if it's still there then can you please create a new issue with more information about screen width to look into it?
