### ISSUE TITLE
No link to download the CSS file.

### ISSUE THREAD

**Issue by inclinedadarsh** [sButtons/sbuttons#1418]
There's no link on the entire repository to download the file, or even if there is then it's definitely not easily accessible because I have looked for it for quite a while.

**Comment by shahednasser** [comment]
Hi @inclinedadarsh thank you for submitting this issue. I'm guessing you mean in the README, as there is a link on the website. I think you are correct, a link should be added to the README, specifically in the "Download CSS File" section.

Would you like to work on this?

**Comment by inclinedadarsh** [comment]
Sure. Actually I was going to ask. I'll definitely like to work on it. Thank You.

**Comment by shahednasser** [comment]
Great, I've assigned you.

**Comment by inclinedadarsh** [comment]
Where can I find the link to the website? I've tried searching for it but I can't find it.
I can also add the link to your website in the README file.

**Comment by shahednasser** [comment]
the website is at [sbuttons.netlify.app](sbuttons.netlify.app). You can find the download link there. Just add it under "Download CSS File" in the README.

**Comment by Rovetown** [comment]
Fixxed the issue, but cant push cause of missing access
