### ISSUE TITLE
The package.json 'start' script no longer launches a light-server

### ISSUE THREAD

**Issue by MorganGodden** [sButtons/sbuttons#1423]
Heya!
`npm start` no longer launches a light-server as stated in CONTRIBUTING.md. 
> ![image](https://user-images.githubusercontent.com/52884391/125714721-769328ac-655f-4038-b15a-2992c84e6de1.png)

This was removed from `package.json` in this commit: 656d144d0f6a8710c631106d524e01a8c1a0c8c7

**Comment by shahednasser** [comment]
Hi @MorganGodden thank you for reporting this! Would you like to work on this issue? Let me know so that I assign you

**Comment by atharva20-coder** [comment]
Hey!
@shahednasser can I give it a try I have worked on this type issues. 

May I try?

**Comment by shahednasser** [comment]
Hi @atharva20-coder sure I'll assign you

**Comment by atharva20-coder** [comment]
Hello @MorganGodden Can I know what do you get when you run the script.

**Comment by MorganGodden** [comment]
Hey @atharva20-coder. Everything in the script runs fine. 
See 656d144d0f6a8710c631106d524e01a8c1a0c8c7 for the '_lite_' script - this should be reimplemented, but I do not believe it runs the server correctly in the main directory.
