### ISSUE TITLE
Improper hatch icon button transform on events. 

### ISSUE THREAD

**Issue by MorganGodden** [sButtons/sbuttons#1424]
**Describe the bug**
- The hatch icon button no longer rotates or shifts the icon inside.

**Expected behavior of what should have happened**
- The inner contents should shift and rotate on a hover event.

  
**Current**
> ![Current](https://user-images.githubusercontent.com/52884391/125717004-f61e9d22-7fc5-4906-af33-be53468acdc8.png)

**Intended**
> ![Intended 1](https://user-images.githubusercontent.com/52884391/97064056-6693ab80-159b-11eb-86cf-9cc8c08af10b.gif)
> ![Intended 2](https://user-images.githubusercontent.com/52884391/97064057-67c4d880-159b-11eb-95b6-7a481d3ea6be.gif)

**Comment by shahednasser** [comment]
Thank you for reporting this @MorganGodden . Let me know if you want to work on it

**Comment by MorganGodden** [comment]
Sadly, I do not have time to work on #1424 or #1423. Good luck to the person/people who do.

**Comment by sourrain** [comment]
Hi, I'm new to GitHub. I would like to work on this issue ~

**Comment by abimael-o-o** [comment]
Hello, I am new to open source. Can I work on this?

**Comment by shahednasser** [comment]
Sure @abimael-o-o I'll assign you

**Comment by abimael-o-o** [comment]
@shahednasser Sorry to ask, but I can't seem to get the app to run, is there something that I might be doing wrong? I followed the instructions on the Readme:

1. Start command:
      ```
      npm start
      ```
This will run sbuttons on a lite server as well as update the CSS in `dist/sbuttons.css` as you make changes.
      
The problem I'm having is that after I do "npm start" the lite server doesn't show up and I even went to localhost:3000 but still no luck.

**Comment by shahednasser** [comment]
Hello @abimael-o-o I apologize for the misunderstanding but we have removed the lite server. Now, you'll need to run `npm run compile`, then go into the `website` directory and run `npm start` from there.

**Comment by pierrelstan** [comment]
Hello, can I work on this issue?

**Comment by ar1hant** [comment]
Can i work on this issue

**Comment by Mayank-MP05** [comment]
It looks like referencing to the parent by using & is getting referred to caller node itself
hence the styles are not really applied at the hover event fire up

**Comment by Mayank-MP05** [comment]
`_hatch.css` modification in referencing
