### ISSUE TITLE
[BUTTON IDEA]: Slack Login button

### ISSUE THREAD

**Issue by RajMhatre20** [sButtons/sbuttons#1438]
**1. Name of button**: Login with Slack

**2. Description**: Add a button for the slack community with purple `rgb(74,21,75)`  background and slack logo

**3. Button Type (Animated, Special, etc...)**: Social Button

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Sounds like a good idea @RajMhatre20 thank you for submitting it.

Let me know if you want to work on it.

**Comment by RajMhatre20** [comment]
Yes, I'm willing to work on it.

**Comment by Ishan2077** [comment]
Hi! Can I work on this issue?

**Comment by RajMhatre20** [comment]
Hello @Ishan2077, I've already added the feature which will close this issue. I'm waiting for my pull request to get merged. Keep contributing :)

**Comment by Ishan2077** [comment]
Thanks for your reply @RajMhatre20 ! I'll look out for other issues :)
