### ISSUE TITLE
[BUTTON IDEA]: Spotify Login Button

### ISSUE THREAD

**Issue by Anshu-jindal** [sButtons/sbuttons#1442]
**1. Name of button**:  Login with Spotify

**2. Description**:  A button for the Spotify community with #1DB954 as background

**3. Button Type (Animated, Special, etc...)**: Social Button

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Hello @Anshu-jindal thank you for submitting this idea. Unfortunately, I don't think this one is necessary, as I haven't really seen any website that uses "login with Spotify" (I'm not sure if this is even available in Spotify's API.)
