### ISSUE TITLE
[BUTTON IDEA]: 3D flip checkbox

### ISSUE THREAD

**Issue by Anshu-jindal** [sButtons/sbuttons#1444]
**1. Name of button**:  3D Flip Checkbox
 
**2. Description**: It will be a checkbox like you can turn it ON or OFF and the change would be visible with a nice animation effect of flip

![Screenshot (411)](https://user-images.githubusercontent.com/62394488/130490715-e6dfa228-b35d-4592-be4e-8809da64385f.png)

**3. Button Type (Animated, Special, etc...)**:  Special Button (Toggle)

**4. Will you work on it?**: Yes, I would love to work on it.

**Comment by shahednasser** [comment]
Hi @Anshu-jindal thank you for submitting another idea. I think this is a nice idea, however, make sure this is done only through CSS. If possible, add support for checkboxes and radio buttons, if not you can do it just for normal buttons.

You can refer to the toggle button for help on this. If you find it impossible to be done with just CSS, then please let me know.

**Comment by Anshu-jindal** [comment]
I will start working on this and if I face any issues I will let you know by today itself.

**Comment by shahednasser** [comment]
Hi @Anshu-jindal are you still working on this?
