### ISSUE TITLE
Add search bar in the examples and documentation pages

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1446]
In the [Examples](https://sbuttons.netlify.app/examples) and [documentation](https://sbuttons.netlify.app/documentation) pages, we should add a search bar that allows us to search through the sidebar items. The search bar should be a reusable component that would allow us to use it in any sidebar.

The search bar doesn't need to do anything fancy. Just search through the sidebar items and hide/show the items based on the search term.

**Comment by varunwho** [comment]
Hey can I try working on this?

**Comment by gursparsh** [comment]
Hi! I would like to try working on
 this issue.

**Comment by shahednasser** [comment]
I'll assign @varunwho for commenting first. Thank you both.

**Comment by varunwho** [comment]
working on it

**Comment by shahednasser** [comment]
Thank you for the update @varunwho

**Comment by varunwho** [comment]
I'm having a doubt as to how do I filter the search bar in this? Normally I know if there's any array we can use the filter method or something, so here can you give some hints or some light as to how do I implement it.
(I saw that you've used Sidebarlink text attribute for that)

**Comment by shahednasser** [comment]
That's true, thank you for pointing it out.

I think this can be done by creating a new state in `Sidebar` with initial value as the prop `children`. Then, when the search input's value changes, you traverse the `children` array, check the value of the `text` prop like this:

```js
children[i].props.text
```

check if the text contains the query entered in the input. Basically, filter out the elements in the children array that do not contain the search query, then set the state you created to the filtered array. You can use the [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) method to make it easier.

Finally, change the rendered children in the sidebar to be the state you created.

Let me know if this is clear or not and if you need any additional help.

**Comment by varunwho** [comment]
I'll try, thanks

**Comment by shahednasser** [comment]
Hello @varunwho any update on this?

**Comment by varunwho** [comment]
I'm trying but actually stuck rn, give me 1-2 days. I'll try to do it

**Comment by varunwho** [comment]
@shahednasser  I've done almost 90% of the work, just stuck on the remaining 10%. will try to do it tomorrow itself

**Comment by varunwho** [comment]
@shahednasser the search filter thing is working perfectly on the docs page but the Examples page has a different logic in rendering the sidebar I think so, I'll have to see to it

**Comment by varunwho** [comment]
The filtering is not working in the example page, rest everything else is working. I'll make a PR, can you have a look?

**Comment by CodeWithBlaze** [comment]
Hey I am absolutely new to open source but I have worked with react and want to contribute . Can you assign me this issue please.

**Comment by shahednasser** [comment]
Hello @CodeWithBlaze sorry but @varunwho is currently working on this. You can work on any other open issue, create an issue for a bug or enhancement whether on the website or in one of the buttons, or submit a new button idea you'd like to implement.

**Comment by CodeWithBlaze** [comment]
Okkk no problem thanx for the reply😀

**Comment by shahednasser** [comment]
Hello @varunwho any update on this?

**Comment by varunwho** [comment]
I'm not able to do the useEffect part

**Comment by shahednasser** [comment]
Do you need more time or should I assign someone else on it?

**Comment by varunwho** [comment]
Some more time, if it's okay with you (like a day or two)

**Comment by shahednasser** [comment]
sure let me know how it goes @varunwho

**Comment by manan-shxrma** [comment]
@shahednasser I have a piece of code that helps to sort out items in the search bar according to the user's entered text.

**Comment by shahednasser** [comment]
hello @manan-shxrma thank you for your interest. I'm still giving @varunwho a shot to finish this. If you're interested on working on other issues, submitting new issues or new button ideas then please go ahead!

**Comment by shahednasser** [comment]
Hello @manan-shxrma would you like to work on this?

**Comment by jazibobs** [comment]
I'm available to work on this if needed, I have a few days off work this week.

**Comment by shahednasser** [comment]
Hello @jazibobs I'll assign you
