### ISSUE TITLE
Login with Microsoft Button has wrong icon

### ISSUE THREAD

**Issue by RajMhatre20** [sButtons/sbuttons#1447]
**1 - Describe the bug**
Login with Microsoft Button in the social section has a Windows OS icon instead of Microsoft.<br>
**2 - Expected behavior of what should have happened (if applicable)** 
We have a Microsoft icon in font awesome which can be used here.<br>
**3 - Screenshots (if applicable)**<br>
original state: ![image](https://user-images.githubusercontent.com/68785723/130637276-2c6ed5ca-33f4-4ea1-bd8d-13778606ce14.png)
improved state:  ![image](https://user-images.githubusercontent.com/68785723/130637483-60707dc6-acdc-4bfb-8812-4bbe9a0167ab.png)

**Comment by RajMhatre20** [comment]
I'm willing to work on this issue and will create a pull request soon.

**Comment by shahednasser** [comment]
Nice catch @RajMhatre20 . Assigning the issue to you
