### ISSUE TITLE
Special Button: Toggle (on and off) button

### ISSUE THREAD

**Issue by RajMhatre20** [sButtons/sbuttons#1459]
**1 - Describe the bug**<br>
The toggle button on the website has two sections ON and OFF, both of them have incorrect representation

**2 - Expected behavior of what should have happened (if applicable)**<br>
First of all, we don't need two different sections to display on and off (i.e instead of **.sbtn.toggle-btn.toggle-on-btn** and **.sbtn. toggle-btn.toggle-off-btn** we can only have **sbtn.toggle-btn**).<br>
Secondly, Users should be able to see a preview by toggling the button live on the website. Currently, the ON button does not have that functionality and the OFF button has it but needs to click and hold the button to show active state. Normal behavior should change state by clicking on it once.

**3 - Screenshots (if applicable)**<br>
In toogle ON section button should look like this<br>
![image](https://user-images.githubusercontent.com/68785723/131210187-d05fdeb8-829b-465d-a4e4-03164af87c12.png)
<br>
Not like this<br>
![image](https://user-images.githubusercontent.com/68785723/131210199-6e8b443b-58a0-49bf-afdd-a3a4cd53683f.png)

**Comment by shahednasser** [comment]
Thank you for reporting this! I've checked it and the problem is with the class `toggle-on-btn` in particular.

Let me know if you would like to work on it..

**Comment by RajaduraiAz** [comment]
Hi @shahednasser I like to work on this
