### ISSUE TITLE
Heading on Front Page

### ISSUE THREAD

**Issue by aviral14112001** [sButtons/sbuttons#1460]
On the front page of the site  ( sbuttons.netlify.app/) the line  "Simple and Creative buttons with sButtons." is underlined. People's general mentality is that if something is underlined it must be some kind of hyperlink it will be better if we just remove the underline and make the heading more stylish. That will make it more  user friendly

**Comment by shahednasser** [comment]
Hmm I get what you are saying. Do you have any style in mind? If so, please let me know so I can assign you the issue and you can submit a PR with it.

**Comment by aviral14112001** [comment]
![Screenshot from 2021-08-31 14-18-23](https://user-images.githubusercontent.com/75156752/131472276-d68c0a43-f5e1-4e06-9a8a-089a78e51bcc.png)
I came up with this style . Its looks simple and shower,  I tried to match the color of text with the site logo if you have any preferences for color let me know

**Comment by shahednasser** [comment]
Looks nice. Please submit a PR with it.

**Comment by shahednasser** [comment]
hi @aviral14112001 any update on this?

**Comment by aviral14112001** [comment]
I will submit  PR today,  due to college  work I was very  busy  in last  few days
