### ISSUE TITLE
[BUTTON IDEA]: Dropbox Login button

### ISSUE THREAD

**Issue by harsh-gulati-14** [sButtons/sbuttons#1461]
**1. Name of button**:  Login with Dropbox

**2. Description**: Add a button for the Dropbox community with blue `rgb(20,20,252)` background and Dropbox logo.

**3. Button Type (Animated, Special, etc...)**: Social Button

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Hi, @harsh-gulati-14 . Thank you for submitting this button idea. I'll assign you.
