### ISSUE TITLE
Icon slide animation inside the button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1472]
### Discussed in https://github.com/sButtons/sbuttons/discussions/1470

<div type='discussions-op-text'>

<sup>Originally posted by **naveensunkara** September 10, 2021</sup>
This is a suggestion I thought it might be a good option. There are lot of scenarios where the buttons will have an icon. Simple animations on the icon will enhance the UX. I just tried one of the effect. Looking forward for feedback.

https://pchfx.csb.app/</div>

**Comment by shahednasser** [comment]
@naveensunkara let me know if you want to work on this

**Comment by naveensunkara** [comment]
Thanks @shahednasser  for the feedback. I am interested to work on this. I will create a PR once its done.

**Comment by shahednasser** [comment]
Great @naveensunkara I've assigned you

**Comment by naveensunkara** [comment]
Hi @shahednasser ,

I have created a PR for this issue. Kindly let me know if I have followed the right process.
https://github.com/sButtons/sbuttons/pull/1475
