### ISSUE TITLE
[BUTTON IDEA]: Login with Amazon

### ISSUE THREAD

**Issue by RajMhatre20** [sButtons/sbuttons#1486]
**1. Name of button**:  Login with Amazon

**2. Description**:  We can add login with amazon button with simple background color: #FF9900 (amazon orange) or we can also add linear-gradient from top to bottom which would look like this
![image](https://user-images.githubusercontent.com/68785723/135563823-010225a3-f81c-449a-9c62-2ca53b9b6dfe.png)
Tell me which one to go with and I would start working on it.

**3. Button Type (Animated, Special, etc...)**: Social Buttons

**4. Will you work on it?**: Yes, I'm willing to work on it

**Comment by imhossen** [comment]
Hi, You can set the default background-color: #FF9900. the idea is you can add any fancy animation stuff with linear gradient background when someone hovers your button.

**Comment by elishahyousaf** [comment]
I think adding a linear gradient from top to bottom is better idea. Black and Amazon Orange.

**Comment by RajMhatre20** [comment]
Thank you @imhossen for the suggestion I like your idea, but in the social category none of the buttons have hover functionality, so it would be a bit odd if this button has it., so I think I would be adding a basic linear-gradient background as you and @elishahyousaf suggested.
Thank you both of you

**Comment by shahednasser** [comment]
Hi @RajMhatre20 thank you for submitting it, and thank you @imhossen and @elishahyousaf for your ideas.

I think as @RajMhatre20 it's best to make sure the button aligns with other social buttons styles, so please keep that in mind when working on it.

I'm assigning you @RajMhatre20
