### ISSUE TITLE
[BUTTON IDEA]: Payment buttons

### ISSUE THREAD

**Issue by RajMhatre20** [sButtons/sbuttons#1498]
**1. Name of button**: 
- [x] #1500
- [x] #1499
- [x] #1501
- [x] #1502
- [x] #1503
- [x] #1504
- [x] #1505

**2. Description**: These are some of the buttons that can be added to the payment category.

**3. Button Type (Animated, Special, etc...)**: Payment button

**4. Will you work on it?**: No

**Comment by mrSidSat** [comment]
Can I work on this issue...

**Comment by shahednasser** [comment]
Hi @mrSidSat sure but please pick one

**Comment by mrSidSat** [comment]
I would like to proceed with apple Pay button

**Comment by RajMhatre20** [comment]
Hi @shahednasser, Should I convert each button to a separate issue?

**Comment by shahednasser** [comment]
Don't worry @RajMhatre20 I'll take care of that.

@mrSidSat please comment on the issue [here](https://github.com/sButtons/sbuttons/issues/1499) to get assigned.

**Comment by mrSidSat** [comment]
i am interested to work on mastercard button

**Comment by nikunj2001** [comment]
i am intrested to work on this

**Comment by shahednasser** [comment]
Hello @nikunj2001 please comment on the issue of one of the buttons from above and you'll be assigned to it if no one else is.

**Comment by mayankmohak** [comment]
@RajMhatre20 @shahednasser i have few more payment button ideas of PhonePe #1509 and paytm #1510
