### ISSUE TITLE
Apple Pay

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1499]

**Comment by mrSidSat** [comment]
i am interested to work on this issue

**Comment by reastyn** [comment]
I am sorry, I've started working on it before I've seen your comment.

**Comment by shahednasser** [comment]
Hi @reastyn unfortunately @mrSidSat was planning to work on this ahead of time and I was late to assign him. I'll label your PR as `hacktoberfest-accepted` but I'll have to close it. Thank you for your work!

**Comment by shahednasser** [comment]
As @mrSidSat worked on PayPal I'll assign @reastyn for this one
