### ISSUE TITLE
Amazon Pay

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1500]

**Comment by sid-khuntwal** [comment]
I am working on this @RajMhatre20

**Comment by void-hr** [comment]
Hi @shahednasser I am new to opensource and want to contribute. Kindly guide me through the process.

**Comment by shahednasser** [comment]
Hi @void-hr you need to find an unassigned issue you think you can work on. Then, comment on that issue and I'll assign you.

To understand how to contribute to this repository, you need to read the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/d7d0f89ed67b92c7baa94bb148b5c69248d80fa2/CONTRIBUTING.md)

**Comment by mayankmohak** [comment]
@shahednasser is the issue still alive

**Comment by mayankmohak** [comment]
done the required changes please review it. #1532
