### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1502]

**Comment by bhavesh1129** [comment]
Hey can you provide some more details regarding this issue?

**Comment by anoushkagera** [comment]
Hi, can I work on this issue?

**Comment by shahednasser** [comment]
Hi @bhavesh1129 you can read about this issue in [the original issue](https://github.com/sButtons/sbuttons/issues/1498). There a lot of other similar issues, so I'll assign @anoushkagera for this for now.

**Comment by TD-17** [comment]
Hey @shahednasser ! Can I work on this issue ?

**Comment by shahednasser** [comment]
Hi @TD-17 please find an unassigned issue to work on

**Comment by palespectre** [comment]
Hey @shahednasser, i'd be glad to work on this issue if you have no news from @anoushkagera  :)
