### ISSUE TITLE
Improving Home Page 

### ISSUE THREAD

**Issue by mrSidSat** [sButtons/sbuttons#1512]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Some sort of animations on the hero component ,some hover or transition effects on the links and much more

**Additional notes**
I would like to work on this.

**Comment by shahednasser** [comment]
Hi @mrSidSat , you can work on this however I don't guarantee it will be merged before I actually see if it looks good or not.

**Comment by adsingh14** [comment]
Hi there! Does this ad looks good while overlaps the content ?
![image](https://user-images.githubusercontent.com/35252877/137589063-9a86ba71-8c0a-4ff7-8196-9052233359a4.png)

**Comment by mrSidSat** [comment]
The work is at halt currently , but I would make the improvements soon
