### ISSUE TITLE
Changes to contributing guidelines

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1514]
There's a part in the contributing guidlines that is outdated as reported by @mayankmohak in #1513 .

In the following section:

https://github.com/sButtons/sbuttons/blob/d7d0f89ed67b92c7baa94bb148b5c69248d80fa2/CONTRIBUTING.md#L47-L49

We need to also add that the contributor has to run the command `npm run clean-css` along with `npm run compile`.

**Comment by mayankmohak** [comment]
Please Assign it to me under hactoberfest label.

**Comment by shahednasser** [comment]
@mayankmohak thank you for catching this but if it's ok with you can we leave for it for beginners as this is an easy task?

**Comment by demiGod31** [comment]
Hello @shahednasser , Can I take this up? I am new to open source and figuring out a way to contribute

**Comment by shahednasser** [comment]
Sure @demiGod31 I'll assign you

**Comment by mayankmohak** [comment]
@shahednasser no issues.
It will be a great issue for biginners they will get more chance to understand contributing guidlines.
