### ISSUE TITLE
[BUTTON IDEA]: Login with Sawo Labs

### ISSUE THREAD

**Issue by I-ArchanaDash** [sButtons/sbuttons#1549]
**1. Name of button**:  Login with Sawo Labs

**2. Description**: Sawo is a user authentication tool and trending nowadays. 

**3. Button Type (Animated, Special, etc...)**: Login Button

**4. Will you work on it?**: Yes , I want to add it in the button examples

**Comment by shahednasser** [comment]
Hello @I-ArchanaDash I'll assign you
