### ISSUE TITLE
[BUTTON IDEA]:

### ISSUE THREAD

**Issue by nisarga-kh** [sButtons/sbuttons#1563]
**1. Name of button**:  Anticlockwise rotating button

**2. Description**:  The buttons rotate in anticlockwise direction when hovered on them

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: Yes

**Comment by nisarga-kh** [comment]
@shahednasser  I created a .less file in src for my button and even committed it and pushed it in my forked repo.  I also added my button in buttons.json file in website/src and also pushed it . How do I add my button in sbuttons.css and sbuttons.min.css file??

**Comment by shahednasser** [comment]
@nisarga-kh you need to run `npm run build`. Please read the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/f17d57a341f3e40c3443f10f80bd9c1b7ca0c950/CONTRIBUTING.md)

**Comment by nisarga-kh** [comment]
Okay I will go through it. Thank you @shahednasser
