### ISSUE TITLE
Problem with Paper Curl Effect in Animated button

### ISSUE THREAD

**Issue by dev-arminder** [sButtons/sbuttons#1568]
I am **_new to open source_** and this gonna be my first issue I have found in paper curl animated button.

**1. If you tries to hover over paper curl button from bottom right corner. It just keep vibrating and changing state between curl and no curl state.**

**2. There should be no hover effect for non visible part of button as well as on curl part of button.**

I am happy to work on this issue.

**Comment by shahednasser** [comment]
Thank you for reporting this @dev-arminder I have assigned you

**Comment by dev-arminder** [comment]
Thanks @shahednasser. It's my pleasure to be part of this open source community.
