### ISSUE TITLE
formatting the codes

### ISSUE THREAD

**Issue by khanjanSanghavi** [sButtons/sbuttons#1574]
### Discussed in https://github.com/sButtons/sbuttons/discussions/1573

<div type='discussions-op-text'>

<sup>Originally posted by **khanjanSanghavi** November 21, 2021</sup>
In this 3 files the code was not formatted properly 
 1)  dist/sbuttons.min.css
    2) package-lock.json
         3)package.json

So I decided to do it to help this community grow

hope maintainers will accept it </div>

**Comment by shahednasser** [comment]
Thank you for opening an issue with this @khanjanSanghavi but these files don't need formatting.
