### ISSUE TITLE
[BUTTON IDEA]: Alipay payment button

### ISSUE THREAD

**Issue by antonioo-c** [sButtons/sbuttons#1577]
**1. Name of button**: 
Alipay
**2. Description**: 
Alipay is now being used in many countries, I think it would be good for us to add this up.
**3. Button Type (Animated, Special, etc...)**:
Payment
**4. Will you work on it?**:
yes

**Comment by shahednasser** [comment]
Sorry for the late reply @antonioo-c I'll assign you
