### ISSUE TITLE
[BUTTON IDEA]: Align button

### ISSUE THREAD

**Issue by angetheo-auth** [sButtons/sbuttons#1593]
**1. Name of button**:  Align

**2. Description**:  the button has a black frame and a colored box that aligns when hovered on, example attached

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: Yes

![image](https://user-images.githubusercontent.com/56256385/149978327-f3a1194f-4141-4a01-a1f9-68b660898f89.png)

**Comment by shahednasser** [comment]
That looks great @angetheo-auth you can work on it, but try to find a better name for it!
