### ISSUE TITLE
Fix text color for White Neon Border Button in Dark Mode

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1600]
In dark mode, the white [Neon Border](https://sbuttons.netlify.app/examples#neon-border) button has a dark text color. It should be white.

**Comment by anngedeus** [comment]
@shahednasser I would love to work on this

**Comment by anngedeus** [comment]
Can you please elaborate more on the issue?

**Comment by shahednasser** [comment]
Hi @anngedeus , The white neon border button in dark mode should have its text as white. You can test it out by clicking on the sun icon in the navbar. Now, when it's dark mode the text is black but it should be white.

I'll assign you. Please check the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/dd2652b48903e804a456f4c93761b3a1796fd032/CONTRIBUTING.md) for more details

**Comment by anngedeus** [comment]
@shahednasser I'm unable to test my changes following the instructions on the contributing documentation. Also I've taken a look at the src/sbuttons.less files and found the neon buttons but didn't see where text color was taken into account for any of the buttons when in dark mode

**Comment by anngedeus** [comment]
I'm a new contributor to open source projects so I'm a bit confused

**Comment by shahednasser** [comment]
@anngedeus in `src/components/animated/_neon.less` you need to add something like this:

```
&.white-btn {
    [data-theme="dark"] &,
    &.dark-mode {
      color: @white !important;
    }
  }
```

Please note that I haven't tested this yet. You need to make sure it actually works.

After adding this line, you need to compile the changes by running `rpm run build`. Then, go into the `website` directory and run `npm start` and you should be able to see the changes on the website.

**Comment by anngedeus** [comment]
Thank you so much @shahednasser for helping me with this. This is all new to me I will do what you say and test it out

**Comment by anngedeus** [comment]
Hello, I've done your changes but I keep getting this error when I run the run build?
events.js:377
      throw er; // Unhandled 'error' event

Has this error ever happened before?

**Comment by mcglauflins** [comment]
I would love to work on this if it hasn't been resolved @shahednasser

**Comment by shahednasser** [comment]
As @anngedeus has been unresponsive regarding this issue, I'll assign you @mcglauflins

**Comment by Monsieur-Nico** [comment]
@shahednasser If it hasn’t been resolved I am happy to do it

**Comment by shahednasser** [comment]
sure @Monsieur-Nico I'll assign you

**Comment by Monsieur-Nico** [comment]
Hey @shahednasser I am working on the white text for the neon buttons but something with higher hierarchy is overwriting whatever style I try to implement.

- Here I added the style required to change the text to white (while not being on hover).
<img width="893" alt="Screen Shot 2022-02-08 at 1 03 42 AM" src="https://user-images.githubusercontent.com/74289847/152928224-77a57acc-c162-48bf-941c-b9e701a8d204.png">
- And here where the style is being overwritten.
<img width="389" alt="Screen Shot 2022-02-08 at 1 04 31 AM" src="https://user-images.githubusercontent.com/74289847/152928247-70eef7e9-0730-4d57-a52a-19736f76c761.png">

Unfortunately I am not very experienced with less but I was able to trace the functionality and how the style is changing. What I couldn't trace is where the `@darkText` is coming from.
_I looked for `#333` in the project and found out it's assigned to `@darkText`_

**Comment by shahednasser** [comment]
Ok @Monsieur-Nico so I checked the code and we have a mixin for adding the white button styling in dark mode:

https://github.com/sButtons/sbuttons/blob/dd2652b48903e804a456f4c93761b3a1796fd032/src/components/_basic.less#L19-L30

So, you can replace the code you added with just:

```
&.white-btn {
   . whiteBtnDarkMode();
}
```

As for the styling with higher priority, it's actually because of this in `src/components/_basic.less`:

https://github.com/sButtons/sbuttons/blob/dd2652b48903e804a456f4c93761b3a1796fd032/src/components/_basic.less#L148-L150

So, if you keep having issues with it you can add an exception for the neon border button along with the fill button here.

Let me know if anything is unclear!

**Comment by Monsieur-Nico** [comment]
Hey @shahednasser,
I just finished working on the issue.
The `_basic.less`:
https://github.com/sButtons/sbuttons/blob/dd2652b48903e804a456f4c93761b3a1796fd032/src/components/_basic.less#L148-L151
Became:
```less
&:not(.fill-color-btn):not(.neon-border-btn) {
    color: @darkText !important;
  }
}
```
And as for the button itself `/src/components/styles/_neon-border.less`:
https://github.com/sButtons/sbuttons/blob/dd2652b48903e804a456f4c93761b3a1796fd032/src/components/styles/_neon-border.less#L68-L76
Became:
```less
&.white-btn {
    .neon(@neonWhite);
    &:hover {
      color: @darkText !important;
    }
    [data-theme="dark"] &,
    &.dark-mode {
      .neon(@neonWhite);
    }
  }
```

I already merged `master` into my branch to make sure I am up to date and I will be making a PR

**Comment by Stergios13** [comment]
Hello everyone. I am happy to help if the issue hasn't resolved.
