### ISSUE TITLE
layered button not showing on website

### ISSUE THREAD

**Issue by angetheo-auth** [sButtons/sbuttons#1601]
**1 - the layered button doesnt show up on the website, or in the preview on the pull request**

**2 - this morning the button was working correctly, no changes have been made to my knowledge**

this is from my local code:
![image](https://user-images.githubusercontent.com/56256385/151038966-99a6fd3f-701e-4e0f-b74e-b09946ab6815.png)

and this is from the website:
![image](https://user-images.githubusercontent.com/56256385/151039023-c20d86c7-3304-4d6c-bba5-602485ed49f4.png)

sorry if this is something temporary, just thought i should mention it

**Comment by shahednasser** [comment]
Hi @angetheo-auth there was actually an issue in the website deploy that caused this. It's now fixed. Thank you for letting me know!
