### ISSUE TITLE
Text Align in Spotlight/Block buttons

### ISSUE THREAD

**Issue by Monsieur-Nico** [sButtons/sbuttons#1606]
Text isn't horizontally aligned in the block section of the [Spotlight buttons](https://sbuttons.netlify.app/examples#Spotlight) after the animation.

<img width="857" alt="Screen Shot 2022-02-09 at 2 45 01 PM" src="https://user-images.githubusercontent.com/74289847/153278370-5b7dab0b-b365-4dae-96a5-eb004a2c7cd8.png">

_The text is aligned correctly in one of the button boxes before the animation starts but should be given a padding after animation._

**Comment by shahednasser** [comment]
Thank you for catching that. I think it's not aligned correctly in the first place for spotlight block buttons.

I'll assign you.

**Comment by ej-sanmartin** [comment]
I'll also test this out on my machine, horizontal centering is always tricky lol see what I can do after work

This seems to be the relevant file, for anyone who wants to try to fix this sooner:

```https://github.com/sButtons/sbuttons```

**Comment by shahednasser** [comment]
Hello @ej-sanmartin do you want to work on this?
