### ISSUE TITLE
Spotlight button's text color in dark mode

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#1609]
In dark mode, [Spotlight's](https://sbuttons.netlify.app/examples#Spotlight) text color should be white before the animation as well.

**Comment by JLambertazzo** [comment]
Hi! I'd like to work on this issue, can you please assign me?

**Comment by Grandstaff79** [comment]
Hello, I would like to work on this issue as well, would you assign me ?

**Comment by ej-sanmartin** [comment]
Since @crisboxing11 has successfully merged a change regarding this bug, issue should be closed! Did anyone check if this change, however, doesn't affect light mode?

**Comment by ej-sanmartin** [comment]
Read the commits / merge history wrong, guess now would be a good time to test it out again

**Comment by shahednasser** [comment]
This issue is still not resolved in case anyone is interested in working on it.

**Comment by JLambertazzo** [comment]
I'll take it, can you assign me?

**Comment by shahednasser** [comment]
Sure @JLambertazzo

**Comment by JLambertazzo** [comment]
I can't get the changes to display on the example site.
Setting the button class to dark-mode or it's parent to have data-theme="dark" manually makes it work as expected but by default in dark mode it does not change.

**Comment by shahednasser** [comment]
@JLambertazzo can you submit a PR so that I can see exactly what's going on?

**Comment by JLambertazzo** [comment]
Created the pull request, let me know what you think

**Comment by Poirei** [comment]
Can I join to work on this issue?

**Comment by shahednasser** [comment]
@Poirei are you still interested in working on this?

**Comment by lam-brian** [comment]
Hi, can I work on this issue? Also, quick question: Would you want white text on all the spotlight buttons except for the white ones? Otherwise when you hover it, the text would blend in with the background color.

**Comment by shahednasser** [comment]
@lam-brian the text in dark mode should be white before the animation. As for after the animation you should just fix the white button to be another color

**Comment by Dustpie** [comment]
Can I work on this issue please?

**Comment by shahednasser** [comment]
Hello @Dustpie are you still interested in working on this?

**Comment by Ruc08** [comment]
Hello @shahednasser, If no one is working on this issue then can I work on it?

**Comment by shahednasser** [comment]
Hello @Ruc08 sure I'll assign you

**Comment by Ruc08** [comment]
Thank you, @shahednasser! I'm starting to work on it now :)

**Comment by Ruc08** [comment]
Hey @shahednasser, 

I'm getting some kind of prompt when I run npm start in terminal which I hadn't faced before and I'm not able see anything on localhost. It would be great if you can help me.

<img width="585" alt="Screenshot 2022-07-01 at 6 48 11 PM" src="https://user-images.githubusercontent.com/89313809/176902748-82de0a63-a67c-439b-938a-6536a07fcd5d.png">

**Comment by shahednasser** [comment]
@Ruc08 basically this command watch any changes you make to the `.less` files and compiles them. If you want to run the website, it's under the `website` directory.

Please check the contributing guidelines for more details

**Comment by Ruc08** [comment]
Hey @shahednasser, Good Afternoon!

Have you seen the PR or not?

**Comment by Ruc08** [comment]
Hello @shahednasser, If you get some time than please look at the PR request which I made last week.

**Comment by DeviSriCharan2020412** [comment]
@shahednasser Is the issue still open? I'm interested in working on this issue.

**Comment by shahednasser** [comment]
@Ruc08 are you still working on this?

**Comment by Ruc08** [comment]
@shahednasser Yep! As I don't know LESS so need some time to learn it and to do require changes. I hope that you won't mind to give me some time to learn about LESS, Right?

**Comment by Youngtechie** [comment]
Hi @shahednasser just going through this issue now, which i noticed some changes i can make to resolve it. Can I be assign?

**Comment by rupnarayanb** [comment]
Hi @shahednasser Is it still open ?  I have solved it, can you please assign the issue to me ?
