### ISSUE TITLE
Hacktoberfest Ideas

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#161]
As everyone knows, Hacktoberfest will start soon. This issue will be open to discussing any ideas to help contributors contribute and participate in Hacktoberfest!

**Comment by keivalya** [comment]
I'd love to participate!😁

**Comment by yashvarshney003** [comment]
I also love to contribute.

**Comment by shahednasser** [comment]
Great! @keivalya @yashvarshney003 . Hacktoberfest hasn't started yet, but I would love to hear ideas from you here if you have any!

**Comment by geographyclub** [comment]
Any interest in adding a color-gradient button? This will be my first contribution but I do know a little bit of CSS and may be able to pull this off by myself.

**Comment by hbach24** [comment]
Hi! I would like to contribute as well! I would suggest some pixelated buttons used for video games (I think it would be really cute and cool to have).

**Comment by shahednasser** [comment]
> Any interest in adding a color-gradient button? This will be my first contribution but I do know a little bit of CSS and may be able to pull this off by myself.

That's a great idea actually. If you would like to contribute and make the button then go ahead, and it not you can add it in the button ideas file and someone else might do it.

If you want to do this as a part of your hacktoberfest contribution though you should wait until October.

**Comment by shahednasser** [comment]
> Hi! I would like to contribute as well! I would suggest some pixelated buttons used in video games (I think it would be really cute and cool to have). 

That's a nice idea. If you would like to do it yourself then go ahead and if not then please add it to the button ideas file.

If you would like to make this contribution as a part of your hacktoberfest participation then you should wait until October. (Note that if you make your button yourself or just add the idea in the button ideas file, both are considered a contribution)

**Comment by APalpattuwar7** [comment]
Hi! What do you think of adding 'Login With GitHub' social button? I will try to add this if you approve. This will be my first contribution.

**Comment by Pratyush-Saxena** [comment]
@shahednasser i would like to colaborate too

**Comment by shahednasser** [comment]
I like the enthusiasm @Pratyush-Saxena but currently we only have 39 contributors, I think it's still a bit early for that.  
Please collaborate in any issue that you find helpful!

**Comment by isonnymichael** [comment]
Keep simple like the name SImple Buttons 😄, how to make more option for padding maybe or make the button block like bootstrap btn-block, or small

**Comment by shahednasser** [comment]
I like the block button idea. Maybe you can add it to button ideas file @isonnymichael

**Comment by isonnymichael** [comment]
@shahednasser okay noted

**Comment by dsnehasish74** [comment]
I think we can add buttons  for chat box . and In this project there is no large button section . We can add this two in the project

**Comment by shahednasser** [comment]
@dsnehasish74 someone added the large button type in button ideas (as block buttons). As for the chat box buttons, please add the idea to button ideas!

**Comment by dsnehasish74** [comment]
ok I am adding it .............. can I add that button .................... I mean I want to work on it .................. If you give me that chance then I will add it in 2 or 3 days

**Comment by vaidikg20000** [comment]
I'd love to contribute by making a transitioning effect button

**Comment by shahednasser** [comment]
sure @vaidikg20000 go ahead!

**Comment by vaidikg20000** [comment]
I'm creating bounce effect button in css, is it different compared to less if i want to contribute?

**Comment by shahednasser** [comment]
@vaidikg20000 no it's not very different and once you try Less it's easier. I think you should try and if you need any assistance let me know

**Comment by palakyadav1807** [comment]
I'd like to participate😍!

**Comment by shahednasser** [comment]
sure @palakyadav1807 go ahead! You can look through the issues to find the best ways to participate!

**Comment by Adarshsingh2k** [comment]
Hey I wanted to contribute can you please help me !

**Comment by shahednasser** [comment]
Hi @Adarshsingh2k what do you need help with? If you're looking for issues to contribute to check out the issues with "Always Open" label or unassigned issues.

**Comment by geographyclub** [comment]
I'm no longer able to work on the gradient-color button. Anyone else want to work it?

**Comment by shahednasser** [comment]
> I'm no longer able to work on the gradient-color button. Anyone else want to work it?

I'll unassign it. Thank you for letting me know.

**Comment by amanraj862** [comment]
hey can i work on it I'm a beginner i know little about css can i contribute?
i can make a  gradient button

**Comment by shahednasser** [comment]
@amanraj862 please comment on that issue so that I can assign you.

**Comment by amanraj862** [comment]
i have doubt i don't know about less i'm a beginner i know css only so can i just upload a css file?

**Comment by amanraj862** [comment]
> i have doubt i don't know about less i'm a beginner i know css only so can i just upload a css file?

@shahednasser

**Comment by shahednasser** [comment]
@amanraj862, unfortunately, it needs to be Less so you might need to learn it a bit and it's not hard.

**Comment by adarshtodi** [comment]
Is the gradient animated glowing button done by anyone yet? if not then I recently learnt it, I would love to contribute. : )

**Comment by shahednasser** [comment]
Hi @adarshtodi someone is already working on this, unfortunately. Try looking for unassigned issues or create a "new button idea" issue if you have any that you would like to work on!

**Comment by adarshtodi** [comment]
I also thinking there is one button  which is like liquid / glue effect,  it will look good!! can I work on that?
![image](https://user-images.githubusercontent.com/58510987/95297205-de738d80-089b-11eb-9f0c-2cd4562a75f1.png)

**Comment by shahednasser** [comment]
@adarshtodi is it an animated button or would it just look like that? If it's an animated button please create a "new button idea" issue with it and I suggest to make it have text in general, not a social icon.

**Comment by adarshtodi** [comment]
okay, i will keep that in mind

**Comment by adityarajendrashanbhag** [comment]
@shahednasser Hi sir, I would love to contribute to this project, I have an idea of creating a hover glow button which gives an RGB look after clicking on it, but I'm a little confused about how to contribute to this project.

**Comment by shahednasser** [comment]
Hello @adityarajendrashanbhag first I suggest you read the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md) before making any contribution. If you have any button idea that you would like to implement or see implemented please create a "new button idea" issue before working on it. If you need any other assistance let me know.
