### ISSUE TITLE
license | MIT button in README.md Page

### ISSUE THREAD

**Issue by Rahul-go1503** [sButtons/sbuttons#1610]
Problem : 
In README.md file when we click on license | MIT button it redirect to a 404 ERROR page.

Possible Solution :  
It can be fix my updating URL path in readme file. 

Request : 
Dear Sir/ma'am I'm new to open source contribution and if you give me chance this is going to be my first contribution. I would like to fix it 

![image](https://user-images.githubusercontent.com/83687972/153740285-da49cc87-1bc9-4a84-befa-c04222ff517b.png)

**Comment by shahednasser** [comment]
Hi @Rahul-go1503 thanks for noticing this. I've assigned you

**Comment by Rahul-go1503** [comment]
Thanks... I resolved the issue and create a PR also
