### ISSUE TITLE
Dead "Button Styles" link in Example page sidebar nav menu

### ISSUE THREAD

**Issue by DarrickFauvel** [sButtons/sbuttons#1618]
**1 - Describe the bug**

The `Button Styles` link in "Example" page sidebar nav menu is non-functioning.

**2 - Expected behavior of what should have happened (if applicable)**

When the sidebar nav menu link, `Button Styles`, is clicked, it should update the right side of the page with a "Button Styles" gallery of buttons.

**3 - Screenshots (if applicable)**

**4 - Additional notes**

My assumption though is the `Button Styles` menu item is just presentational of the types of button styles that follow below it. In this case, the `Button Styles` menu item should not appear as an active menu link, as it is a confusing behavior and to the user it would appear to be a broken link.

**Comment by shahednasser** [comment]
Hello @DarrickFauvel thank you for reporting this but this is not a bug since this link doesn't refer to a page, just a title for sub categories.
