### ISSUE TITLE
shadow button

### ISSUE THREAD

**Issue by badhri17** [sButtons/sbuttons#1627]
**1. Name of button**:  Shadow button

**2. Description**: 
I am thinking of adding a shadowed button class name ( shadow-btn) which will take the button color (for example : blue-btn )
and shadow it (fixed shadow ) and another option shadow-on-hover  which will display the shadow only when the button is hoverd .

## shadow-btn
![image](https://user-images.githubusercontent.com/60823745/162592625-bec7ed2a-3e8f-4c0d-af05-2b7fb387b381.png)

## shdaow-on-hover
![sbutton](https://user-images.githubusercontent.com/60823745/162592689-b281dee8-9b0f-42af-8fe4-960cf92cf8bf.gif)

**3. Button Type (Animated, Special, etc...)**:  Button Styles

**4. Will you work on it?**:
yes I am ready if you give me the permission.

**Comment by shahednasser** [comment]
Looks cool! I assigned you

**Comment by badhri17** [comment]
Still working on it I will finish it these two days
