### ISSUE TITLE
new like buttons to be add

### ISSUE THREAD

**Issue by Pratyush-Saxena** [sButtons/sbuttons#225]
I guess we need some new buttons with fill animation effect .somewhat .like-->
![2834b3bbf14da02901ff68fb76395da8](https://user-images.githubusercontent.com/52444607/94332165-4a2e3e80-fff0-11ea-8b02-3addb1aa438b.gif)

**Comment by shahednasser** [comment]
I like it. If you wanna work on it, please let me know to assign you!

**Comment by shahednasser** [comment]
And if not, please add it in the buttons ideas file for someone else to see it. Let me know!

**Comment by Pratyush-Saxena** [comment]
> I like it. If you wanna work on it, please let me know to assign you!

surely i would like to take this up

**Comment by shahednasser** [comment]
Great! I assigned you @Pratyush-Saxena

**Comment by shahednasser** [comment]
Hi @Pratyush-Saxena are you still working on it? Please either submit a PR by tomorrow or I'll have to unassign you to give other contributors a chance. Thank you.

**Comment by Pratyush-Saxena** [comment]
> Hi @Pratyush-Saxena are you still working on it? Please either submit a PR by tomorrow or I'll have to unassign you to give other contributors a chance. Thank you.

I guess it should be assigned to someone else . because I m not able to work right now ... @shahednasser you must unassign me .

**Comment by shahednasser** [comment]
No problem @Pratyush-Saxena  thank you for letting me know.

**Comment by harsh863** [comment]
@shahednasser i would like to give this a try.

**Comment by shahednasser** [comment]
Sure @harsh863  I'll assign you

**Comment by shahednasser** [comment]
Any update on this @harsh863 ?

**Comment by dsnehasish74** [comment]
If no one is working on this can I work on this issue @shahednasser ???

**Comment by shahednasser** [comment]
Yes @dsnehasish74 as this issue has taken too long.

**Comment by dsnehasish74** [comment]
@shahednasser sorry I am not able to solve this problem for now , because I am little busy now .You can assign this to other . Sorry.

**Comment by shahednasser** [comment]
It's ok @dsnehasish74 I understand! Thank you for letting me know.

**Comment by BeniB98** [comment]
Hey, i would love to work on it, if nobody else do it. :)

**Comment by shahednasser** [comment]
Sure @BeniB98 I'll assign you.
