### ISSUE TITLE
Add dark mode toggle button

### ISSUE THREAD

**Issue by hvirmani** [sButtons/sbuttons#229]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional notes**

**Comment by shahednasser** [comment]
Hello @hvirmani will you be adding this button idea or should I unassign you?

**Comment by hvirmani** [comment]
I am working on it and will be pushing soon.

**Comment by shahednasser** [comment]
Ok great @hvirmani take your time, just needed a confirmation.

**Comment by shahednasser** [comment]
Closing this PR due to inactivity and since the button idea is not very important.
