### ISSUE TITLE
Split Basic/Rounded/Block into tabs

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#298]
Split Basic/Rounded/Block buttons into tabs for each button style instead of under each other where the user can change between them as suggested by @zahra-abdullah .

**Comment by shahednasser** [comment]
@zahra-abdullah will be working on this.

**Comment by shagun25** [comment]
can i contribute?

**Comment by shahednasser** [comment]
Hi @shagun25 someone is already working on this issue. Please look at other issues if you wanna help and contribute!

**Comment by shahednasser** [comment]
@zahra-abdullah please confirm if you'll be working on this issue

**Comment by zahra-abdullah** [comment]
> @zahra-abdullah please confirm if you'll be working on this issue

Hi @shahednasser ! yes I already started working on it

**Comment by shahednasser** [comment]
Great @zahra-abdullah . I have refactored the code in buttons-examples.js to make the website mor consistent. If you have any questions about it let me know.

**Comment by shahednasser** [comment]
Hi @zahra-abdullah unfortunately I need to unassign you from this as this issue has become a high priority issue and there has been a lot of changes since this issue. I will be closing this PR as well. Thank you.
