### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by Charu271** [sButtons/sbuttons#340]
**Hover effect using gradient.**

**In this the gradient of button will change when hovered over it**

**I would like to work on it**

**Comment by shahednasser** [comment]
Sounds like a nice idea. You can go ahead and work on it.

**Comment by Charu271** [comment]
Okay

**Comment by Charu271** [comment]
What does it mean? I didn't get it. Please let me know.

**Comment by shahednasser** [comment]
@Charu271 don't worry about it. It just reports issues that have been inactive for 7 days so that I can check if someone is actually working on the issue or not.

**Comment by Charu271** [comment]
Okay

**Comment by ilhambara** [comment]
Hi, can I add my gradient button style for this issue?

**Comment by shahednasser** [comment]
@ilhambara this issue has been resolved. Thank you.
