### ISSUE TITLE
Move variables in src/sbuttons.less to new file src/_variables.less

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#395]
Just move the variables in `src/sbuttons.less` to new file `src/_variables.less` then import `src/_variables.less` in the beginning of sbuttons.less before any file

You should also change the link in the README for sbuttons.less under [Modifying Button Colors](https://github.com/shahednasser/sbuttons#modifying-button-colors) to the new variables.less file and change the text as well to "_variables.less"

**Comment by annettomcy** [comment]
Would like to work on this

**Comment by shahednasser** [comment]
Ok @annettomcy I will assign you

**Comment by pinkman7009** [comment]
is anyone working on this?

**Comment by annettomcy** [comment]
Yes me

**Comment by pinkman7009** [comment]
okay

**Comment by faraz16iqbal** [comment]
Is this issue still open?

**Comment by shahednasser** [comment]
@faraz16iqbal this issue is assigned. Please look for unassigned issues.

**Comment by abhishekrawe** [comment]
I want to work on it? is this still open?

**Comment by shahednasser** [comment]
@abhishekrawe someone is working on this.

**Comment by shahednasser** [comment]
Unassigning @annettomcy as they are taking too long and this is a high priority issue.

**Comment by tmott13** [comment]
I would like to be assigned to this, if that's possible? @shahednasser

**Comment by kuldeep123kd** [comment]
Can i work on this?

**Comment by shahednasser** [comment]
@tmott13 I need someone to not take long with it can you do that?

**Comment by shubh710** [comment]
Hi @shahednasser 
I can do it quickly.
Is the problem Statement same as
https://github.com/sButtons/sbuttons/issues/395#issue-712643930 ?

**Comment by kuldeep123kd** [comment]
Yes @shahednasser  i can do it quickly.

**Comment by shahednasser** [comment]
Assigned @kuldeep123kd
