### ISSUE TITLE
Transparent on Hover Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#415]
**1. Name of button**: Transparent on Hover Button

**2. Description**: A button whose background becomes transparent on hover

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**:

**Comment by iamvaishnav** [comment]
I would like to work on it

**Comment by Neeraj3508** [comment]
@shahednasser  i already opened this issue #412

**Comment by Neeraj3508** [comment]
Can i do it

**Comment by shahednasser** [comment]
Assigned @Neeraj3508

**Comment by adsingh14** [comment]
Is it still open or I start working on it ?

**Comment by Neeraj3508** [comment]
Thanks @shahednasser

**Comment by Neeraj3508** [comment]
@shahednasser This issue is completed i think we should close it now.
