### ISSUE TITLE
Colored Background on Hover Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#416]
**1. Name of button**: Colored Background on Hover Button

**2. Description**: A button that is originally transparent but its background becomes colored on hover

**3. Button Type (Animated, Special, etc...)**: Button Styles

**4. Will you work on it?**:

**Comment by sindhwanicheshtha06** [comment]
I can work on this

**Comment by yaspalsingh115** [comment]
Yes, I can do.

**Comment by LuciKritZ** [comment]
I can work on it too.

**Comment by shahednasser** [comment]
assigning @sindhwanicheshtha06  for replying first

**Comment by crew-guy** [comment]
Hey ! Does anyone need any help with this ?

**Comment by shahednasser** [comment]
Unassigning this due to inactivity so that someone else can work on it.

**Comment by shahednasser** [comment]
@crew-guy if you finish the stack buttons and no one is assigned I'll let you know.

**Comment by developerzone** [comment]
I can work on this.

**Comment by shahednasser** [comment]
Sure @developerzone go ahead

**Comment by developerzone** [comment]
I am getting error while creating a PR. Please check this at https://github.com/sButtons/sbuttons/pull/776 and kindly guide me on this if I am doing anything wrong.

**Comment by maityankan10** [comment]
can I work on this

**Comment by HERITAGEALABI** [comment]
> **1. Name of button**: Colored Background on Hover Button
> 
> **2. Description**: A button that is originally transparent but its background becomes colored on hover
> 
> **3. Button Type (Animated, Special, etc...)**: Button Styles
> 
> **4. Will you work on it?**:

yes i can work on it

**Comment by shahednasser** [comment]
Hi @HERITAGEALABI please do. I'll assign you.

**Comment by HERITAGEALABI** [comment]
@shahednasser i apologize i will work on a button type

**Comment by venkataraman123** [comment]
I can work on it

**Comment by mrSidSat** [comment]
Can I work on this issue

**Comment by shahednasser** [comment]
@mrSidSat you may work on this. I'm changing the priority of this button to High as it has taken too long and I think it's an important button

**Comment by venkataraman123** [comment]
Can I work on this

**Comment by rifafatima** [comment]
Yes, I can

**Comment by shahednasser** [comment]
@rifafatima since this is a high priority issue you can work on it as well. We need to resolve this one soon.

**Comment by rifafatima** [comment]
> @rifafatima since this is a high priority issue you can work on it as well. We need to resolve this one soon.

Okay.

**Comment by rifafatima** [comment]
@shahednasser Okay.
