### ISSUE TITLE
Colored Liquid Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#417]
**1. Name of button**: Colored Liquid Button

**2. Description**: A button that filled the space like liquid

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: no

**submitted by**: @abdullah2205

**Comment by Neeraj3508** [comment]
i would like to work

**Comment by shahednasser** [comment]
Assigned you the button

**Comment by Neeraj3508** [comment]
Thanks @shahednasser

**Comment by Neeraj3508** [comment]
Working on this

**Comment by Neeraj3508** [comment]
https://i.ibb.co/gg7V3CP/Screenshot-2020-10-03-at-8-51-48-PM.png
Please check this screenshot if buttons are OK?
Also i am adding hover properties but i don't know why they aren't working. So, this can take some time as i am figuring out that thing.

**Comment by Neeraj3508** [comment]
Facing issue when using hover pseudo selector then it is not working on hover but when i go to chrome developer tool and forcefully enable hover then the results are as desired. So, i think no problem with code.
Here is screenshot attached of that behaviour.
This behaviour is similar to #128 
Please help if you can.
Normal State GIF - https://i.ibb.co/W3GG6cg/ezgif-com-gif-maker.gif
Forced state GIF - https://i.ibb.co/2cgp7kt/ezgif-com-gif-maker-1.gif

**Comment by shahednasser** [comment]
Can you please submit a PR with this as it is easier to figure it out that way?

**Comment by Neeraj3508** [comment]
Done @shahednasser
