### ISSUE TITLE
Animated Gradient Border Button	

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#418]
**1. Name of button**: Animated Gradient Border Button

**2. Description**: A button that has gradient text border background with animation

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: no

**submitted by**: @mukesh2309

**Comment by mukesh2309** [comment]
yes

**Comment by shahednasser** [comment]
will you work on it @mukesh2309 ?

**Comment by LuciKritZ** [comment]
Can I work on it?

**Comment by sanyud24** [comment]
can i  work over it ?

**Comment by shahednasser** [comment]
@LuciKritZ @sanyud24 I'm still waiting on confirmation from @mukesh2309

**Comment by mukesh2309** [comment]
Yes you can 😊

**Comment by mukesh2309** [comment]
@shahednasser 

Yes they can work .👍

**Comment by shahednasser** [comment]
Ok since @LuciKritZ asked first they will be assigned to this issue.

**Comment by shahednasser** [comment]
Unassigning this due to inactivity. Someone else can get assigned now.

**Comment by sanyud24** [comment]
Can I work over it now

**Comment by mukesh2309** [comment]
> Can I work over it now

Yes you can

**Comment by shahednasser** [comment]
Assigned @sanyud24

**Comment by SrijitaSarkar99** [comment]
May I work on this too?

**Comment by shahednasser** [comment]
@SrijitaSarkar99 someone is assigned to this issue.

**Comment by shahednasser** [comment]
Hello @sanyud24 any update on this?

**Comment by parresh77** [comment]
I see it has been more than a week since any action from the assignee, @shahednasser I can work on this.

**Comment by shahednasser** [comment]
@parresh77 I'll assign you

**Comment by parresh77** [comment]
@shahednasser I will not be able to work on this due to other engagements. Hence I am unassigning this. Apologies for any inconvenience.

**Comment by shahednasser** [comment]
It's ok @parresh77 I'll be closing this issue anyway

**Comment by parresh77** [comment]
@shahednasser I know the issue is closed and I unassigned it myself but can you please review it as I think it is one of the best designs we've got here.
