### ISSUE TITLE
Cracking Neon Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#419]
**1. Name of button**: Cracking Neon Button

**2. Description**: A Neon Button that will cracked when clicked

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: no

**submitted by**: @EmpalGentong

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by shahednasser** [comment]
ok I will assign you @rahullli

**Comment by rahullli** [comment]
Can you please tell me what will be the crack in the button , it is not clear to me .
After cracking whether I have to show the cracked one or it is going to be vanished ?

**Comment by shahednasser** [comment]
I'm actually not sure either as the idea is not clear to me (it was not submitted by me). I guess try to do it the way you visualize it.

**Comment by abhishekrawe** [comment]
i would like to work on it.

**Comment by shahednasser** [comment]
@abhishekrawe someone is working on it. Please look for unassigned issues
