### ISSUE TITLE
Trace Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#420]
**1. Name of button**: Trace Button

**2. Description**: An outline button whose border gets traced, starting and ending at the same point

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: no

**submitted by**: @preity-p

**Comment by Kazeno21** [comment]
can i work on this?

**Comment by shahednasser** [comment]
Sure @Kazeno21 I'll assign you

**Comment by Kazeno21** [comment]
i have made the pr. can you please check and merge it?

**Comment by shahednasser** [comment]
Hi @Kazeno21 , are you still working on this? If not let me know to give other contributors a chance at it.

**Comment by Kazeno21** [comment]
yup. still working on this. will take some time though.

**Comment by PriyanshTri** [comment]
can you assign this to me?

**Comment by shahednasser** [comment]
No worries @Kazeno21 let me know if you need help.

**Comment by shahednasser** [comment]
Hi @Kazeno21 thank you for working on this but unfortunately, this is taking too long. I'll be unassigning you to give other contributors a chance on it.

**Comment by devakisj1** [comment]
Can you assign me this issue

**Comment by shahednasser** [comment]
Yes @devakisj1 I'll assign you

**Comment by shahednasser** [comment]
@devakisj1 do you have any update on this?

**Comment by devakisj1** [comment]
Yes, I have worked out the solution will make pull request soon

**Comment by devakisj1** [comment]
@shahednasser I am having trouble understanding extending the animation to different colors of button in the less file. Can I make a pr for just a single color button solution.

**Comment by shahednasser** [comment]
@devakisj1 submit a pr and maybe I can guide you through it.
