### ISSUE TITLE
Expanding Border Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#421]
**1. Name of button**: Expanding Border Button

**2. Description**: On hovering over the button, the border will get pushed inside out, besides the opacity changing

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: no

**submitted by**: @preity-p

**Comment by Bhargav252000** [comment]
hey @shahednasser can I start working on this issue ?

**Comment by shahednasser** [comment]
hi @Bhargav252000 yes you can

**Comment by Bhargav252000** [comment]
I have never made a button in less format, can you please give me idea how to do it in less ?
I can do in CSS.

**Comment by shahednasser** [comment]
Less is very easy. I suggest you go to the [Less](http://lesscss.org/) website to understand how you can do it and you can refer to other buttons as well for help. It's very similar to CSS just with a few improvements.

Let me know if you can do that or not to assign you.

**Comment by Bhargav252000** [comment]
Okay, cool I'll look in less website and will let you know.

**Comment by Bhargav252000** [comment]
#462 
added a pull request can you check it.

**Comment by Bhargav252000** [comment]
#462 
Added PR on **expand button inside out** can you please check that out.

**Comment by isonnymichael** [comment]
Can i try to work on this ?

**Comment by shahednasser** [comment]
Yes @isonnymichael
