### ISSUE TITLE
[BUTTON IDEA]: App Buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#424]
**1. Name of button**: App Buttons

**2. Description**: 2 Buttons "Get it on Play Store" & "Download on the app store"

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**Comment by Kazeno21** [comment]
can i work on this please?

**Comment by shahednasser** [comment]
Hi @Kazeno21 this is also in progress. Please find issues that are unassiged and don't have the "in-progress" label

**Comment by Kazeno21** [comment]
cool thanks. this is actually my first time. sorry for the inconvenience

**Comment by shahednasser** [comment]
It's fine @Kazeno21 no worries! I hope you can find an issue to contribute to.

**Comment by shahednasser** [comment]
@dsnehasish74 can you confirm you're working on this?
