### ISSUE TITLE
[BUTTON IDEA]: Thumbs Up Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#425]
**1. Name of button**: 

**2. Description**: Button with Thumbs up icon only

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**Comment by wisetok12680** [comment]
hey there I would like  to work on it

**Comment by shahednasser** [comment]
Sure @wisetok12680 I'll assign you

**Comment by wisetok12680** [comment]
Thanks I'll get right on it

**Comment by wisetok12680** [comment]
Hey would you mind helping me with the following questions as this is my first time contributing to open-source. I have read through the contributing guidelines but still had these in mind.
1.Do I need to edit just the basic styling of a thumbs up button and can I import the button from any library and style it or is there some other method I am not aware of.
2.Will there be any hover or onclick effects.

Any suggestions or help will be awesome :)

**Comment by shahednasser** [comment]
Hi @wisetok12680 . You can use font awesome to get the icon for the button. you should place the styling in a new file in `src/components/icon/` directory. You can refer to other icon buttons on a guide on how to do this properly.

After you're done you should compile the code with `npm run compile` then add the button in `assets/js/buttons-examples.js` as indicated in the contributing guidelines.

If you need any more help please let me know.

**Comment by wisetok12680** [comment]
Sure thanks

**Comment by wisetok12680** [comment]
Hey there, 
So I have successfully cloned the repo and after getting ready to edit, I created a `_thumbsup.less` in```src/components```. Now I am unable to Import the font awesome icon. Placing the cdn in the index.html doesn't seem to work.
Please help as this is very new to me altogether.

**Comment by shahednasser** [comment]
Hi @wisetok12680 . First you need to place `_thumbsup.less` in `src/components/icon/` and you need to import it in `src/components/_icon.less`. Then, you need to add it in `assets/js/buttons-examples.js` to show up on the website. 

Font awesome is already present in the website. If you're having trouble using the icon please refer to other implementations of icons in `src/components/icon/` directory. Maybe check out `_plus.less` as it is straightforward.

**Comment by shahednasser** [comment]
Also don't forget to run `npm run compile` once you are done making changes to see your changes on the website. Please check out the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md) for more info

**Comment by wisetok12680** [comment]
Ok,
That really helps.. thank you so much.

**Comment by wisetok12680** [comment]
Hey there,
Thank you for the assistance throughout. I have made a pull request [https://github.com/sButtons/sbuttons/pull/625](url). Please tell if everything is alright and the changes to be done if it isn't.
