### ISSUE TITLE
[BUTTON IDEA]: Share Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#426]
**1. Name of button**: Share Button

**2. Description**: Button with the share icon only

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**Comment by LuciKritZ** [comment]
I would like to work on it.

**Comment by shahednasser** [comment]
Sure @LuciKritZ

**Comment by MeerHamza1421** [comment]
Can i work on it for hacktober?? and can i add a social media share button

**Comment by shahednasser** [comment]
Someone is assigned to this.

**Comment by LuciKritZ** [comment]
Hi @shahednasser ! I am actually a bit confused about choosing the icon for the share button.
I have the following choices:
1. 
![image](https://user-images.githubusercontent.com/26204432/94991180-f6e35f80-059e-11eb-83c2-dc49300eeb2f.png)
2. 
![image](https://user-images.githubusercontent.com/26204432/94991191-0b275c80-059f-11eb-8e3e-6f7361ed9b2e.png)
3.
![image](https://user-images.githubusercontent.com/26204432/94991202-21cdb380-059f-11eb-9ce8-3c10f6143176.png)
4. 
![image](https://user-images.githubusercontent.com/26204432/94991219-38740a80-059f-11eb-943a-3566f9f1c3dc.png)
5. 
![image](https://user-images.githubusercontent.com/26204432/94991227-4aee4400-059f-11eb-85c8-eb8c243ea42f.png)

For now, I have added this icon and share icon looks something like this in the main page:
![image](https://user-images.githubusercontent.com/26204432/94991250-6fe2b700-059f-11eb-835e-5a88fcac659c.png)

Do you have any suggestions? Or should I raise the PR if the icon seems okay?

**Comment by shahednasser** [comment]
I prefer the 4th one

**Comment by maityankan10** [comment]
Can i contribute for hacktoberfest

**Comment by shahednasser** [comment]
@maityankan10 someone is working on this
