### ISSUE TITLE
[BUTTON IDEA]: Screen Capture Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#427]
**1. Name of button**: Screen Capture Button

**2. Description**: Button with Camera icon

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**submitted by**: @ShrutiJha31

**Comment by LuciKritZ** [comment]
I can work on it.

**Comment by shahednasser** [comment]
Ok @LuciKritZ I'll assign you

**Comment by shahednasser** [comment]
Hi @LuciKritZ, are you still working on this?

**Comment by LuciKritZ** [comment]
Yes, I am working on it. Due to time constraints, I am not able to devote much time. But I'm working on it.

**Comment by LuciKritZ** [comment]
Sure!
