### ISSUE TITLE
[BUTTON IDEA]: Text Size +/- Buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#430]
**1. Name of button**: 

**2. Description**: A button to change the font/text size

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**: no

**submitted by**: @Archis19

**Comment by SanyuktaSaha** [comment]
@shahednasser I will work on it

**Comment by shahednasser** [comment]
Ok @SanyuktaSaha I will assign you

**Comment by shahednasser** [comment]
Closing this issue as I don't think this button has an importance and contributor didn't work on it.
