### ISSUE TITLE
[BUTTON IDEA]: Vintage Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#433]
**1. Name of button**: Vintage Button

**2. Description**: A button that has a Windows 95 Vintage style to it

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**: no

**submitted by**: @anonyda

**Comment by anonyda** [comment]
Hi @shahednasser, I am working on it

**Comment by shahednasser** [comment]
Great @anonyda I'll assign you
