### ISSUE TITLE
[BUTTON IDEA]: Neumorphic button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#434]
**1. Name of button**: Neumorphic button

**2. Description**: A button that has a neumorphic style

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**: no

**submitted by**: @vitoriapena

**Comment by pinkman7009** [comment]
can i work on it?

**Comment by shahednasser** [comment]
hi @pinkman7009 it's currently in progress

**Comment by Kazeno21** [comment]
can i work on this?

**Comment by shahednasser** [comment]
Hi @Kazeno21 it's currently in progress.

**Comment by crew-guy** [comment]
Hey ! Does anyone need help with this ?
