### ISSUE TITLE
[BUTTON IDEA]: Spooky Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#435]
**1. Name of button**: Spooky Button

**2. Description**: A button with dramatic/spooky touch to it for special website designs.

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**: no

**submitted by**: @confusedcoder1

**Comment by confusedcoder1** [comment]
I am working on it actually. But I guess more people can try and we will see mutliple versions.

**Comment by shahednasser** [comment]
I'm assigning you to it @confusedcoder1 . This is just due to confusions caused by the button ideas file.

**Comment by malihanan** [comment]
Can I work on this?

**Comment by shahednasser** [comment]
Someone is assigned to this. Please pick an unassiged issue.

**Comment by Hyma200** [comment]
Is this issue still assigned? Can I work on this?

**Comment by shahednasser** [comment]
You can work on it @Hyma200

**Comment by confusedcoder1** [comment]
Hey @shahednasser, I have already designed the button and the Css part is done too, I just was not able to edit HTML for finally merging, due to some time constraints. Sorry,I should have kept you updated.

**Comment by shahednasser** [comment]
Hi @confusedcoder1 that's fine. We have made a lot of changes to the repo and how everything works so I suggest you take a look again at what you need to do. Once you feel like you can submit a PR for it you can go ahead

**Comment by Hyma200** [comment]
Can I still work on this?

**Comment by shahednasser** [comment]
Yes you can too @Hyma200
