### ISSUE TITLE
[BUTTON IDEA]: Loading Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#436]
**1. Name of button**: Loading Button

**2. Description**: A button with CSS loading

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**: no

**submitted by**: @akshatgarg12

**Comment by chinmaikaveti2001** [comment]
hi!....can u please assign this issue to me......?
I  want to work on this issue.....

**Comment by shahednasser** [comment]
sure @chinmaikaveti2001 but this issue is kind of tricky as it needs to be only CSS and while making it as simple as possible.

**Comment by chinmaikaveti2001** [comment]
thank you  @shahednasser

**Comment by chinmaikaveti2001** [comment]
mam can we use bootstrap frame.....?

**Comment by chinmaikaveti2001** [comment]
mam can i use bootstrap framework..?

**Comment by shahednasser** [comment]
@chinmaikaveti2001 no we need to implement them ourselves.

**Comment by chinmaikaveti2001** [comment]
kk..mam

**Comment by abhishekrawe** [comment]
I want towork on it

**Comment by shahednasser** [comment]
@abhishekrawe someone is assigned to this issue.

**Comment by PriyanshTri** [comment]
can I work on this?

**Comment by shahednasser** [comment]
As @chinmaikaveti2001 is not responding or committing any code, I will assign you @PriyanshTri instead

**Comment by Caleb335** [comment]
Hi @shahednasser I'd love to work on this

**Comment by shahednasser** [comment]
Hi @Caleb335 yes go ahead!

**Comment by Caleb335** [comment]
> Hi @Caleb335 yes go ahead!

Alright, thanks.

But before I proceed, do I need to make variations of the loading button? If yes, can you specify the types that I'd be making?

**Comment by shahednasser** [comment]
@Caleb335 I haven't really thought of that. If you have different type of variations then go ahead but make sure all variations use CSS only.

**Comment by Caleb335** [comment]
Alright, will do ✌️

**Comment by harsh863** [comment]
@shahednasser can i work on this?

**Comment by shahednasser** [comment]
@harsh863 someone is working on this
