### ISSUE TITLE
Add minified version of sbuttons.css with minification action

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#452]
This was previously available but caused a lot of conflicts in PR requests because it was compiled on every change. The improved way to do it is remove compiling the sbuttons.min.css from the compile scripts, and only apply the minification on pushing to the repo by using a Github Action.

Currently I'm assigning myself to this, but if someone also has knowledge in Github Actions and thinks can take this on please comment below.

**Comment by mayankmohak** [comment]
Can i do it.

**Comment by shahednasser** [comment]
Hi @mayankmohak sure you can. I'll assign you.

**Comment by mayankmohak** [comment]
@shahednasser  please review the changes
