### ISSUE TITLE
[BUTTON IDEA]: Neon Trace Button

### ISSUE THREAD

**Issue by aayushi221** [sButtons/sbuttons#453]
**1. Name of button**: Neon trace button

**2. Description**: An outline button whose border gets traced by a sleek line from start to end.

**3. Button Type (Animated, Special, etc...)**:Animated, Neon

**4. Will you work on it?**:Yes

**Comment by shahednasser** [comment]
Hi @aayushi221 there's already an issue for trace button, can please clarify the difference?

**Comment by aayushi221** [comment]
@shahednasser Yeah I saw that issue, but this one will have a neon effect to it to, with a slight delay in transition.
https://drive.google.com/file/d/1ZWiuXdxDHNcMRlWgqTo53o0GmW1NnIrR/view?usp=sharing
check this out

**Comment by Deepakmukka1** [comment]
@aayushi221 i can do it can you assign me this

**Comment by shahednasser** [comment]
Ok @aayushi221 it looks nice. Please work on it.
