### ISSUE TITLE
[BUTTON IDEA]:Social media sliding button

### ISSUE THREAD

**Issue by aayushi221** [sButtons/sbuttons#455]
**1. Name of button**: Social media sliding button

**2. Description**:  Social media sliding icon hover effect, a slider slides and shows the name of social media.

**3. Button Type (Animated, Special, etc...)**: Icon

**4. Will you work on it?**:Yes

**Comment by shak1505** [comment]
May i take up this issue?

**Comment by shahednasser** [comment]
Hi @aayushi221 I'm not sure what you mean by this but you can work on it and show me.

**Comment by aayushi221** [comment]
@shahednasser Sure, I am on it!
