### ISSUE TITLE
[BUTTON IDEA]: Hover Fancy

### ISSUE THREAD

**Issue by shak1505** [sButtons/sbuttons#468]
**1. Name of button**: Hover Fancy

**2. Description**: as the mouse is hovered on any button, it will show the name of the social media. 

**3. Button Type (Animated, Special, etc...)**:special

**4. Will you work on it?**: Yes.

**Comment by shahednasser** [comment]
Hi @shak1505 I'm honestly not sure what you exactly mean by that, but you can work on it and I'll see it when you submit a pull request.

**Comment by Summer-source** [comment]
I want to contribute on the  issue

**Comment by Summer-source** [comment]
I would like to work on this!

**Comment by shahednasser** [comment]
someone is assigned to this issue @Summer-source

**Comment by shahednasser** [comment]
Closing this issue as it is stale and the idea is not important
