### ISSUE TITLE
[BUTTON IDEA]: Diagonally curved button shape.

### ISSUE THREAD

**Issue by adsingh14** [sButtons/sbuttons#477]
**1. Name of button**: Diagonally curved button.

**2. Description**: Button curved 5% diagonally from vertices or vice versa **&** the remaining vertices will be 20% curved. 

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**: Yes.

**Comment by shahednasser** [comment]
I've edited it to change the button type. But please don't start working on it now as we are adding the special category. I'll let you know once you can.

**Comment by shahednasser** [comment]
Hi @adsingh14 you can now add this button under Special

**Comment by adsingh14** [comment]
Because this button will reflect the curved area. So, there's no need of `.rounded-btn` here. Shall I amend the javascript for this exceptional case or keep it as it is ?

**Comment by shahednasser** [comment]
Honestly I'm still not sure what the idea still means. Can you first work on it and submit a pull request, then we can look into that part?

**Comment by adsingh14** [comment]
#490, Please check '.rounded-btn'. Is it looking good with curved-corners buttons ?
