### ISSUE TITLE
Add comments in JS files

### ISSUE THREAD

**Issue by adsingh14** [sButtons/sbuttons#480]
**Is your feature request related to a problem? Please describe.**
Code is not formatted. 

**Describe the solution you'd like**
Single/block line comment indeed ! It would be great to add comments before committing code.  
`// Single line code for rare but useful checkpoints `
`/* Block lines comment
    for well documented code */`

**Additional notes**
I know the minified files won't include any comment but it will be useful for devs.

**Comment by shahednasser** [comment]
Do you mean comments in the less files?

**Comment by adsingh14** [comment]
Extremely needed in JS and css ((un-minified versions).

**Comment by palakyadav1807** [comment]
Can you assign me this for .html file?

**Comment by shahednasser** [comment]
@adsingh14 I don't think it's necessary in the CSS but you're right about the JS. I'll change the title to make it more fitting. Let me know if you would like to work on it.

**Comment by HADES-01** [comment]
@shahednasser Should the comments be detailed or just general explanation of functions? I can get on it either way.

**Comment by shahednasser** [comment]
@HADES-01 I guess it should be enough to make it understandable for contributors. I'll assign you.

**Comment by adsingh14** [comment]
I will add single line comments in main **.js** file.

**Comment by shahednasser** [comment]
Ok @HADES-01 you can work on `assets/js/buttons-examples.js` and @adsingh14 you can work on `assets/js/index.js`

**Comment by adsingh14** [comment]
Sounds good ! Later on, I will follow JSDoc guidelines for block comments and I recommend the same to other assignee.

**Comment by HADES-01** [comment]
@adsingh14 Yeah sure.

**Comment by shahednasser** [comment]
@HADES-01 added good documentation in buttons-examples.js but now I'm thinking maybe we should also include in the documentation the keys allowed in `buttons` array as it can get confusing. What do you guys think?

**Comment by HADES-01** [comment]
@shahednasser Yeah, I actually was going to create a new issue regarding this very feature. We should include it in the contributors guidelines so that it removes all the ambiguity for the contributors.

**Comment by shahednasser** [comment]
@HADES-01 it's already in the contributing guidelines but I think we should add it in the jsDoc as well. Let me know if you can do that

**Comment by HADES-01** [comment]
@shahednasser Just to be sure you want me to add `jsDoc` for the keys of the button object in the `buttons-examples.js`.

**Comment by shahednasser** [comment]
@HADES-01 yes

**Comment by HADES-01** [comment]
@shahednasser Okay, then you can assign it to me.

**Comment by adsingh14** [comment]
Need help ! 

In **index.js**, is the mentioned code-block 👇 in use or not ? 
If it's written for future purpose, then what should I write in comment ?

```  
   // What should I write here ?

   $("body").click(function (event) {
    var sidebar = $(".sidebar");
    var targetElement = $(event.target);
    if (
      $(window).width() <= 767 &&
      !targetElement.hasClass("sidebar") &&
      !targetElement.parents(".sidebar").length &&
      sidebar.hasClass("animate__slideInLeft") &&
      !sidebar.hasClass("hide-sidebar")
      ) {
      toggleSidebar();
    }
  });
```

**Comment by adsingh14** [comment]
#583, Added a few lines of comment.

**Comment by shahednasser** [comment]
> ❓ Need help !
> 
> In **index.js**, is the mentioned code-block 👇 in use or not ?
> If it's written for future purpose, then what should I write in comment ?
> 
> ```
>    // What should I write here ?
> 
>    $("body").click(function (event) {
>     var sidebar = $(".sidebar");
>     var targetElement = $(event.target);
>     if (
>       $(window).width() <= 767 &&
>       !targetElement.hasClass("sidebar") &&
>       !targetElement.parents(".sidebar").length &&
>       sidebar.hasClass("animate__slideInLeft") &&
>       !sidebar.hasClass("hide-sidebar")
>       ) {
>       toggleSidebar();
>     }
>   });
> ```
> 
> I'm leaving this code as it is without comment.

This code is necessary for clicking the sidebar when clicking outside of it.
