### ISSUE TITLE
[BUTTON IDEA]: Diagonally appearing background on hover

### ISSUE THREAD

**Issue by tushar2407** [sButtons/sbuttons#482]
**1. Name of button**:  diagonal_background

**2. Description**:  when on hovers on the button, say the current background colour of the button is black, so that will change to white. But that white background will appear from right bottom. More like a diagonal making the colour change. 

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: Yes, definitely.

**Comment by shahednasser** [comment]
I'm honestly not sure I understand this idea but I'll assign you to it. I'll see if it's good or not when you submit the PR.

**Comment by tushar2407** [comment]
@shahednasser 
I have made my pull request but didn't see any reviewers. Could you please confirm if you can see my PR and edit it?
Thanks
