### ISSUE TITLE
[BUTTON IDEA]:Close Icon Buttons

### ISSUE THREAD

**Issue by gokul112** [sButtons/sbuttons#506]
**1. Name of button**: Close Button

**2. Description**: Button with close icon

**3. Button Type (Animated, Special, etc...)**:icon

**4. Will you work on it?**:I will work on it.

**Comment by shahednasser** [comment]
Sounds good. You should make the background transparent (not like other buttons).

**Comment by gokul112** [comment]
Yeah sure
