### ISSUE TITLE
Align Social Media Icons in Buttons center vertically

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#513]
In Social Buttons, the icons should be aligned center vertically.

**Comment by dineshsy** [comment]
sure can I take this issue let me try to complete it :smiley_cat:  @shahednasser

**Comment by shahednasser** [comment]
sure @dineshsy go ahead.

**Comment by dineshsy** [comment]
![image](https://user-images.githubusercontent.com/50043613/94897383-20bc5980-04ad-11eb-8944-706bec72cf56.png)
This is what yu were expecting right? 
**The text and icon aligned equally**

**Comment by shahednasser** [comment]
Yes that's it!
