### ISSUE TITLE
[BUTTON IDEA]: Glow Button

### ISSUE THREAD

**Issue by malihanan** [sButtons/sbuttons#517]
**1. Name of button**: Glow Button

**2. Description**: A translucent button with neon borders with a glow effect on hover.

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Hi @malihanan we have a very similar idea to this. Can you confirm it's different than the "Neon" button?

**Comment by malihanan** [comment]
![Screenshot (994)](https://user-images.githubusercontent.com/50942732/94895320-d042fd00-04a8-11eb-8ef3-70f9ee4f5d5c.png)

I am thinking something similar to this

**Comment by shahednasser** [comment]
Alright then you can work on it.

**Comment by malihanan** [comment]
On it! Thanks
