### ISSUE TITLE
Change Button Ideas section in documentation

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#535]
Change content for Button Ideas section in both README and CONTRIBUTING to just "If you would like to suggest a new button idea, please create a "New Button Idea" Issue."

**Comment by shngt** [comment]
Hi, mind if I pick this up?

**Comment by shahednasser** [comment]
Sure @shngt go ahead

**Comment by shngt** [comment]
To clarify, you would like specifically the sentence "If you have ideas for buttons, please submit a new issue for it." in the README to be changed to the above right? The other sentences would be informative to keep, imo.

And in the CONTRIBUTING, should I add the sentence as the first line in the section? (Before "You can find on Button Ideas a list of ideas in a table...")

**Comment by shahednasser** [comment]
I want the text in both README and CONTRIBUTING to be changed to "If you would like to suggest a new button idea, please create a "New Button Idea" Issue."

**Comment by shngt** [comment]
Opened a PR just to confirm the changing the whole content is what you wanted.. if it's okay, let me know and I'll rebase and resubmit
