### ISSUE TITLE
Add content menu to CONTRIBUTING

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#538]
Add content menu to CONTRIBUTING. It should be added before "Installation"

**Comment by chriswmercer** [comment]
Hello, may I work on this?

**Comment by palakyadav1807** [comment]
Pls assign this to me.

**Comment by shahednasser** [comment]
Assigning @chriswmercer for commenting first

**Comment by chriswmercer** [comment]
Thank you

**Comment by chriswmercer** [comment]
PR on its way :)
