### ISSUE TITLE
Fix "Fill" rounded buttons on mobile

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#54]
On mobile devices (specifically iPhone), when clicking on buttons of type "Fill" the overlayed color doesn't fully fill the container button.

**Comment by Vansh1067** [comment]
can I work on this??

**Comment by shahednasser** [comment]
Sure!

**Comment by shahednasser** [comment]
It seems like no one is currently working on this issue if anyone is interested

**Comment by reveurguy** [comment]
the issue you are stating doesn't seem to exist. Has it been corrected?

**Comment by shahednasser** [comment]
@reveurguy It seems that this is happening to some buttons and not others. Please look at the screenshots for examples
![image](https://user-images.githubusercontent.com/27354907/93749328-6b62e980-fc02-11ea-968c-c3763378a3e9.jpeg)
![image](https://user-images.githubusercontent.com/27354907/93749334-6e5dda00-fc02-11ea-87e9-fdfd9f8cf881.jpeg)

**Comment by ahmad-shiddiq** [comment]
I didn't see that problem honestly, everything works well in my device.

**Comment by shahednasser** [comment]
That's interesting @ahmad-shiddiq what device are you using? Maybe this will help narrow the problem down

**Comment by ahmad-shiddiq** [comment]
I'm sorry, I thought that was IOS. I was trying on Ipad.
![WhatsApp Image 2020-09-25 at 3 07 10 PM](https://user-images.githubusercontent.com/53107961/94337552-6ee8dd00-0015-11eb-951d-6d70ac8444c6.jpeg)

But I tried on my phone too, same didn't see any problem as you said.
![WhatsApp Image 2020-09-26 at 4 30 28 PM](https://user-images.githubusercontent.com/53107961/94337576-b8d1c300-0015-11eb-9c40-48fadb42af3f.jpeg)

**Comment by shahednasser** [comment]
Thank you for sharing that @ahmad-shiddiq . Will keep this issue for future reference then.

**Comment by samyev** [comment]
Hi, has this issue been resolved? if not, can I work on it?

**Comment by shahednasser** [comment]
@samyev it has not been resolved. We've been having trouble reproducing it. If you can reproduce and fix it then go ahead!

**Comment by Caleb335** [comment]
@shahednasser what exactly is the problem?

Are the buttons too round?  On mobile? Please enlighten me, so I can try fixing it

**Comment by shahednasser** [comment]
> @shahednasser what exactly is the problem?
> 
> Are the buttons too round? On mobile? Please enlighten me, so I can try fixing it

The problem can be found in [this comment](https://github.com/shahednasser/sbuttons/issues/54#issuecomment-695991767). Some buttons are not being filled completely. This proved tricky as it could not be reproduced on all devices.

**Comment by Caleb335** [comment]
> > @shahednasser what exactly is the problem?
> > Are the buttons too round? On mobile? Please enlighten me, so I can try fixing it
> 
> The problem can be found in [this comment](https://github.com/shahednasser/sbuttons/issues/54#issuecomment-695991767). Some buttons are not being filled completely. This proved tricky as it could not be reproduced on all devices.

Ok, I've seen it, I'd try fixing it.

I'd let you know if I can't

**Comment by ankitaugale23** [comment]
> On mobile devices (specifically iPhone), when clicking on buttons of type "Fill" the overlayed color doesn't fully fill the container button.

Can I work on this?

**Comment by faraz16iqbal** [comment]
Is this issue still open?

**Comment by shahednasser** [comment]
@ankitaugale23 @faraz16iqbal you can work on it if you can reproduce it and find the solution for it (as it has been proven tricky to reproduce)

**Comment by samyev** [comment]
I'm not getting it, I implemented a function for recognition of the iPhone device, but the site ends up breaking, but the problem apparently is with the iPhone, on any other device the site works very well

**Comment by shahednasser** [comment]
> I'm not getting it, I implemented a function for recognition of the iPhone device, but the site ends up breaking, but the problem apparently is with the iPhone, on any other device the site works very well

Yea but someone even tried it on an iPhone and it worked fine for them, that's why it's tricky. I think this should be done with CSS but honestly I haven't figured it out either. Thank you for working on it!

**Comment by Caleb335** [comment]
> I'm not getting it, I implemented a function for recognition of the iPhone device, but the site ends up breaking, but the problem apparently is with the iPhone, on any other device the site works very well

You are right about this...

'cause while I was viewing it on my device (an android) it works fine

**Comment by samyev** [comment]
> > Não estou entendendo, implementei uma função de reconhecimento do aparelho iPhone, mas o site acaba quebrando, mas o problema aparentemente é com o iPhone, em qualquer outro aparelho o site funciona muito bem
> 
> Sim, mas alguém até experimentou em um iPhone e funcionou bem para eles, é por isso que é complicado. Acho que isso deveria ser feito com CSS, mas, honestamente, também não descobri. Obrigado por trabalhar nisso!

I believe that the problem may be with the version of the IOS system then, because it runs on one and the other does not. I've been researching deeper and saw that safari on iPhone ends up breaking the CSS of the sites.

**Comment by samyev** [comment]
> > Não estou entendendo, implementei uma função de reconhecimento do aparelho iPhone, mas o site acaba quebrando, mas o problema aparentemente é com o iPhone, em qualquer outro aparelho o site funciona muito bem
> 
> Você está certo sobre isso ...
> 
> porque enquanto eu estava visualizando no meu dispositivo (um Android), ele funciona bem

With mine too, and I realized that in some versions IOS it runs well, and in others the site does not open

**Comment by shahednasser** [comment]
Thank you for the inside @samyev . I guess we'll leave it open for now and see if we can ever find a fix for it.

**Comment by samyev** [comment]
> Obrigado por dentro @samyev . Acho que vamos deixar em aberto por enquanto e ver se podemos encontrar uma solução para isso.

That’s okay ><

**Comment by abhishekrawe** [comment]
yes, I m intrested on this , please assign me.

**Comment by basvandenwijngaard** [comment]
I'm able to reproduce this with rounded buttons with the fill-animation effect on an iPhone Xs, but also on Safari on macOs. I also have a possible fix for it.

**Comment by shahednasser** [comment]
Issue finally resolved. Thank you everyone!
