### ISSUE TITLE
Create base Icon button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#549]
There are a lot of different ideas for icon buttons being added but we can't really create a button for each icon out there when all that needs to be done is changing the unicode of the icon to the one the user would want to use.

Let's add a Base Icon Button where the only required thing to add to it is the font awesome class to it. This way we don't need to add a class for each icon.

Required changes to be made:
- [ ] Create Base Icon Button with the formatting needed to make it look good, without adding any icon to it.
- [ ] Add an additional class for positioning of the icon (left or right of the text)
- [ ] Test that it would work fine with and without text.
- [ ] Add to the documentation (Readme and Get Started page) a note about using any icon with the base icon button.

**Comment by shahednasser** [comment]
@gokul112 would you like to work on this?

**Comment by gokul112** [comment]
Yeah sure i will work on it !

**Comment by Caleb335** [comment]
I'd love to work on this...

Is it open?

**Comment by shahednasser** [comment]
@Caleb335 are you sure you can take it? It can be a lot of work

**Comment by Caleb335** [comment]
> @Caleb335 are you sure you can take it? It can be a lot of work

Yes, I will be able to work on it. 🙂 

Thanks

**Comment by shahednasser** [comment]
I assigned you @Caleb335

**Comment by Caleb335** [comment]
On it.

**Comment by abhishekrawe** [comment]
I want to work on it ? Kindly assign me

**Comment by shahednasser** [comment]
@abhishekrawe soemone is already assigned and is working on this.

**Comment by abhishekrawe** [comment]
> @abhishekrawe soemone is already assigned and is working on this.

okay,  is there any another issue? so please kindly assign me, i want to work on your repository

**Comment by shahednasser** [comment]
Hi @Caleb335 I was discussing this issue with fellow members in this repository, and we think the styling of the icon should not use ":before" and ":after" like what we have been doing, instead it should rely on an `i` element inside the button. The reason behind this is:

1. If the icon button were to be used in combination with other buttons, it can cause a problem as other buttons use `:before` and `:after` for other styling.
2. Most users are used to using `i` for icons anyway.

So please make sure to use `i` for styling the icons inside buttons. We will then add it in the documentation for users to know about it.

Thank you!

**Comment by Caleb335** [comment]
> Hi @Caleb335 I was discussing this issue with fellow members in this repository, and we think the styling of the icon should not use ":before" and ":after" like what we have been doing, instead it should rely on an `i` element inside the button. The reason behind this is:
> 
> 1. If the icon button were to be used in combination with other buttons, it can cause a problem as other buttons use `:before` and `:after` for other styling.
> 2. Most users are used to using `i` for icons anyway.
> 
> So please make sure to use `i` for styling the icons inside buttons. We will then add it in the documentation for users to know about it.
> 
> Thank you!

Hi @shahednasser, 

Thanks for noting this. I actually didn't use those pseudo-classes at all. 

I just submitted a PR now, kindly review
