### ISSUE TITLE
Add animation to the navbar on scroll

### ISSUE THREAD

**Issue by HADES-01** [sButtons/sbuttons#550]
**Describe the feature you'd like**
When scrolling the navbar seems to just jumps in and out (looks weird) of the page as there is no animation to it.

**Additional notes**
The navbar should have a animation so that it transitions in and out the page on scrolling.

**Comment by ibhavikamalhotra** [comment]
I would like to work on this @shahednasser  .

**Comment by hussein-hub** [comment]
1. The width occupied by first three buttons in the first row in many sections is a bit less than that of the width occupied by the rest of the rows which looks a bit non uniform. Example Pudding section.
2. The animation of in shine buttons goes fast which makes it difficult for the eye to catch the effect correctly.
3. The text for the yellow dashed button(small rectangle buttons) is in black that looks out of trend.(tried applying the same yellow color to the text it is visible)
4. The text for  yellow disabled button is missing

**Comment by hussein-hub** [comment]
1. The width occupied by first three buttons in the first row in many sections is a bit less than that of the width occupied by the rest of the rows which looks a bit non uniform. Example Pudding section.
2. The animation of in shine buttons goes fast which makes it difficult for the eye to catch the effect correctly.
3. The text for the yellow dashed button(small rectangle buttons) is in black that looks out of trend.

**Comment by shahednasser** [comment]
Ok @HADES-01 can you work on it as you seem to visualize how it should look like?
