### ISSUE TITLE
Change Shine animation

### ISSUE THREAD

**Issue by hussein-hub** [sButtons/sbuttons#559]
1. The width occupied by first three buttons in the first row in many sections is a bit less than that of the width occupied by the rest of the rows which looks a bit non uniform. Example Pudding section.
2. The animation of in shine buttons goes fast which makes it difficult for the eye to catch the effect correctly.

**Comment by shahednasser** [comment]
hi @hussein-hub thank you for reporting these issues. I'll look into the first one and see the best fix for it. We're currently working on a layout fix for the website.

As for the second one, would you like to work on it?

**Comment by Easyvipin** [comment]
I can work on 2nd issue!

**Comment by hussein-hub** [comment]
Yes I would love to

**Comment by shahednasser** [comment]
Great @hussein-hub I will assign you.

**Comment by shahednasser** [comment]
Hi @hussein-hub any update on this?
