### ISSUE TITLE
[BUTTON IDEA]:

### ISSUE THREAD

**Issue by maulanagansss** [sButtons/sbuttons#562]
**1. Outline Hover**: 

**2. before hover the button is outline state whereas when hover it becomes a regular button (solid)**: 

**3. Hover**:

**4. Sorry i don't understand NPM
![simplescreenrecorder-2020-10-02_19 21 42](https://user-images.githubusercontent.com/71548744/94922830-11f19900-04e5-11eb-8bd8-c871b0368bba.gif)

**:

**Comment by shahednasser** [comment]
Hi @maulanagansss thank you for submitting this idea but we already have an issue for it!
