### ISSUE TITLE
[NEW BUTTON IDEA ]:

### ISSUE THREAD

**Issue by vaishnavijha** [sButtons/sbuttons#563]
**1. Name of button**:  Dynamic animated type

**2. Description**: Giving a dynamic animated behavior to button by filling the button with its border color inside when mouse hovered in and the same outside when mouse is withdrawn with change in text style.when one brings mouse over button it seems colors are filling inside from border to body of button with the change in text color as well as style and the same happens in reverse when one starts taking out the mouse .

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: Yes ,i want to work on it.

**Comment by shahednasser** [comment]
Hi @vaishnavijha we have a similar button idea in the works. Thank you for suggesting a new idea though!
