### ISSUE TITLE
Sidebar overlays footer

### ISSUE THREAD

**Issue by arjuna1729** [sButtons/sbuttons#564]
**1 - Describe the bug**
The sidebar list overlays footer when scrolling to the bottom of the page.
**2 - Expected behavior of what should have happened (if applicable)**

**3 - Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/33598813/94926378-50d02080-04de-11eb-9997-530dbc0519e7.png)

**4 - Additional notes**

**Comment by pinkman7009** [comment]
can i work on this issue?

**Comment by Dheerajbana** [comment]
can i take thiis up

**Comment by shahednasser** [comment]
Hi @arjuna1729 can you provide more info on this? What browser are you using and what's the screen width that this bug is happening on? Thanks!

**Comment by adsingh14** [comment]
I am using Mozilla Firefox. I think that's happening in all browsers because it's the CSS syntactical error. 

![image](https://user-images.githubusercontent.com/35252877/94959985-bc7eb180-050f-11eb-8436-2ff050729ad6.png)

**Comment by shahednasser** [comment]
You are all correct this is due to an increase in the number of items, not a CSS syntactical error. It can be resolved in multiple ways.

@arjuna1729 thank you for reporting the bug. Would you like to work on it or should I assign it to someone else?

**Comment by pinkman7009** [comment]
can i work on this?

**Comment by shahednasser** [comment]
you may go ahead @pinkman7009

**Comment by adsingh14** [comment]
Footer has to be changed. Need to fill it up with more content.

**Comment by pinkman7009** [comment]
thank you @shahednasser . i will start working on this,

**Comment by shahednasser** [comment]
@adsingh14 please start a new issue with any idea you have instead of commenting on unrelated issues.

**Comment by pinkman7009** [comment]
@shahednasser i am not getting this error on chrome and firefox at 100% width screen size. can you tell me where i might be going wrong?

**Comment by shahednasser** [comment]
This could be due to different screen sizes. What's your screen width?

**Comment by pinkman7009** [comment]
@shahednasser my screen size is 15.6 inch which is around 1450 pixels.

**Comment by shahednasser** [comment]
That's odd but everyone has seen the bug by now. If you can't reproduce it then maybe we should assign it to someone else. Please let me know.

**Comment by pinkman7009** [comment]
@shahednasser okay then i guess you should assign it to someone else.

**Comment by shahednasser** [comment]
@Dheerajbana do you still want to work on this?

**Comment by Dheerajbana** [comment]
@shahednasser  Ok i will take this up. Was able to reproduce it on firefox with 133%
![image](https://user-images.githubusercontent.com/12607160/94992407-7c6b0d80-05a7-11eb-8209-572bfebe4c63.png)

**Comment by Dheerajbana** [comment]
@shahednasser i have added fix and created a pull request 
https://github.com/sButtons/sbuttons/pull/621

**Comment by shahednasser** [comment]
This issue is open for assignment again.

**Comment by Goodiec** [comment]
I will like to try this

**Comment by shahednasser** [comment]
Sure @Goodiec you can work on it.

**Comment by Hirak-Pandya** [comment]
Can I try this?

**Comment by shahednasser** [comment]
Someone is assigned now @Hirak-Pandya

**Comment by JithinAji** [comment]
Hi,

I think I was able to fix this issue. Will be very helpful if someone is able to do a code review for the same. :)

**Comment by shahednasser** [comment]
Hi @JithinAji someone is working on this. Please look for issues that are unassigned.

**Comment by JithinAji** [comment]
sure. 👍  @shahednasser

**Comment by Goodiec** [comment]
@shahednasser, the most I could do was make it go behind the footer and that isn't the best solution. I think @JithinAji should try his fix.

**Comment by Goodiec** [comment]
Also, I think coming up with another way to show the menu items would be nice as the list is bound to keep increasing

**Comment by Caleb335** [comment]
Can I work on this @shahednasser ?

**Comment by shahednasser** [comment]
Hi @Caleb335 sure you can! However, we're currently working on a website revamp so we just need a temporary solution. You can try a simple solution such as hiding the sidebar behind the footer for now. Thank you!

**Comment by Caleb335** [comment]
> Hi @Caleb335 sure you can! However, we're currently working on a website revamp so we just need a temporary solution. You can try a simple solution such as hiding the sidebar behind the footer for now. Thank you!

Alright @shahednasser I'd do just that.

**Comment by JithinAji** [comment]
@shahednasser How I did was giving the margin top a negative value whenever the bottom page is reached on scroll.
