### ISSUE TITLE
Link to website don't work

### ISSUE THREAD

**Issue by HADES-01** [sButtons/sbuttons#566]
**1 - Describe the bug**
Link to the website in the about and the readme sections are not working as the repository is moved.

**2 - Expected behavior of what should have happened (if applicable)**
They should posses the current website address.

**Comment by gokul112** [comment]
I will take this bug

**Comment by HADES-01** [comment]
@gokul112 I don't think if you can fix this as it can only be done by the owner.

**Comment by Dheerajbana** [comment]
i want to take this up

**Comment by HADES-01** [comment]
@Dheerajbana I don't think if you can fix this as it can only be done by the owner @shahednasser . I only added this issue to remind her.

**Comment by Dheerajbana** [comment]
@HADES-01  thanks for the update . Can you guide me having 5 years in IT want to contribute for hacktoberfest :)

**Comment by shahednasser** [comment]
Thank you @HADES-01 for pointing this out. Some things need to be re-done after creating the organization. Issue has been fixed now!
