### ISSUE TITLE
i am trying to make a keyboard button in the animation repo of sbuttons but the code writtenby me in .ls file not showing effect @shahednasser

### ISSUE THREAD

**Issue by Shreyansh252001** [sButtons/sbuttons#567]

**Comment by Shreyansh252001** [comment]
please help if any body wants i can provide him code

**Comment by Shreyansh252001** [comment]
@shahednasser

**Comment by HADES-01** [comment]
@Shreyansh252001 Can you elaborate your problem, I don't think I fully understand what you mean.

**Comment by Shreyansh252001** [comment]
@HADES-01 i  have made changes in the application.ls file and added a kybd-btn.ls fileinside which i have created a button which looks exact like keyboard button but the same button is not showing up with same effects when i include the code insidde the folder rather than running raw.what to do?i have also made changes in button-example,js for the same to include a new category of  buttons looking like keyboard just as other users did.

**Comment by HADES-01** [comment]
@Shreyansh252001 Can you give screenshots of `animation.less`, your new keybdb-btn file and `buttons-example.js`

**Comment by Shreyansh252001** [comment]
`@height:65;
@depth:6;
@color:#7fbb98;
@text-color:darken($color,10%);
@lighten-on-hover:7%;
@button-speed:.06;
@timing-function: ease-out;
.keyboard
{
    margin:auto;
    
    cursor: pointer;

    margin-left:5px;

    margin-bottom:15px;

    text-shadow:0 -2px 0 darken(@color,20%),0 1px 1px lighten(@color,20%);

    box-sizing: border-box;

    font-size: 2em;

    font-family: Arial, Helvetica, sans-serif;

    text-decoration: none;

    font-weight: bold;

    color:@text-color;

    &:visited{
        color:@text-color;
    }

    height:@height+px;

    line-height:@height+px;

    padding: 0 ((@height/2)+px);

    display:inline-block;
    
    width:auto;

    background: linear-gradient(to bottom,
    saturate(lighten(@color,15%),35%) 0%,
    saturate(lighten(@color,12%),15%) 26%,
    @color 100%);

    border-radius:5px;

    border-top:1px solid lighten(@color,22%);

    border-bottom:1px solid lighten(@color,20%);

    top:0;

    transition:all (@button-speed+s) @timing-function;

    position:relative;

    &:hover {
        background: linear-gradient(to bottom,
          lighten(saturate(lighten(@color,15%),35%),@lighten-on-hover) 0%,
          lighten(saturate(lighten(@color,12%),15%),@lighten-on-hover) 26%,
          lighten(@color,@lighten-on-hover) 100%);
      }

    &:active {
        top:$depth+px;
             text-shadow:0 -2px 0 darken(@color,0%),0 1px 1px lighten(@color,20%), 0 0 4px white ;
        color:lighten(@color,45%);
    &:before {
          top:0;
          box-shadow: 0 3px 3px rgba(0,0,0,.7),0 3px 9px rgba(0,0,0,.2);
        }
      }

      &:before {
        display:inline-block;
        content:'';
        position:absolute;
        left:0;
        right:0;
        z-index:-1;
        top:($depth)+px;
        border-radius:5px;
        height:($height)+px;
        background: linear-gradient(to top,
          saturate(darken($color,40%),15%) 0%,
          saturate(darken($color,25%),10%) $depth+px);
        transition:all(($button-speed*1.3) + s) $timing-function;
        box-shadow:
          0 1px 0 2px rgba(0,0,0,.3),
          0 5px ($depth*.4+px) rgba(0,0,0,.5),
          0 ($depth*1.8+px) 9px rgba(0,0,0,.2);
      }  
}`
keyboard.less

**Comment by Shreyansh252001** [comment]
`
$(document).ready(function () {
  //default button class
  var defaultClass = "sbtn";
  //button color variations
  var buttonColors = [
    "blue-btn",
    "pink-btn",
    "red-btn",
    "green-btn",
    "yellow-btn",
    "orange-btn",
    "purple-btn",
    "black-btn",
    "white-btn",
  ];
  //list of button types
  var buttons = 
  [
    {
      type: "basic",
      label: "Basic Buttons",
      classes: "basic-btn",
      children: [],
    },
    {
      type: "animated",
      label: "Animated Buttons",
      classes: "",
      children: [
        {
          type:"keyboard",
          label:"keyboard button",
          classes:"keyboard",
        },
        {
          type: "click",
          label: "Click",
          classes: "click-btn",
        },
        {
          type: "fill-color-down",
          label: "Fill Color - Down",
          classes: "fill-color-btn down-fill",
        },
        {
          type: "fill-color-left",
          label: "Fill Color - Left",
          classes: "fill-color-btn",
        },
        {
          type: "fill-color-right",
          label: "Fill Color - Right",
          classes: "fill-color-btn right-fill",
        },
        {
          type: "fill-color-up",
          label: "Fill Color - Up",
          classes: "fill-color-btn up-fill",
        },
        {
          type: "hinge",
          label: "Hinge",
          classes: "hinge-btn",
        },
        {
          type: "invert",
          label: "Invert",
          classes: "invert-btn",
        },
        {
          type: "neon",
          label: "Neon",
          classes: "neon-btn",
        },
        {
          type: "next",
          label: "Next Button",
          classes: "next-arrow-btn",
        },
        {
          type: "nudge",
          label: "Nudge",
          classes: "nudge-btn",
        },
        {
          type: "previous",
          label: "Previous Button",
          classes: "previous-arrow-btn",
        },
        {
          type: "pulse",
          label: "Pulse",
          classes: "pulse-btn",
        },
        {
          type: "ripple",
          label: "Ripple",
          classes: "ripple-btn",
        },
        {
          type: "scale",
          label: "Scale",
          classes: "scale-btn",
        },
        {
          type: "shake",
          label: "Shake",
          classes: "shake-btn",
        },
        {
          type: "shine",
          label: "Shine",
          classes: "shine-btn",
        },
        {
          type: "skew",
          label: "Skew",
          classes: "skew-btn",
        },
        {
          type: "splash",
          label: "Splash",
          classes: "splash-btn",
        },
      ],
    },
    {
      type: "disable",
      classes: "btn-disabled",
      label: "Disabled Buttons",
    },
    {
      type: "hover",
      label: "Hover Buttons",
      classes: "hover-btn",
      children: [],
    },
    {
      type: "icon",
      label: "Icon Buttons",
      classes: "",
      children: [
        {
          type: "add-to-cart",
          label: "Add To Cart Button",
          classes: "add-to-cart-btn",
          text: "Add To Cart",
        },

        {
          type: "buy-me-coffee",
          label: "Buy Me Coffee Button",
          classes: "buy-me-coffee-btn",
          text: "Buy me coffee",
        },
        {
          type: "download",
          label: "Download Button",
          classes: "download-btn",
          text: "Download",
        },
        {
          type: "like",
          label: "Like Button",
          classes: "like-btn",
          text: "",
        },
        {
          type: "play",
          label: "Play Button",
          classes: "play-btn",
          text: "",
        },
        {
          type: "plus",
          label: "Plus Button",
          classes: "plus-btn",
          text: "",
        },
      ],
    },
    {
      type: "outline",
      label: "Outline Buttons",
      classes: "outline-btn",
      children: [],
    },
    {
      type: "social",
      label: "Social Buttons",
      classes: "social-btn",
      variations: [
        {
          classes: "apple",
          text: "Login with Apple",
        },
        {
          classes: "facebook",
          text: "Login with Facebook",
        },
        {
          classes: "github",
          text: "Login with Github",
        },
        {
          classes: "google",
          text: "Login with Google",
        },
        {
          classes: "instagram",
          text: "Login with Instagram",
        },
        {
          classes: "linkedin",
          text: "Login with LinkedIn",
        },
        {
          classes: "twitter",
          text: "Login with Twitter",
        },
        {
          classes: "weibo",
          text: "Login with Weibo",
        },
      ],
      children: [],
    },
  ];

  var sidebar = $(".sidebar-list"),
    content = $("#content");

  function getButtonHtml(
    classes,
    textClasses,
    buttonText,
    isBlock,
    isDisabled
  ) {
    if (buttonText === false) {
      buttonText = "Button";
    }
    return `
            <div class="button-container">
                <button class="${classes}" role="Button"
                  ${isDisabled ? 'aria-disabled="true" tabindex="-1"' : ""}
                  >${buttonText}</button>
                ${!isBlock ? "<br>" : ""}
                <small class="button-caption-sub">${textClasses}</small><br>
            </div>
        `;
  }

  function getMenuLinkHtml(type, label, isSubMenu) {
    return (
      '<a href="#' +
      type +
      '" ' +
      (isSubMenu ? 'class="submenu-link" ' : "") +
      ">" +
      label +
      "</a>"
    );
  }

  function createSection(button, shouldAddToSidebar) {
    var heading = "h1";
    if (shouldAddToSidebar) {
      // add link to sidebar
      sidebar.append(getMenuLinkHtml(button.type, button.label, false));
    } else {
      heading = "h3";
    }
    var section = $('<section id="' + button.type + '">');

    section.append(
      "<" +
        heading +
        ' class="section-header">' +
        button.label +
        "</" +
        heading +
        ">"
    );
    if (button.hasOwnProperty("children") && button.children.length) {
      //add children buttons
      var submenu = $('<div class="submenu-links">');
      for (var j = 0; j < button.children.length; j++) {
        var childSection = createSection(button.children[j], false);
        childSection.appendTo(section);
        if (j !== 0) {
          childSection.before('<hr class="secondary-hr">');
        }
        submenu.append(
          getMenuLinkHtml(
            button.children[j].type,
            button.children[j].label,
            true
          )
        );
      }
      sidebar.append(submenu);
    } else {
      var buttonArr = buttonColors;
      var isDisabled = false;
      if (button.hasOwnProperty("variations")) {
        buttonArr = button.variations;
      } else {
        if (button.type === "disable") {
          isDisabled = true;
        }
      }

      //add type buttons
      var normalButtonsGrid = $('<div class="button-grid">'),
        roundedButtonsGrid = $('<div class="button-grid">'),
        blockButtonsGrid = $('<div class="button-grid">'),
        buttonText = button.hasOwnProperty("text") ? button.text : false;
      for (var j = 0; j < buttonArr.length; j++) {
        var thisButtonText =
          buttonText !== false
            ? buttonText
            : buttonArr[j].hasOwnProperty("text")
            ? buttonArr[j].text
            : false;
        var thisButtonClasses = buttonArr[j].hasOwnProperty("classes")
          ? buttonArr[j].classes
          : buttonArr[j];
        normalButtonsGrid.append(
          getButtonHtml(
            `${defaultClass} ${button.classes} ${thisButtonClasses}`,
            `.${defaultClass} .${button.classes} .${thisButtonClasses}`,
            thisButtonText,
            false,
            isDisabled
          )
        );
        roundedButtonsGrid.append(
          getButtonHtml(
            `${defaultClass} ${button.classes} rounded-btn ${thisButtonClasses}`,
            `.${defaultClass} .${button.classes} .rounded-btn .${thisButtonClasses}`,
            thisButtonText,
            false,
            isDisabled
          )
        );
        blockButtonsGrid.append(
          getButtonHtml(
            `${defaultClass} ${button.classes} block-btn ${thisButtonClasses}`,
            `.${defaultClass} .${button.classes} .block-btn .${thisButtonClasses}`,
            thisButtonText,
            true,
            isDisabled
          )
        );
      }
      section.append(normalButtonsGrid);
      section.append(roundedButtonsGrid);
      section.append(blockButtonsGrid);
    }
    return section;
  }

  for (var i = 0; i < buttons.length; i++) {
    var section = createSection(buttons[i], true);
    section.appendTo(content).before('<hr class="secondary-hr">');
  }
});
`
button-example.js

**Comment by HADES-01** [comment]
@Shreyansh252001 Did you include this keyboard.less file in (_animation.less)[https://github.com/sButtons/sbuttons/blob/master/src/components/_animated.less] like this `@import "animated/_keyboard.less";
` and please change the class name to `.kybd-btn` and file name to `_kybd.less`.

**Comment by HADES-01** [comment]
@Shreyansh252001 And for next time you should just send the code you changed.

**Comment by Shreyansh252001** [comment]
yes
`@import "animated/_arrow.less";
@import "animated/_click.less";
@import "animated/_fill.less";
@import "animated/_hinge.less";
@import "animated/_invert.less";
@import "animated/_nudge.less";
@import "animated/_neon.less";
@import "animated/_pulse.less";
@import "animated/_ripple.less";
@import "animated/_scale.less";
@import "animated/_shake.less";
@import "animated/_shine.less";
@import "animated/_skew.less";
@import "animated/_splash.less";
@import "animated/_kybd.less";`

animation.less code

**Comment by Shreyansh252001** [comment]
> @Shreyansh252001 And for next time you should just send the code you changed.

ok

**Comment by HADES-01** [comment]
Is the file inside the animation folder ?

**Comment by Shreyansh252001** [comment]
it is inside components folder

**Comment by HADES-01** [comment]
It should be inside the animated folder which in turn is inside the components folder.

**Comment by Shreyansh252001** [comment]
doesn't work i tried

**Comment by Shreyansh252001** [comment]
[git-demo.zip](https://github.com/sButtons/sbuttons/files/5319120/git-demo.zip)

**Comment by HADES-01** [comment]
Now I got it. You should first run `npm run compile` to compile your changes. Then you will be able to see the changes.

**Comment by Shreyansh252001** [comment]
it is showing pm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\git-demo\git-hack\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\git-demo\git-hack\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shreyansh\AppData\Roaming\npm-cache\_logs\2020-10-02T17_10_10_170Z-debug.log
though i have installed npm

**Comment by Shreyansh252001** [comment]
on running npm run compile index.html

**Comment by HADES-01** [comment]
just run `npm run compile` inside the sbuttons folder and first run `npm install`

**Comment by HADES-01** [comment]
In my opinion you should just save `_keybd.less` somewhere else and restart by following the instructions in the [guidelines](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md). If you still have some problem than ask again. Closing this now.
