### ISSUE TITLE
[BUTTON IDEA]:Buttons with same colour of bit lighter background, darker border colour and darker text colour

### ISSUE THREAD

**Issue by VishakhaAwasthi01** [sButtons/sbuttons#579]
**1.Same Colour Buttons**: 

**2. [BUTTON IDEA]:Buttons with same colour of bit lighter background, darker border colour and darker text colour**: 

**3.Basic**:

**4. yes**:

**Comment by shahednasser** [comment]
Hi @VishakhaAwasthi01 , are you suggesting adding the same basic buttons but with different colors? If so we're currently not adding any new colors.

**Comment by VishakhaAwasthi01** [comment]
No actually, the buttons will have text of darker shade of their background colour and will have same colour of the border as of text

**Comment by shahednasser** [comment]
I'm not really sure what that means but you can add it only so I can see if it looks good or not. For now, add it under Special as we are not adding anything under Basic.

**Comment by VishakhaAwasthi01** [comment]
Sure

**Comment by VishakhaAwasthi01** [comment]
hey these are the buttons I was talking about[
![Screenshot 2020-10-04 at 12 41 14 AM](https://user-images.githubusercontent.com/45326880/94999977-bdc8e080-05da-11eb-975b-98a99e1d37d6.png)
](url)

**Comment by VishakhaAwasthi01** [comment]
I wanted the background colour of red and yellow bit lighter and color of yellow bit darker but for that I have to add new colours

**Comment by VishakhaAwasthi01** [comment]
![Screenshot 2020-10-04 at 12 51 27 AM](https://user-images.githubusercontent.com/45326880/95000199-69266500-05dc-11eb-851a-9ec4c10cab24.png)


Somewhat like this

**Comment by shahednasser** [comment]
I'm not a big fan of that. Thank you for the the idea but I'll be closing this issue.
