### ISSUE TITLE
Make shadows working with both themes.

### ISSUE THREAD

**Issue by adsingh14** [sButtons/sbuttons#580]
**Is your feature request related to a problem? Please describe.**
It would be great if every shadowed buttons looks better on both Dark/Light theme. 

**Describe the solution you'd like**
Anyone can check **rounded-diagonal-tl.less** file under CSS > Special folder for `box-shadow` code.

**Additional notes**

For reference, you could check `box-shadow` of Special > Rounded Diagonal buttons. 

![image](https://user-images.githubusercontent.com/35252877/94962297-db7f4280-0513-11eb-9558-91b96ba40a48.png)
 
![image](https://user-images.githubusercontent.com/35252877/94962336-e8039b00-0513-11eb-924f-6b7838ad0fb5.png)

**Note: This is an optional change.**

**Comment by shahednasser** [comment]
You're right it looks better. Would you like to work on it as you have worked on the rounded diagonal button or should we leave it to someone else?

**Comment by adsingh14** [comment]
I pass this code trick for others. I want other's to be a part of it.

**Comment by adsingh14** [comment]
I want other's to be a part of it.

**Comment by jonasvag** [comment]
Can you assign this task to me?

**Comment by mtanveersingh** [comment]
Hi, It's my first time contributing towards an open-source project. This issue seems feasible to me, can I work on solving it?

**Comment by shahednasser** [comment]
Assigning @jonasvag as they replied first.

**Comment by Priya378** [comment]
Is this issue still open? I also want to work on it.

**Comment by shahednasser** [comment]
@Priya378  Someone is assigned to this issue

**Comment by Priya378** [comment]
> @Priya378 Someone is assigned to this issue

Okay, Thank you! @shahednasser !

**Comment by shubh710** [comment]
@shahednasser If this is still open can I take that?
Thanks.

**Comment by jonasvag** [comment]
yes you can take it

**Comment by shubh710** [comment]
@shahednasser Please assign this to me, I can start working on it quickly.

**Comment by shubh710** [comment]
@shahednasser submitted a PR #727 .
Please review and merge.
