### ISSUE TITLE
Navbar overlaying sidebar on small devices

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#584]
**1 - Describe the bug**
On small devices (less than 768px) the navbar is overlaying the sidebar when it is toggled, which makes the items at the top of the sidebar not visible.
**2 - Expected behavior of what should have happened (if applicable)**
Navbar should not overlay sidebar and sidebar's items should all appear

**Comment by Goodiec** [comment]
Please could you assign this to me?

**Comment by PhilippeBarre** [comment]
Hello, I would like fix it

**Comment by vale-c** [comment]
Hi there! I'd also like to give this issue a try if possible :)

**Comment by adsingh14** [comment]
- It would be great if the scrolling behind the opened sidebar remains fixed or un-scrollable and toggle on hiding sidebar.

- Sidebar animation should fast. Maybe 0.3s or 0.5.

**Comment by shahednasser** [comment]
> * It would be great if the scrolling behind the opened sidebar remains fixed or un-scrollable and toggle on hiding sidebar.
> * Sidebar animation should fast. Maybe 0.3s or 0.5.

I'm not sure what you mean by the first one but you can submit a PR on the second one and I can see if it looks good.

**Comment by shahednasser** [comment]
Assigning @Goodiec as they commented first

**Comment by Goodiec** [comment]
Thank you, here my [PR](https://github.com/sButtons/sbuttons/pull/588)

**Comment by Goodiec** [comment]
#589

**Comment by Goodiec** [comment]
#611
