### ISSUE TITLE
Footer rework.

### ISSUE THREAD

**Issue by adsingh14** [sButtons/sbuttons#587]
**Is your feature request related to a problem? Please describe.**
Footer needs to be change. Add and replace content.
**Describe the solution you'd like**
Try to replace content with icons. eg. Icon with total contributors.
**Additional notes**
Utilize the footer space. Make it minimal.

**Comment by shahednasser** [comment]
You can work on it @adsingh14 and if it looks good I'll consider it.

**Comment by adsingh14** [comment]
Again, I pass it to another new comer.

**Comment by gokul112** [comment]
I will take this one!

**Comment by shahednasser** [comment]
@adsingh14 I can't really pass this one to anyone else as it is your idea and it is still vague so it's not 100% approved. Either you work on this or close this issue.
