### ISSUE TITLE
Get Started Block Buttons Example

### ISSUE THREAD

**Issue by isonnymichael** [sButtons/sbuttons#590]
**Is your feature request related to a problem? Please describe.**
![getStarted BLock Buttons Example](https://user-images.githubusercontent.com/24585708/94980435-ee196c00-0553-11eb-80bf-8548d20e6974.png)

I was check for getStarted page and found the Block Buttons was not have an example like other

**Describe the solution you'd like**
Would you like to show the Block Buttons example like others ?

**Additional notes**
I will work on it if you agree.

**Comment by shahednasser** [comment]
Yea work on it.
