### ISSUE TITLE
Get Started Page - Sidebar Icon Button not active 

### ISSUE THREAD

**Issue by isonnymichael** [sButtons/sbuttons#591]
**1 - Describe the bug**
Sidebar Icon Button not active when I press it.

**2 - Expected behavior of what should have happened (if applicable)**
Sidebar Icon Button must be active when pressed

**3 - Screenshots (if applicable)**
![Sidebar Icon Button Bug](https://user-images.githubusercontent.com/24585708/94980789-3ede9400-0557-11eb-9e84-37c7e7d2cef9.png)

**4 - Additional notes**

**Comment by Suniti13** [comment]
I would like to work on this.

**Comment by HADES-01** [comment]
@isonnymichael @Suniti13 I don't think it can be fixed according to how the code is setup right now.

**Comment by shahednasser** [comment]
@isonnymichael This is because the script is setting the active sidebar menu item based on page position. Changing this would require some rework.

You can work on it if you want but I don't find it a big problem.

**Comment by isonnymichael** [comment]
Yeah I know it based on page position, I will check later if I can fixed that without some rework but dont assign me now.
