### ISSUE TITLE
[BUTTON IDEA]: Round Social Button with just icon in it

### ISSUE THREAD

**Issue by Suniti13** [sButtons/sbuttons#594]
**1. Name of button**: Round Social Button

**2. Description**: A round social button that has icon inside it and nothing else. This can be used to direct users to the social media links.

**3. Button Type (Animated, Special, etc...)**: Social Button

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Hello @Suniti13 thank you for your idea, but we are currently not accepting any icon buttons as we are working on a new way to implement any icon button. Again thank you!
