### ISSUE TITLE
Navbar icons not aligned properly on mobile devices with screen width 350-400px.

### ISSUE THREAD

**Issue by pinkman7009** [sButtons/sbuttons#597]
**1 - Describe the bug**
The navbar icons like the Github icon, dark theme icon and the download icon are not aligned properly on mobile devices. On some devices like the Moto G4, the icons are not even visible.

**2 - Expected behavior of what should have happened (if applicable)**
The icons should be visible on the top right of the navbar even on mobile devices or can be placed below the logo SButtons but aligned at the center to make it look good.

**3 - Screenshots (if applicable)**
![sbuttonsissue](https://user-images.githubusercontent.com/52635583/94988766-520c5680-058d-11eb-9e06-cbf872aed06e.png)

**4 - Additional notes**
I would like to work on it.

**Comment by shahednasser** [comment]
@pinkman7009 instead of making them aligned in the navbar, can you just hide everything but the theme icon on small devices (less than 400px)?

**Comment by pinkman7009** [comment]
@shahednasser yes sure. should i keep the theme icon at the right of the navbar like in the desktop view?

**Comment by shahednasser** [comment]
Yes please

**Comment by pinkman7009** [comment]
@shahednasser sure ill get started with this.
