### ISSUE TITLE
Rename Button Labels

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#606]
There's inconsistency in the labels of buttons throughout the website. We need to rename it to the following:

1. Top level buttons (Basic, Animated, etc...) should always end with "Buttons".
2. Nested buttons (i.e. that fall under top level buttons) should not end with "Buttons", just the button name.

The change would be made just in `assets/js/buttons-examples.js`. This is an easy change so whoever wants to work on it should not take too long with it.

**Comment by mohitshende** [comment]
I would like to do this.

**Comment by shahednasser** [comment]
Sure @mohitshende I will assign you.

**Comment by mandepsingh** [comment]
will you please assign me this.
