### ISSUE TITLE
Better layout for basic/rounded/block buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#607]
Basic/Rounded/Block buttons should be split into tabs or something similar. This is necessary as the website is getting longer with every button added.

**Comment by lee00286** [comment]
Does it mean to split buttons in Basic Buttons into several tabs like Animated Buttons? Can I work on this issue?

**Comment by shahednasser** [comment]
No it means that each button should have a tab where you choose to reveal how it looks like as basic, rounded or block

**Comment by lee00286** [comment]
I tried to say the tabs like Bounce and Click under Animated Buttons tab. Did I understand it right?

**Comment by shahednasser** [comment]
No. Basically in Bounce button there would be tabs that says Basic, Rounded and Block and on clicking each it will show the Bounce button as basic or rounded or block. It doesn't have to be tabs if there's a better way of organizing it but that's the approach for now.

**Comment by lee00286** [comment]
Oh I think I understood. Can I work on "Basic Buttons" section first and continue for the other sections after the confirmation?

**Comment by shahednasser** [comment]
Ok I will assign you.

**Comment by HADES-01** [comment]
@shahednasser @lee00286 I think one of the better ways is to just dynamically change the classes of the buttons when the respective tab-button is clicked. So you will just have add tab-buttons and rest should be taken care of by js.

**Comment by shahednasser** [comment]
@HADES-01 yes but with the current way at least the execution is done during loading time and no extra execution is needed. I'm afraid the second way might end up buggy.

Maybe at first we can try the easy way which is to just add the tabs and hide/show on click, later on if we find it more optimal to do it the way you mentioned then we can optimize it.

**Comment by shahednasser** [comment]
Hi @lee00286 how is this issue going? Do you need any assistance?

**Comment by lee00286** [comment]
@shahednasser Hello I'm working on buttons tab that should display basic, rounded, and block buttons. I edited `index.html` to only show basic buttons at this point and each header (this is temporary decision for test... I will create buttons afterwards) directs to `buttonsPage.html` which I created. 

Currently I am thinking about the way to show only relative buttons in `buttonsPage.html` without creating html file for each section.

**Comment by shahednasser** [comment]
Hi @lee00286 thank you so much for your work! Unfortunately I will have to close this issue as you didn't reply before and we changed this issue to add it to another workflow of this project. I'm sorry and again thank you for your contribution!
