### ISSUE TITLE
Social Buttons "Login" G is getting cut. 

### ISSUE THREAD

**Issue by Dheerajbana** [sButtons/sbuttons#615]
**1 - Describe the bug**
In social buttons g is getting cut. It is due to font type. Please find the attached screenshot.

**2 - Expected behavior of what should have happened (if applicable)**
Login "G" should be proper

**3 - Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/12607160/94992079-0bc2f180-05a5-11eb-9698-19c2161e1d00.png)

**4 - Additional notes**
Please assign it to me i will fix it asap.

**Comment by Dheerajbana** [comment]
@shahednasser please assign me this issue

**Comment by shahednasser** [comment]
This is not a bug it is due to the font family of the website.

**Comment by Dheerajbana** [comment]
@shahednasser i know this so we should remove font family for social buttons. It is not looking good. Attaching the fix and screenshot. If you like this better please repoen i will add this fix :) 

![image](https://user-images.githubusercontent.com/12607160/94992236-32cdf300-05a6-11eb-906a-c999d85adbb5.png)

**Comment by shahednasser** [comment]
If you would like to change the font family then please suggest a better font to use for social buttons.

**Comment by Dheerajbana** [comment]
@shahednasser  currently the font family is "Syne" and then sans-serif. So best option what  did is removed Syne it automatically took sans-serif which looks very good. 
![image](https://user-images.githubusercontent.com/12607160/94992515-13d06080-05a8-11eb-8e4f-d157550fcf43.png)

**Comment by shahednasser** [comment]
I'm not a big fan of the sans-serif

**Comment by Dheerajbana** [comment]
@shahednasser fangsong looks ok to me. If it looks good to you we can update.
![image](https://user-images.githubusercontent.com/12607160/95016663-ff589a80-0671-11eb-91df-6f75c9b6ef89.png)

**Comment by shahednasser** [comment]
Still not a fan of it. It's ok I think we can leave the current font for now.
