### ISSUE TITLE
[BUTTON IDEA]: Flip Button

### ISSUE THREAD

**Issue by vsaini212223** [sButtons/sbuttons#628]
1. Name of button : Flip Button

2. Description:  The button which flips when hovered

3. Button Type (Animated, Special, etc...): Animated

4. Will you work on it?: Yes, I can work on this.

**Comment by shahednasser** [comment]
Looks good but please add it to Animated, not special.

**Comment by VishakhaAwasthi01** [comment]
Is someone working on it? or I can take this?

**Comment by shahednasser** [comment]
@VishakhaAwasthi01 yes someone is working on this
