### ISSUE TITLE
[BUTTON IDEA]: Animated gradient button

### ISSUE THREAD

**Issue by IraTeixeira** [sButtons/sbuttons#634]
**1. Name of button**: Animated gradient button

**2. Description**: The gradient animates by itself

**3. Button Type (Animated, Special, etc...)**: Animated, Gradient

**4. Will you work on it?**: Yes

**Comment by IraTeixeira** [comment]
@shahednasser , can you add hacktoberfest label, please?

**Comment by shahednasser** [comment]
@IraTeixeira we already have a button idea for this.

**Comment by IraTeixeira** [comment]
@shahednasser the idea of my button is like on this GIF. It animates without hover. Do you have this idea already? Because i didn't find
![Animated-gradient-button-pure-css](https://user-images.githubusercontent.com/56459726/95024914-64a19100-065c-11eb-99cb-62de24af532d.gif)

**Comment by shahednasser** [comment]
We have a gradient button idea to be implemented.
