### ISSUE TITLE
[BUTTON IDEA] Discord Button:

### ISSUE THREAD

**Issue by ryuzaki221** [sButtons/sbuttons#643]
**1. Name of button**: 
Discord button
**2. Description**: 
I found that discord has it's own OAuth API and we don't yet have a button for it
**3. Button Type (Animated, Special, etc...)**:
Social
**4. Will you work on it?**:
Yes

**Comment by shahednasser** [comment]
Ok you may work on it @ryuzaki221

**Comment by ryuzaki221** [comment]
#650 

Please review the changes. Thank You
