### ISSUE TITLE
Change the URL of the minified file

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#649]
Currently we are using Statically for the URL of the minified CSS file. We need to make the following changes:

- [ ] Change the CDN URL to use jsDelivr which links to `dist/sbuttons.min.css` in the repo. This change should be reflected in the README and "Get Started" page on the website.
- [ ] Change the Download URL (which is used in `assets/js/index.js`) to link to the minified file in the repo.

**Comment by zikos2** [comment]
can i start working on this?

**Comment by shahednasser** [comment]
Sure @zikos2 I will assign you.

**Comment by zikos2** [comment]
Done! can you check my PR.
