### ISSUE TITLE
Refactor code for Key Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#652]
The code in `src/components/styles/_key.less` is more of CSS code than Less code. We need to refactor it to use Less functionalities and syntax.

**Comment by shahednasser** [comment]
Sure @JoelLau I’ll assign you

**Comment by shahednasser** [comment]
Hello @JoelLau are you working on this one? This is a priority high issue so if you can't work on it please let me know to assign someone else.

Also, the file has been moved from `src/components/animated/_key.less` to `src/components/styles/_key.less`

**Comment by JoelLau** [comment]
yes! will open a pull request in a few hours. sorry for the delay
