### ISSUE TITLE
Refactor code in _diagonalBackground.less

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#654]
In `src/components/animated/_diagonalBackground.less` we have the following code:

https://github.com/sButtons/sbuttons/blob/2bc79ffc81c36ed38c8b71077a5849c7376bdcbf/src/components/animated/_diagonalBackground.less#L88-L91

it's a rule for `&:hover.white-btn`. We need to nest it in `&.white-btn` on line 74. Make the modification to the selector accordingly.

Same needs to be done for yellow button. We have to move the following code:

https://github.com/sButtons/sbuttons/blob/2bc79ffc81c36ed38c8b71077a5849c7376bdcbf/src/components/animated/_diagonalBackground.less#L92-L96

and nest it in `&.yellow-btn` on line 50

Another thing that needs to be done is place the following code in a mixin: 

```
background-image: linear-gradient(
      120deg,
      transparent 50%,
      @color 50%
    ) !important;
    color: @textColor !important;
```

and call it inside each button class with the needed color for background and text passed.

One last change is replace `#313131` with `@darkText`

**Comment by chatRG** [comment]
@shahednasser I can take this up!

**Comment by shahednasser** [comment]
Sure @chatRG
