### ISSUE TITLE
Refactor code in `_glow.less`

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#655]
In `src/components/animated/_glow.less` there are two mixins `glowBorderRule` and `glow`, then inside each button color (for example `blue-btn`), the following code is used:

```
    transition: all 0.5s ease;
    .glowBorderRule(@neonBlue);
    &:hover {
      .glow(@neonBlue);
    }
```

with `@neonBlue` replaced with the color needed for the button.

We need to create a new mixin with the above code that takes the color as a parameter, then use it accordingly throughout the file.

Also, place all mixin declarations at the top of the file.

**Comment by Hisime** [comment]
Hello. Please assign it to me.

**Comment by shahednasser** [comment]
Sure @Hisime go ahead
