### ISSUE TITLE
Refactor _ripple.less

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#657]
In `src/components/animated/_ripple.less` we have the following piece of code:

https://github.com/sButtons/sbuttons/blob/2bc79ffc81c36ed38c8b71077a5849c7376bdcbf/src/components/animated/_ripple.less#L22-L24

It should be nested inside `&:hover` on line 17 and the selector should be simplified accordingly.

**Comment by bhavika24** [comment]
Hey @shahednasser! Can I work on this?

**Comment by shahednasser** [comment]
Sure @bhavika24 I'll assign you
