### ISSUE TITLE
Refactor _snake.less

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#658]
In `src/components/animated/_snake.less` we have the following code:

https://github.com/sButtons/sbuttons/blob/2bc79ffc81c36ed38c8b71077a5849c7376bdcbf/src/components/animated/_snake.less#L54-L63

The code should be nested inside `.snake-btn` and the selector should be modified accordingly.

**Comment by paulo9mv** [comment]
Hi @shahednasser , can I do this one?
