### ISSUE TITLE
Refactor _splash.less

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#659]
In `src/components/animated/_splash.less` the code is written almost CSS like. We need it to be modified to make use of Less functionalities, mostly nesting rules where necessary.

Also replace `#000` here with `@darkText`:

https://github.com/sButtons/sbuttons/blob/2bc79ffc81c36ed38c8b71077a5849c7376bdcbf/src/components/animated/_splash.less#L41-L43

**Comment by chatRG** [comment]
I can take this up!

**Comment by shahednasser** [comment]
Sure @chatRG I'll assign you
