### ISSUE TITLE
Refactor _transparentOnHover.less

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#661]
In `src/components/animated/_transparentOnHover.less` we have two mixins `textColorChange` and `transparentOnHover`. First, change `transparentOnHover` to take two parameters: `@borderColor` and `@backgroundColor` where `@borderColor` will be used for the border color and `@backgroundColor` will be used for the background.

Then every button class color (for example, blue-btn) has the following repeated code:

```
      .textColorChange(@color);
      .transparentOnHover(@color);
```

A new mixin should be created with this code but `transparentOnHover` should be amended to receive two colors instead of one as discussed above. The mixin should take two parameters: `@color` which will be used for `textColorChange` parameter and for the backgroundColor parameter of `transparentOnHover`, and a border color which will be the `@borderColor` in `transparentOnHover`. You should then replace the piece of code above throughout the file with calling the new mixin, passing the appropriate parameters to the mixin.

Finally, place all the mixins in the file in the beginning of the file.

**Comment by Goodiec** [comment]
Please assign this to me

**Comment by shahednasser** [comment]
Assigned you

**Comment by Goodiec** [comment]
Do you have a suggestion on what the new mixin can be called?

**Comment by Deepak2417** [comment]
I am a first timer... I found it feasible to begin. Can you assign it to me?

**Comment by shahednasser** [comment]
@Goodiec you can just call it `onHover`

**Comment by Goodiec** [comment]
> @Goodiec you can just call it `onHover`

Ok
