### ISSUE TITLE
Gradient Button

### ISSUE THREAD

**Issue by yashvarshney003** [sButtons/sbuttons#669]
**1. Name of button**: 

**2. Description**: 

**3. Button Type (Animated, Special, etc...)**:

**4. Will you work on it?**:

**Comment by Nanak360** [comment]
I'll work on it.

**Comment by yashvarshney003** [comment]
I want to work on it.

**Comment by shahednasser** [comment]
Hi @yashvarshney003 we already have a gradient button idea in progress. Thank you.
