### ISSUE TITLE
refactor _appstore.less

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#673]
In `src/components/icon/_appstore.less` both `&.applestore` and `&.playstore` have a lot of similar properties and they should be moved out to their parents. Here are the properties: 

https://github.com/sButtons/sbuttons/blob/5198b8872a5d1541df8deab0990c5d35a3abe010/src/components/icon/_appstore.less#L34-L35

https://github.com/sButtons/sbuttons/blob/5198b8872a5d1541df8deab0990c5d35a3abe010/src/components/icon/_appstore.less#L37-L38

In this one everything but content:
https://github.com/sButtons/sbuttons/blob/5198b8872a5d1541df8deab0990c5d35a3abe010/src/components/icon/_appstore.less#L42-L53

Place these properties in their immediate parent appropriately.

**Comment by SamD97** [comment]
Can I take this up?

**Comment by shahednasser** [comment]
Sure @SamD97

**Comment by SamD97** [comment]
> In this one everything but content:
> 
> https://github.com/sButtons/sbuttons/blob/5198b8872a5d1541df8deab0990c5d35a3abe010/src/components/icon/_appstore.less#L42-L53
> 

In the `after` pseudo-class the `left` property of `&.applestore` and `&.playstore` are different, `100px` and `87px` respectively. Is this a discrepancy and needs to be changed to the same value or the `left` property is supposed to be moved out to the parent?

`left` also causes the following on `.block-btn`
![image](https://user-images.githubusercontent.com/9783888/95115652-73bf3680-0763-11eb-93a1-8e4a1d1ebda2.png)

Please let me know.

Thank you.
