### ISSUE TITLE
[BUTTON IDEA]:

### ISSUE THREAD

**Issue by printf-ana** [sButtons/sbuttons#676]
1. Name of button: Jump Social Medias Button

2. Description: It is a serie of 5 buttons, when user pass the mouse in, they kind of a jump in layers.

3. Button Type: Animated

4. Will you work on it?: Yes, i made them in a CSS project, i have the code with me and i like to start contributing with this buttons. =)

**Comment by shahednasser** [comment]
I'm not sure how that sounds like but you can submit a PR and we'll judge based on how it looks.
