### ISSUE TITLE
[BUTTON IDEA]:User Account Button 

### ISSUE THREAD

**Issue by wisetok12680** [sButtons/sbuttons#685]
**1. Name of button**: User-circle Button

**2. Description**: A basic button/icon to take the user to their account page.

**3. Button Type (Animated, Special, etc...)**:Icon

**4. Will you work on it?**:Yes I'd like to work on it.

Reference - https://fontawesome.com/v4.7.0/icon/user-circle

**Comment by shahednasser** [comment]
Hello @wisetok12680 thank you for the idea but we are currently not accepting icon ideas with no original concept as we are working on a change in a core feature regarding normal icon buttons.
