### ISSUE TITLE
Fix for settings button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#689]
Remove `position: absolute` on `.setting-btn:before` in `src/components/icon/_setting.less`

**Comment by erdemuslu** [comment]
I'm working on it.

**Comment by arkumari2000** [comment]
Is this issue open? And only what you said is to implement?
Can I work on this?

**Comment by shahednasser** [comment]
Hi @arkumari2000 yes that's all you have to do with the addition of running `npm run compile` afterwards and committing the changes.

I'll assign you.

**Comment by arkumari2000** [comment]
Okay, Thank you
