### ISSUE TITLE
Button UX: Make toggle button design work for checkboxes as well

### ISSUE THREAD

**Issue by adsingh14** [sButtons/sbuttons#690]
Add enhancements to the Toggle Button by ensuring the design can work well on checkboxes just by adding the classes to it.
 
![image](https://user-images.githubusercontent.com/35252877/95182805-b6742380-07e2-11eb-80cd-e13cbc1bae35.png)

**Comment by shahednasser** [comment]
Hello @adsingh14 I appreciate your input but generally, we're not accepting any idea that has no use case to it. The reason I accepted this button is just that it has a nice addition to the project. 

Another way to approach this issue is if we can make this design applicable to checkboxes as well. This could be an enhancement on the side. 

I'll change the issue title and description accordingly. Thank you.

**Comment by adsingh14** [comment]
It would be great if current toggle button will replaced with **checkbox** type. It should be a single element and used with colors classes also.

**Comment by gokul112** [comment]
Hi @shahednasser ,
shall i work on this?

**Comment by shahednasser** [comment]
@adsingh14 I understand but our main focus is keeping the website consistent. We could add a note about it in "Get Started" page.

**Comment by shahednasser** [comment]
Sure @gokul112 I'll assign you.

**Comment by shahednasser** [comment]
Hi @gokul112 any update on this?

**Comment by shahednasser** [comment]
Unassigning @gokul112 to give other contributors a chance to work on this

**Comment by vinbaluyot** [comment]
@shahednasser Can I work on this one, too? Already tried it on my local but just haven't figured out how to add the html in the examples.  [sbuttons-toggle-button.zip](https://github.com/sButtons/sbuttons/files/5390203/sbuttons-toggle-button.zip)


![image](https://user-images.githubusercontent.com/46494300/96234250-ea222b00-0fe4-11eb-8c4a-409686280c7e.png)

**Comment by shahednasser** [comment]
@vinbaluyot for now we don't want to add any examples for it, just to make sure the necessary changes for it to work as a checkbox. We might later add it in the documentation.

I'll assign you.

**Comment by shahednasser** [comment]
Any update on this @vinbaluyot ?

**Comment by vinbaluyot** [comment]
> Any update on this @vinbaluyot ?

Hi @shahednasser sorry got too busy. I just made a [PR](https://github.com/sButtons/sbuttons/pull/960#issue-510364467) for this one.
