### ISSUE TITLE
Add link to logo in navbar

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#691]
Add link to homepage "/" to logo in the navbar

**Comment by akankshast** [comment]
I would link to contribute to this issue, please assign it to me.
Regards,
Akanksha

**Comment by caspero-62** [comment]
Hey, I would like to take this if it's still available

**Comment by shahednasser** [comment]
Hello @akankshast you can go ahead!

**Comment by Akanksha7-art** [comment]
Can I contribute?

**Comment by shahednasser** [comment]
Hi @Akanksha7-art someone is already working on this.

**Comment by Akanksha7-art** [comment]
ok no issue
