### ISSUE TITLE
Day limit for an assignee.

### ISSUE THREAD

**Issue by adsingh14** [sButtons/sbuttons#694]
**1 - Describe the bug**
Some issues have been created and assigned but not completed in 4-5 days. That would create a headache for the maintainer as well as for the new comers.

**2 - Expected behavior of what should have happened (if applicable)**
 It would be better if the assignee will not take more than 2 days for button for a single button. In case if the assignee won't respond/submit-a-PR, then the maintainer will pass the responsibility to other in-queue coders.

**3 - Screenshots (if applicable)**

**4 - Additional notes**
Don't get assigned into rush. Think before getting assigned.

**Comment by shahednasser** [comment]
Hi @adsingh14 we're currently keeping up to date with label "Priority: High" to make sure it doesn't take too long. "Priority Medium" we give them some additional time. As for "Priority Low", it will be reported by stale action that will label issues that have been stale for more than 7 days with "stale-issue" and will report it to me. I will then follow up with the contributor and take the necessary action regarding reassigning the issue.

Thank you!
