### ISSUE TITLE
[BUTTON IDEA]: Half Framed Button

### ISSUE THREAD

**Issue by 0-harshit-0** [sButtons/sbuttons#696]
**1. Name of button**: half framed button

**2. Description**: make a frame around button on hover

**3. Button Type (Animated, Special, etc...)**: animation

**4. Will you work on it?**: yes

![learnmorebutton](https://user-images.githubusercontent.com/59227793/95190820-7b2b2200-07ed-11eb-984e-9c6f05c5b08c.png)

**Comment by shahednasser** [comment]
Looks good. Add it under "Animated" instead of hover though.

**Comment by 0-harshit-0** [comment]
I have query (I'm new in opensource),
does this issue comes under hacktoberfest ?

**Comment by shahednasser** [comment]
Yes the PR counts in hacktoberfest if it gets merged or if it gets the "hacktoberfest-accepted" label. For more info please check the note in the README

**Comment by shahednasser** [comment]
Hi @0-harshit-0 any update on this?
