### ISSUE TITLE
Create a new button type

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#698]
Some buttons under animated don't fall under that category but don't have a better place to add them, same for Special. We need a new category: Button Styles

The following tasks are required:
- [ ] Create a new file `_button_styles.less` in `src/components/`
- [ ] Add a new button type in Index page in `assets/js/buttons-examples.js`
- [ ] Move the following buttons from animated to button styles:
   - Click
   - Glow
   - Key
   - Dashed (currently it is a separate type. It should become a subtype)
   - Disabled (same as Dashed)
   - Outline (same as Dashed)
   - Glossy
   - Rounded Bottom
   - Rounded Top
   - Rounded Diagonal (both types)

Moving the buttons include:
- Moving the file to `src/components/button_styles/` directory (which you need to create)
- Import the file in the newly created `_button_styles.less`
- Moving it in `assets/js/buttons-examples.js` to be the child element of button styles.

That's all that is required. No design changes need to be made. This issue also requires you to have some knowledge in the structure of this repo so please read the [contribution guidelines](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md) ahead of working on it and if you need any assistance I will provide it.

**Comment by SamD97** [comment]
Can I take this up?

**Comment by swapnalshahil** [comment]
Move the following buttons from animated to button styles:
what does it mean?

**Comment by shahednasser** [comment]
Hi @SamD97 yes you can. This may be a little complicated so do let me know if you need any help.

**Comment by SamD97** [comment]
I think I can do it but sure if need be I will let you know @shahednasser

**Comment by SamD97** [comment]
Hey @shahednasser, I am about to make the commit along with the pull request, however I think there is a slight inconsistency. The style of the `disabled-btn` is defined in the `src/components/_basic.less` should this be moved to the new file `_disabled-btn.less` within the new folder?

**Comment by SamD97** [comment]
Hey @shahednasser, I am about to make the commit along with the pull request, however I think there is a slight inconsistency. The style of the `disabled-btn` is defined in the `src/components/_basic.less` should this be moved to the new file `_disabled-btn.less` within the new folder?
