### ISSUE TITLE
Change class of Download button in header

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#699]
Changes classes of Download button in header to use "Transparent On Hover" button. There are some styling applied to it in `assets/css/index.css` with the class names currently used, you should keep anything necessary (for example font size or font family) but remove all the ones that won't be necessary anymore. Make sure to change the selectors to the new selectors appropriately.

**Comment by harjotscs** [comment]
i would like to work on this can you give a brief

**Comment by shahednasser** [comment]
Hi @harjotscs I think the description is clear. Maybe you should look over the website, repo and [contributing guidelines](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md) before working on this.

**Comment by Goodiec** [comment]
Please assign this to me. @harjotscs is this alright with you?

**Comment by harjotscs** [comment]
Hi @Goodiec I am working on it, If you want to do it, I'll leave it

**Comment by shahednasser** [comment]
@harjotscs you can have a shot at it. I will assign you.

**Comment by Goodiec** [comment]
@harjotscs that's alright, you can work on it.

**Comment by mePallavi** [comment]
@shahednasser can I work on this issue?
