### ISSUE TITLE
[BUTTON IDEA]: Handwritten button

### ISSUE THREAD

**Issue by IngoA-1848613** [sButtons/sbuttons#704]
**1. Name of button**: Handwritten button

**2. Description**: A button that looks handwritten (it's text and it's border)

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**: Yes

![image](https://user-images.githubusercontent.com/42770346/95233701-89853800-0805-11eb-86f1-cdbb4ab3ac9b.png)

**Comment by arnabuchiha** [comment]
Can I work on this?

**Comment by IngoA-1848613** [comment]
> Can I work on this?
> 
> 

Sorry, I was already gonna work on this myself 😉!

**Comment by shahednasser** [comment]
Great idea @IngoA-1848613 you may go ahead.
