### ISSUE TITLE
Compile action for pull requests

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#708]
Add an action on pull requests **only** that run `npm run compile` on changes to anything in the src directory. This would make contributing more efficient as so many people forget to compile their work on PRs and time gets wasted in review to request the compilation.

**Comment by varunks99** [comment]
@shahednasser, I would like to take this up.

**Comment by debapriyo1999** [comment]
@shahednasser ,I would like to take this up.

**Comment by shahednasser** [comment]
Hi @varunks99 great I will assign you!
