### ISSUE TITLE
[BUTTON IDEA]: Glue/Liquid animated button 

### ISSUE THREAD

**Issue by adarshtodi** [sButtons/sbuttons#710]
**1. Name of button**: Glue/Liquid animated button 
**2. Description**: A simple animated button with sticky glue effect while hovering it.

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: yes (if anyone would to do then i am okay with it)

**Comment by shahednasser** [comment]
Assigned you.

**Comment by shahednasser** [comment]
Hello @adarshtodi any update on this?

**Comment by adarshtodi** [comment]
Update is that, that I have created this earlier using css, but I have no idea how to work on less. 

I can attach the CSS files so that anyone else can work or you have to delete the issue :/

**Comment by shahednasser** [comment]
Thank you @adarshtodi . I'll assign this to give other contributors a chance to work on it
