### ISSUE TITLE
[BUTTON IDEA]: Neumorphic Design Buttons

### ISSUE THREAD

**Issue by crew-guy** [sButtons/sbuttons#726]
**1. Name of button**:  Neumorphic Design Button

**2. Description**:  A different kind of styling using **box-shadows** to create a button with a really comfortable and cool looking UI.

**3. Button Type (Animated, Special, etc...)**: Neumorphism

**4. Will you work on it?**: Yes. I will be contributing everything in this issue right from basic rounded buttons, radio buttons, icon buttons to toggle buttons, dropdown buttons and more. I will finish all PRs of this issue within this week.

![Neumorphic UI](https://user-images.githubusercontent.com/69717009/95420464-1b518a00-0959-11eb-8cbe-b3c30718c552.png)

**Comment by crew-guy** [comment]
I'll start working right away and have some test examples ready for you perusal before I work with main code base ^_^

**Comment by shahednasser** [comment]
@crew-guy thank you but someone is already working on this button style.

**Comment by crew-guy** [comment]
Ok no problem ! @shahednasser 
I'll look for other design ideas.
