### ISSUE TITLE
[BUTTON IDEA]: 3D Layered Icon Button

### ISSUE THREAD

**Issue by crew-guy** [sButtons/sbuttons#729]
**1. Name of button**: 3D Layered Icon Button

**2. Description**: Initially skewed button. On hover, we see a decreasing transparency 3D stack below button

**3. Button Type (Animated, Special, etc...)**: Hover button

**4. Will you work on it?**: Yes. I'll try adding some fill-in or ripple effect to complement the effect even better. I also want to implement different style for dark and light theme for buttons of different platforms like Google, Facebook, Instagram, Snapchat, LinkedIn, Github and more.

---

![maxresdefault](https://user-images.githubusercontent.com/69717009/95454186-bb270c00-0989-11eb-9c8c-69041b1dcad2.jpg)

**Comment by shahednasser** [comment]
@crew-guy someone tried implementing this before, but it didn't look so good. You may work on it and I'll see how it looks in the end.

**Comment by crew-guy** [comment]
> @crew-guy someone tried implementing this before, but it didn't look so good. You may work on it and I'll see how it looks in the end.

You were so SO right about this Ma'am. It took me forever to implement just a rudimentary version of this (check out pull request #746 ) 😅😁

But it was really fun ! I look forward to coming up with and implementing more such design ideas !

**Comment by shahednasser** [comment]
You did a great job at it @crew-guy , I just need you to make the changes mentioned in the PR and I'm sure it will be a part of the repo soon! Thank you for contributing and trying hard.

**Comment by crew-guy** [comment]
Hey !! I have completed both tasks assigned to me. Check out PR - #764 and #763  
I gotta say, refactoring my own code from icon buttons to button styles and that too whilst minimizing CSS lines has gotta be the one of the coolest CSS problems I've had to crack
I honestly had no clue about PRs and branches but thanks to these assignments, I have a fairly good idea of how to work around them.
You're a great mentor Ma'am and I really enjoy working with you ! 🙏🏻😄

**Comment by shahednasser** [comment]
@crew-guy thank you so much and I hope this repository keeps helping you learn new things! I'll check your PRs soon.

**Comment by crew-guy** [comment]
Thanks !!🙏🏻
