### ISSUE TITLE
[BUTTON IDEA]: Extra-Small, Small, Large and Extra-Large Buttons

### ISSUE THREAD

**Issue by RodolfoNei** [sButtons/sbuttons#734]
**1. Name of button**: x-small-btn, small-btn, large-btn, x-large-btn

**2. Description**: Four different size options for buttons, using relative length units

**3. Button Type (Animated, Special, etc...)**: Styles

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Can we just add the extra small and extra large?

**Comment by RodolfoNei** [comment]
Sure, no problem!
