### ISSUE TITLE
icons missing on screen resize(for mobile view)

### ISSUE THREAD

**Issue by mayankmohak** [sButtons/sbuttons#735]
**The icons like _Toogle screen_, _download_ and  _git hub link_ is missing**
![main](https://user-images.githubusercontent.com/63801800/95474072-57f5a380-09a2-11eb-826b-762940d3e660.jpg)

**On mobile view**
![missing](https://user-images.githubusercontent.com/63801800/95474192-76f43580-09a2-11eb-868b-da623b909108.jpg)

**Expected behavior of what should have happened (if applicable)**
![expected](https://user-images.githubusercontent.com/63801800/95474382-a9059780-09a2-11eb-8ff7-2bd484356f52.jpg)

**Comment by mayankmohak** [comment]
I have made successful changes locally shall i make a PR.

**Comment by shahednasser** [comment]
Someone was working on a similar issue but they're taking a while. You may submit a PR.

**Comment by mayankmohak** [comment]
I have made a PR now its working well i have also added SC please have a look.
