### ISSUE TITLE
Add an action on pull request and new issue for an automatic reply

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#738]
As the Members of this organization and I might take a little while to reply to new issues or PRs, we need an action to greet the users once they create an issue or submits a PR, and tell them that we will be looking at their issue/PR soon.

**Comment by sdesani** [comment]
@shahednasser if you don't mind, I would like to look into this. Can you assign it to me ?

**Comment by shahednasser** [comment]
Sure @sdesani

**Comment by sdesani** [comment]
Quick question. Does it need to be only for first time a user creates a PR on this repo or do we want this greeting for every PR even if its from same user ?

**Comment by shahednasser** [comment]
@sdesani it should be for all PRs/issues, regardless of who the user is. Just a simple greeting saying we will look into it shortly.

**Comment by Soumi150** [comment]
I would like to work on this. Please assign me.

**Comment by mayankmohak** [comment]
It is taking too long for him to work upon it can i have a try on it. @shahednasser  and @sdesani

**Comment by shahednasser** [comment]
Sure @mayankmohak I'll assign you.

**Comment by mayankmohak** [comment]
I am looking to use this : https://github.com/marketplace/actions/mast-joke-mara
please have a look weather it will be ok or please suggest some actions.

**Comment by shahednasser** [comment]
@mayankmohak sure I don't mind

**Comment by mayankmohak** [comment]
hlo @shahednasser  please make a branch for me ton test this action.

**Comment by shahednasser** [comment]
@mayankmohak I have created the branch "test-welcome-action" to test it. You may submit a pull request there.

**Comment by mayankmohak** [comment]
I have created a PR please have a review.

**Comment by Soumi150** [comment]
I would like to work on this, if it's still open. Can I use a different action ?

**Comment by mayankmohak** [comment]
The pr is made on test-welcome action branch it is late for maintainer to review and merge.

@shahednasser please merge the branch.
