### ISSUE TITLE
Remove unnecessary files

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#740]
There are unnecessary files in the repo that need to be removed:

- README_BACKUP_6160.md
- README_BASE_6160.md
- README_LOCAL_6160.md
- README_REMOTE_6160.md
- .README.md.swp

**Comment by crew-guy** [comment]
Can you please assign this to me ?

**Comment by shahednasser** [comment]
Hi @crew-guy since I assigned you to another issue let's give other contributors a chance too!

**Comment by dkochetkov** [comment]
Can you assign it to me?

**Comment by shahednasser** [comment]
@dkochetkov you may work on it.

**Comment by PriyanshTri** [comment]
can you assign this to me?

**Comment by shahednasser** [comment]
@PriyanshTri someone is assigned to this.
