### ISSUE TITLE
Make changes to CONTRIBUTING.md

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#741]
In CONTRIBUTING.md under Instructions item number 3, we've added the structure of the button to be added to `assets/js/buttons-examples.js`. Currently `shouldHaveBlockType` is the last item. We need to move `variations` and `children` to be at the button of the list.

**Comment by crew-guy** [comment]
Hi ! Can you please assign this to me ?

**Comment by shahednasser** [comment]
Hi @crew-guy since I assigned you to another issue let's give other contributors a chance too!

**Comment by shubh710** [comment]
Hi @shahednasser 
I would like to work on this.

**Comment by shahednasser** [comment]
Sure @shubh710 go ahead

**Comment by shubh710** [comment]
Hi @shahednasser.
just to make sure that I understood this correctly.
only order of display properties in CONTRIBUTING.md needs to be changed.

**Comment by shahednasser** [comment]
yes just change the order in `CONTRIBUTING.md`

**Comment by shubh710** [comment]
Thanks for clarification @shahednasser 
Just submitted the PR #753.
Please check and merge.
Thanks.
