### ISSUE TITLE
Add a link to the NPM package

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#742]
Add the link to the npm package ([https://www.npmjs.com/package/sbuttons](https://www.npmjs.com/package/sbuttons)) in README and Get Started page. The link should be under "NPM" in Installation, added on the word "NPM".

For example, in README it's" You can install sButtons using NPM:"

**Comment by crew-guy** [comment]
Can I please be assigned to this ?

**Comment by shahednasser** [comment]
Hi @crew-guy sure I'll assign you

**Comment by Caleb335** [comment]
Hi @shahednasser, is this still open?

If yes, I'd love to work on it

**Comment by shahednasser** [comment]
Hi @Caleb335 someone is working on this

**Comment by crew-guy** [comment]
> Hi @Caleb335 someone is working on this

Isn't this completed ?

**Comment by shahednasser** [comment]
@crew-guy no please review my comment on #782

**Comment by crew-guy** [comment]
Done. Kindly check out PR #826
