### ISSUE TITLE
[BUTTON IDEA]: Add float and pulse animation to Stack Design Buttons

### ISSUE THREAD

**Issue by crew-guy** [sButtons/sbuttons#747]
**1. Name of button**:  Float and Pulse Stack Button

**2. Description**: Basically, in the stack design buttons that I created in issue #729 (pull request #746), I will be adding a pulsing animation on lower layer and floating animation on upper layer

**3. Button Type (Animated, Special, etc...)**: Stack Button

**4. Will you work on it?**: Yes. I already feel comfortable with Stack Buttons so it will be really cool to improve upon my designs for better user experience

**Comment by shahednasser** [comment]
@crew-guy sounds great. You can do it while working on stack buttons. I'll close this issue.
