### ISSUE TITLE
Add active state for star button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#750]
Currently the star icon button on `:active` gets colored yellow, however it is more convenient to also add an active state for the button (a new class `.active`) where the color of the star will be yellow. It should also have a nice transition between the inactive and active state. It shouldn't be displayed on the website, but if someone adds the class `.active` to the button or removes it, the transition should look nice.

**Comment by crew-guy** [comment]
Can I do it please ? I just have 1 small other pending issue

**Comment by shahednasser** [comment]
@crew-guy I really appreciate you contributing to this repository but I can't give you too many issues to work on at the same time. Once you finish at least one of them you can then get assigned to a new one. Thank you!

**Comment by pontakornth** [comment]
@shahednasser I already forked the repository but I forget to add comment here. Could you assign this to me?

**Comment by shahednasser** [comment]
sure @pontakornth but please follow the other instructions I gave you as well.

**Comment by crew-guy** [comment]
> @crew-guy I really appreciate you contributing to this repository but I can't give you too many issues to work on at the same time. Once you finish at least one of them you can then get assigned to a new one. Thank you!

Yaya cool ! Guess I am taking wayy too much work to properly process and finish it all 😂✌🏻

**Comment by PriyanshTri** [comment]
can you assign this to me? thanks

**Comment by pontakornth** [comment]
> sure @pontakornth but please follow the other instructions I gave you as well.

Done. The check is still failed and I have no idea why.

**Comment by maityankan10** [comment]
i would like to contribute
