### ISSUE TITLE
Improve bounce animation

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#751]
The bounce button's animation needs improvement. You can refer to [this](https://codepen.io/fershopls/pen/LjMwZb) for an example, but you don't have to follow it exactly. It also should only happen on hover.

**Comment by shubh710** [comment]
Hi @shahednasser I would like to work on this.
Please assign this to me.

**Comment by shahednasser** [comment]
sure @shubh710 go ahead

**Comment by shubh710** [comment]
Hi @shahednasser 
I have submitted PR #758.
However I had below query.
should dist/sbuttons.css file also be a part of commit and PR?
Please let me know so that I can update that as well.
Thanks

**Comment by PriyanshTri** [comment]
assign this to me. thanks

**Comment by shahednasser** [comment]
> Hi @shahednasser
> I have submitted PR #758 previously have submitted updated PR #762 .
> However I had below query.
> should dist/sbuttons.css file also be a part of commit and PR?
> Please let me know so that I can update that as well.
> Thanks

If your repository is up to date it's not necessary anymore, as we have added an action that compiles your work when you push new commits.
