### ISSUE TITLE
Add animated class to all Animated buttons

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#752]
We need to add an animated class to all animated buttons. The purpose of this is that animated button's animation right now only happens on hover. In case someone needs to make a button continuously animated, we need to add `.animated` class to each animated button to make sure the animation runs indefinitely. 

Make sure when you add the `animated` class to the button, you nest it inside the button name. This will make sure no overlapping between buttons would happen. I suggest making a mixin in `src/components/_animated.less` that takes the name of the animation as a parameter and any necessary parameters (maybe animation duration, etc...)

If an animated button does not use an animation and just use a transformation or transition, you can just put the transformation/transition inside the active state

**Comment by Caleb335** [comment]
I'd love to work on this @shahednasser.

But can you please explain on how I'd go about creating the mixing for animation? I'm new to it

**Comment by shahednasser** [comment]
Mixins in Less are just like functions. Basically if you have repeated properties for different classes, you can create a mixin with those properties and then call them from inside the class. That way you don't have to repeat your code. Also, you can pass it parameters if there are minor changes for each class. You can read and learn more about [mixins](http://lesscss.org/features/#mixins-feature-mixins-as-functions-feature) and you can check the code in this repo as a lot of buttons use mixins. (for example, check `src/components/styles/_key.less`). It's not hard to do.

Please confirm to me if you can do it or not.

**Comment by Caleb335** [comment]
> Mixins in Less are just like functions. Basically if you have repeated properties for different classes, you can create a mixin with those properties and then call them from inside the class. That way you don't have to repeat your code. Also, you can pass it parameters if there are minor changes for each class. You can read and learn more about [mixins](http://lesscss.org/features/#mixins-feature-mixins-as-functions-feature) and you can check the code in this repo as a lot of buttons use mixins. (for example, check `src/components/styles/_key.less`). It's not hard to do.
> 
> Please confirm to me if you can do it or not.

Yes, please assign me.

Thanks

**Comment by shahednasser** [comment]
Great I assigned you

**Comment by shahednasser** [comment]
This issue now is unassigned and can be claimed

**Comment by shubh710** [comment]
Hi @shahednasser,
I Would like to work on this issue.
Please assign this to me.

**Comment by shahednasser** [comment]
sure @shubh710

**Comment by shubh710** [comment]
Hi @shahednasser 
Sorry, but I won't be able to work until Saturday hence if any one can work on it meanwhile please assign them.
Thanks a lot.

**Comment by shahednasser** [comment]
Alright @shubh710 I'll unassign this. You can claim it again if it is not assigned before then.

**Comment by shahednasser** [comment]
Sure @adunola142

**Comment by adunola142** [comment]
pls, assigned this back to @shahednasser ....

i might not be able to meet up

thank you

**Comment by shubh710** [comment]
Hi @shahednasser 
i would like to take up this enhancement.

**Comment by shubh710** [comment]
@shahednasser 

Please address below queries.
1) Where you have said 
> _"We need to add an animated class to all animated buttons. The purpose of this is that animated button's animation right now only happens on hover. In case someone needs to make a button continuously animated, we need to add .animated class to each animated button to make sure the animation runs indefinitely."_

Does this mean, adding a class "animated" in buttons-examples.js > buttons > type:"anmated" > children.
e.g. instead of 
`children: [
        {
          type: "aura-pulse",
          label: "Aura Pulse",
          classes: "aurapulse-btn",
        },`
we should have
`children: [
        {
          type: "aura-pulse",
          label: "Aura Pulse",
          classes: "animated aurapulse-btn",
        },`
For all children?

2) You have mentioned about adding mixin.
Does that mean we should have a mixin in _animated.less something like,
`.animated(@name,@duration,@iteration) { 
    animation-name: @name; 
    animation-duration: @duration; 
    animation-iteration-count: @iteration;
}`
and wherever we are using animation,
instead of 
`animation-name: bouncy;
    animation-duration: 2s;
    animation-iteration-count: infinite;` 
we should write 
`.animated(bouncy, 2s, infinite);`

**Comment by shahednasser** [comment]
Hi @shubh710 . Regarding your queries:

1. No we don't want to include this in the examples. We want to add the ability to make the button animated at all times, not just on hover. We want this to be done just by adding the class `.animated` to the button. We will then include this in the documentation for the users to know about it.
2. yes that's what I meant. However, I think some animations might require additional fields so please do anything that you find necessary.

I'll assign you to this issue.

**Comment by shahednasser** [comment]
Hi @shubh710 are you still working on this?

**Comment by shubh710** [comment]
Sorry @shahednasser .
I started but will not be able to complete any time soon.
Sorry once again. :(

**Comment by shahednasser** [comment]
No problem @shubh710 ! Thank you for letting me know.
