### ISSUE TITLE
[BUTTON IDEA]: Hamburger Menu Button

### ISSUE THREAD

**Issue by senguyen1011** [sButtons/sbuttons#765]
**1. Name of button**: Hamburger Menu Button

**2. Description**: Hamburger menu buttons/icons are typically three horizontal lines that toggle the appearance of an off-screen menu. The humburger menu button when toggled will change to a different icon, such as an 'X' to indicate clicking it again will close the menu and reset the button.

**3. Button Type (Animated, Special, etc...)**: Icon Buttons

**4. Will you work on it?**: Yes

![image](https://user-images.githubusercontent.com/52718953/95587188-bb69ea80-0a0f-11eb-8b4b-c6dda77a9ac4.png)

**Comment by senguyen1011** [comment]
I'd like to work on this for Hacktoberfest, and possibly add animated variants of the hamburger icon. Please let me know if I didn't create this issue correctly.

**Comment by shahednasser** [comment]
We're currently not adding icon buttons but if you're gonna add it animated as you say (change between hamburger and X) then you may. But here are a few notes:

All buttons are implemented without JS, only CSS. So you need to do things:

1. Create the hamburger button which is the original state.
2. Add an `.active` state on that button that makes the hamburger button an X button. The transition between them needs to be clean.
3. Display both states on the website but without the actual toggling as it will require JS and we're not doing that for now.

Let me know if you can work on it. I can help you with anything you need as well.

**Comment by senguyen1011** [comment]
Yes, I can create the button and the active state. If you create an issue, please assign it to me, thank you.
