### ISSUE TITLE
[BUTTON IDEA]: leather buttons

### ISSUE THREAD

**Issue by laurachristensen1214** [sButtons/sbuttons#766]
**1. Name of button**: Western Themed buttons

**2. Description**: These buttons will resemble a leather or denim patch and on hover will appear as embossed leather

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: Yes please!

**Comment by shahednasser** [comment]
I'm not sure how it will look like to be honest but you can start working on it.

**Comment by laurachristensen1214** [comment]
Thank you!

**Comment by shahednasser** [comment]
Hi @laurachristensen1214 any update on this?
