### ISSUE TITLE
[BUTTON IDEA]: Can Add a button which has 100% width

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#768]
**1. Name of button**: 100% width button

**2. Description**: As many time we need that type of button which takes full width of the screen or the parent element

**3. Button Type (Animated, Special, etc...)**:

**4. Will you work on it?**:yes

**Comment by developerzone** [comment]
Can I takeup this ?

**Comment by shahednasser** [comment]
We already have this button it's the Block Button. Thank you.
