### ISSUE TITLE
Store button and typo in sbtn class.

### ISSUE THREAD

**Issue by adsingh14** [sButtons/sbuttons#775]
**1 - Describe the bug**
I'm sharing two bugs here:
- Wrong alignment of App Store block buttons.
- Extra period in starting of `.rounded` and `.block` button classes.

**2 - Expected behavior of what should have happened (if applicable)**
Both can be done in a single PR.

**3 - Screenshots (if applicable)**
![Screenshot_20201010-152642~2.png](https://user-images.githubusercontent.com/35252877/95652279-8c39a300-0b0d-11eb-8c82-7e94712e5cef.png)

**4 - Additional notes**
It's just a fix and tested on all browsers.

**Comment by isonnymichael** [comment]
Ok, tell me if you want to work on this, I will asign you.

**Comment by shahednasser** [comment]
Please let @isonnymichael know if you will work on it. Also, provide a simple fix as in a release soon this button will be removed so it's not very important.

**Comment by harsh1868** [comment]
@shahednasser  can i do this ?

**Comment by isonnymichael** [comment]
> @shahednasser can i do this ?

sure, I will assign you
