### ISSUE TITLE
[BUTTON IDEA]:CURL BOTTOM CORNERS ON HOVER

### ISSUE THREAD

**Issue by wisetok12680** [sButtons/sbuttons#786]
**1. Name of button**: CURL BOTTOM CORNERS ON HOVER

**2. Description**: Curls the bottom corners on hover 

**3. Button Type (Animated, Special, etc...)**:Animated 

**4. Will you work on it?**:Yes of course

**Comment by shahednasser** [comment]
@wisetok12680 I'm not sure that's a good idea to be honest. Can you show me an example of it?

**Comment by wisetok12680** [comment]
I had something like [this](https://codepen.io/wisetok12680/pen/ZEObEEq) in my mind.
Its okay I wasn't confident about it either. I would work for something similar.

**Comment by shahednasser** [comment]
That doesn't look bad. You can go ahead and work on it.

**Comment by wisetok12680** [comment]
Hey there,
I don't understand why you closed the issue. I was about make PR as the button is ready.

**Comment by shahednasser** [comment]
@wisetok12680 I closed the issue since I didn't get any update from you on it and the button idea isn't essential to keep it in issues, but if you would like to submit a PR you still can.
