### ISSUE TITLE
[BUTTON IDEA]: Menu Button

### ISSUE THREAD

**Issue by NicolaLC** [sButtons/sbuttons#788]
**1. Name of button**: 

Menu Button - a first-level button with a sub-menu opening on click.

**2. Description**: 

This button idea is similar to [material menu button](https://material.angular.io/components/menu/overview). The goal of this button is to handle different click options (like a menu).

**3. Button Type (Animated, Special, etc...)**:

Special Button.

**4. Will you work on it?**:

Yes, I would like to as my first PR for hacktoberfest 2020.

**Comment by shahednasser** [comment]
Thank you @NicolaLC but this button requires Javascript, and our project is CSS only.
