### ISSUE TITLE
Enhancement in Stack Button implementation

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#803]
In `.stack-btn` the text (for example "Button") is set in `:before` in `content` property which is not convenient. We need the text inside the `<button>` element to be used, while maintaining the design of the button.

**Comment by vinbaluyot** [comment]
Hi @shahednasser first time contributor here and I'd like to work on this one. :)

**Comment by shahednasser** [comment]
I assigned you @vinbaluyot

**Comment by vinbaluyot** [comment]
I did `git fetch upstream` then `git merge upstream/master` before doing PR and now [my PR](https://github.com/sButtons/sbuttons/pull/816) is not showing up here. :(

**Comment by isonnymichael** [comment]
> I did `git fetch upstream` then `git merge upstream/master` before doing PR and now [my PR](https://github.com/sButtons/sbuttons/pull/816) is not showing up here. :(

check your forked project, you can make PR there

**Comment by ShashankArunkumar** [comment]
Hey, I'm a beginner, I would like to work on this one!

**Comment by shahednasser** [comment]
@ShashankArunkumar someone is working on this.
