### ISSUE TITLE
Move all variables to _variables.less

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#804]
All variables in less files in src directory should be added in `src/_variables.less` recursively. When moving variables, append the name of the button to the beginning of the variable to not cause overlap between buttons. Also, change the variable names to camel case. For example, `@outline-width` in `src/components/special/_retro.less` should become `@retroOutlineWidth`. Make sure to change the name of the button where it is used. Also, add comments to the file like so:

```
/* BEGIN VARIABLES IN special/_retro.less */
...
/* END VARIABLES IN special/_retro.less */
```

where `special/_retro.less` should be the name of the file the variable(s) is used in. This should be added to all variables, the ones that are already in the file and the variables that you move to the file, with the exception of the base colors. To make it simpler, starting from `@neonGreen`. To the base colors before `@neonGreen` make the comments "BEGIN BASE COLORS" and "END BASE COLORS"

**Comment by android-lewis** [comment]
Can I take a crack at this one?

**Comment by shahednasser** [comment]
Sure @android-lewis i'll assign you
