### ISSUE TITLE
Liquid button performance.

### ISSUE THREAD

**Issue by adsingh14** [sButtons/sbuttons#807]
**1 - Describe the bug** Liquid button performance needs to be fix. It slows down the website when it's in the viewport. That usually happens because of multiple animation runs at the same time while rendering.

**2 - Expected behavior of what should have happened (if applicable)** It should be placed in Special category or keep one or two color classes in display and hide others.

**3 - Screenshots (if applicable)**

**4 - Additional notes**
Color classes makes the website longer, add 'Show More' option on page.

**Comment by shahednasser** [comment]
I'm not sure how it slows the website since it's fine on my end, However we're currently working on a website revamp so most of these problems will be resolved. Thank you for reporting this!

**Comment by adsingh14** [comment]
It's slow on mobile when the multiple animations run at same time.
