### ISSUE TITLE
[BUTTON IDEA]:Logout button

### ISSUE THREAD

**Issue by VishakhaAwasthi01** [sButtons/sbuttons#809]
**1. Name of button**: Logout Button

**2. Description**: A simple logout icon button

**3. Button Type (Animated, Special, etc...)**:Icon

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Sorry @VishakhaAwasthi01 we are currently not accepting icon buttons unless they have special functionalities (for example, the star button). Thank you
