### ISSUE TITLE
[BUTTON IDEA]: Push Button

### ISSUE THREAD

**Issue by Hrshk15** [sButtons/sbuttons#817]
**1. PUSH BUTTON **: 

**2. Push button will be having a push affect when user hovers over it .  Simple  push animation .**: 

**3. Button Type - Animated **:

**4. Yes , I have  solved this issue **:
Working-file:
[push-btn.zip](https://github.com/sButtons/sbuttons/files/5385451/push-btn.zip)

**Comment by shahednasser** [comment]
Hi @Hrshk15 thank you for wanting to contribute! First, to contribute your idea you need to fork this repository, add your code to your forked repository then submit a PR from your forked repository page. Please read the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md) for more information.

But first, can you show me an example or image of what the button actually looks like? You can show me a link from another website as an example if you want.

**Comment by Hrshk15** [comment]
Hi, @shahednasser  I've attatched a zip file above. Please check it out.

**Comment by shahednasser** [comment]
This button is exactly similar to the key button

**Comment by Hrshk15** [comment]
@shahednasser  Ohh ...I checked .. its similar to it but both have an important difference ... key button has a push affect when clicked but it has a push affect when hovered over it.

**Comment by shahednasser** [comment]
I see but I don't this the difference is that big. I'll close this but if you have any other ideas please submit them in a "new button idea" issue

**Comment by Hrshk15** [comment]
ok.., no problem.
