### ISSUE TITLE
There are 2 outline button section in the website . They both are same . 

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#824]
![Screenshot (354)](https://user-images.githubusercontent.com/58779604/96184667-6c174300-0f56-11eb-88fd-3f2dfcd03422.png)

can you please review that one ????

**Comment by SARVESHKHANDELWAL** [comment]
Can you assign me this task?

**Comment by shahednasser** [comment]
Thank you for noticing that @dsnehasish74 .

Yes @SARVESHKHANDELWAL you can work on it.

**Comment by SARVESHKHANDELWAL** [comment]
Can you please help ,as i didin't find the sidenav bar HTML code ,can you tell me in which file/folder contains that code.

**Comment by dsnehasish74** [comment]
This side nav is not hard coded ................ you just go to assests/buttons-examples.js and there you will find a list where all the button types are mentioned there you can see outline button types will be 2 times remove one of them .................... thats all .................. Hope you understand

**Comment by SARVESHKHANDELWAL** [comment]
Yes, I got it. Thanks.

**Comment by SARVESHKHANDELWAL** [comment]
I have made the PR :+1: #859 .

**Comment by SARVESHKHANDELWAL** [comment]
I have made the PR +1 #888 .
