### ISSUE TITLE
Remove "Buttons" from some button labels

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#830]
Some button labels on the website include the word "Buttons" in them (for example Dashed Buttons). You just need to remove the word "Buttons" from the label. Changes need to be made in `assets/js/buttons-examples.js`.

Make sure to not remove the word buttons from the top level types (for example Basic Buttons, Animated Buttons, etc...).

This issue is open only for new contributors to this repository

**Comment by LeaFranz** [comment]
I'm a new contributor, could you assign this to me?

**Comment by HADES-01** [comment]
Sure @LeaFranz, Go ahead I am assigning it to you.

**Comment by LeaFranz** [comment]
Should the word "button" as in "Base icon button", "Close button", "Code button" or "Toggle button" also be removed?

**Comment by HADES-01** [comment]
@LeaFranz Yes.

**Comment by navaneeth001** [comment]
I'm a new contributor, could you assign this to me?
