### ISSUE TITLE
Place "Snake Border" button in the correct alphabetical order under Animated

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#841]
Place "Snake border" in the correct alphabetical order under Animated. Changes should be made only in `assets/js/buttons-examples.js`

**Comment by Soumi150** [comment]
I would like to work on this. Please assign me.

**Comment by shashwatbangar** [comment]
hello @shahednasser can you please assign me this project? I would love to work on it. Thank you !!

**Comment by Yasas4D** [comment]
Hi, I fixed this issue as no one has assigned to this untill now. Please have a look on pull request.
Thank you!
