### ISSUE TITLE
[BUTTON IDEA]: Neumorphic Buttons

### ISSUE THREAD

**Issue by divinenaman** [sButtons/sbuttons#848]
**1. Name of button**: Neumorphic Buttons

**2. Description**: Neumorphism or Soft UI is a combination of flat design and skeuomorphism. By adding intense drop/box shadows to elements.

**3. Button Type (Animated, Special, etc...)**: Basic

**4. Will you work on it?**: Yes, I want to work on it just that this will be my second pull so help me out if needed.

**5. Examples:** 
![image](https://user-images.githubusercontent.com/63128054/96332867-180a7c80-1084-11eb-8f2d-31b49f69ffa0.png)

And one more thing please add the hacktoberfest-accepted tag after successful pull

**Comment by AnaDeCanha** [comment]
Hi! I would like to contribute to this.

**Comment by shahednasser** [comment]
We already have neumorphic buttons on the website. Thank you though!
