### ISSUE TITLE
Improve Key Button

### ISSUE THREAD

**Issue by I3han** [sButtons/sbuttons#851]
**1. Name of button**:  3D button for video games

**2. Description**: This button will feel like button can be clicked physically 

**3. Button Type (Animated, Special, etc...)**: 3D

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Hi @I3han is this different than the retro buttons we have? Please check them and if they are different please show me an example (an image or maybe an example from another website) before working on it.

**Comment by I3han** [comment]
https://i.ytimg.com/vi/CJ8FKjYtrT4/maxresdefault.jpg
It is something like this

**Comment by shahednasser** [comment]
I think this is similar to the key button as well but I'm not sure. 

@HADES-01 can I get your opinion on this? Do you think this button idea is a good one to add?

**Comment by HADES-01** [comment]
@shahednasser I think both are similar but this button has certain features that should be there in the current version, So it would be better if @I3han modified the current retro button to add the new features.

**Comment by shahednasser** [comment]
That's a good idea @HADES-01 . Can you do that @I3han ?

**Comment by I3han** [comment]
@shahednasser yes sure

**Comment by shahednasser** [comment]
Ok I'll assign you @I3han

**Comment by I3han** [comment]
Is there any guidelines for the participate?

**Comment by I3han** [comment]
@shahednasser can you tell me which folder should I added this button and what should be the name of the button and name of the file name?

**Comment by HADES-01** [comment]
@I3han You can find everything in [here](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md)

**Comment by I3han** [comment]
@HADES-01 @shahednasser Can you please check the PR please

**Comment by nobiaya** [comment]
@I3han can i contribute to this project
