### ISSUE TITLE
 Adding title to Download and Github button like theme toggle button

### ISSUE THREAD

**Issue by Hrshk15** [sButtons/sbuttons#856]
**

1. When user hovers cursor over the toggle theme button , it shows title as "Toggle light/dark mode" .
2. But it does not do that with the other two buttons (download and  github buttons ).
3. For good user experience we should add the titles to other two buttons also.
4.  Or if the icons are **self-explanatory** ,  then the hover message on Toggle theme icon should also be removed.

**
**Problem-images-**
![IMG_20201018_105833](https://user-images.githubusercontent.com/56513758/96359577-0384bd80-1132-11eb-83e1-1d0c543f2793.jpg)
![IMG_20201018_105434](https://user-images.githubusercontent.com/56513758/96359550-b99bd780-1131-11eb-8659-d524ca5e88eb.jpg)
![IMG_20201018_105440](https://user-images.githubusercontent.com/56513758/96359555-c5879980-1131-11eb-9ba8-282d95599b79.jpg)

**There can be two solutions -

1. Adding Titles to other  two buttons like toggle theme button. So that user can understand what will these buttons do.

Solution 1 images-

![IMG_20201018_105427](https://user-images.githubusercontent.com/56513758/96359541-9d983600-1131-11eb-9e65-93007e8ad9b9.jpg)
![IMG_20201018_105837](https://user-images.githubusercontent.com/56513758/96359517-63c72f80-1131-11eb-8c4c-9815e217fb92.jpg)
![IMG_20201018_105841](https://user-images.githubusercontent.com/56513758/96359529-8bb69300-1131-11eb-999c-be1f97b99468.jpg)

2. And if you think that these buttons are self explanatory , then removing the   on hover  message from toggle theme button can be a good idea . This will give a cleaner look.
Solution 2-

![WhatsApp Image 2020-10-18 at 11 08 46](https://user-images.githubusercontent.com/56513758/96359601-66765480-1132-11eb-9d2b-dc8a96b7e93c.jpeg)

![IMG_20201018_105434](https://user-images.githubusercontent.com/56513758/96359550-b99bd780-1131-11eb-8659-d524ca5e88eb.jpg)
![IMG_20201018_105440](https://user-images.githubusercontent.com/56513758/96359555-c5879980-1131-11eb-9ba8-282d95599b79.jpg) **

**Comment by Soumi150** [comment]
I want to work on this. Please assign me.

**Comment by Hrshk15** [comment]
I  created this issue.. so that I can contribute to it.🙃

**Comment by Soumi150** [comment]
Alright. Best of luck

**Comment by shahednasser** [comment]
Hello @Hrshk15 thank you for pointing this out. We are currently working on a website revamp so this layout might change. I'll keep this open for now until we are done with the website revamp and if we still need to do this I will assign you to it.

**Comment by Hrshk15** [comment]
ok, no problem.

**Comment by shahednasser** [comment]
Hi @Hrshk15 you can work on this now as the website has been revamped.

**Comment by shahednasser** [comment]
@Hrshk15 hello, can you confirm if you'll be working on this?

**Comment by VinayakChopra** [comment]
Hi, I can fix this real quick if this is unassigned.

**Comment by Hrshk15** [comment]
@shahednasser  I m very sorry for being this late.... this issue will be solved within 24 hours.
