### ISSUE TITLE
Animated-liquid-button scrolling problem

### ISSUE THREAD

**Issue by Hrshk15** [sButtons/sbuttons#857]
**1 - The liquid button under animated type has a problem with scrolling. It scrolls up/down properly in full desktop window , but when you make the browser window smaller in size(or open the site on mobile browser)  the liquid button section comes over the navigation bar while scrolling . Below are some screen-shots of the problem**
 

 **Proper behavior in full desktop view**
![Screenshot (402)](https://user-images.githubusercontent.com/56513758/96365024-7b1b1280-115b-11eb-9655-e5bd6b05eff2.png)
 

**Improper behavior as we decrease the size of the window**
![Screenshot (403)](https://user-images.githubusercontent.com/56513758/96365029-7f473000-115b-11eb-84db-9b0db4de5770.png)

 **2- Expected behavior -As we decrease the size of the browser-window the scrolling should be proper likewise in full desktop window .**

**How it is behaving as of now / How it should behave**
![Screenshot (404)](https://user-images.githubusercontent.com/56513758/96365221-920e3480-115c-11eb-969f-4867d7aeeaad.png)

**4 - I have fixed this issue and will make a pull request as soon as this issue gets assigned .**

**Comment by shahednasser** [comment]
@Hrshk15 thank you for finding this bug! I'll assign you to it.

**Comment by Hrshk15** [comment]
@shahednasser Thanks for assigning this to me...

**Comment by Hrshk15** [comment]
@shahednasser  will it count for hacktoberFest?...

**Comment by shahednasser** [comment]
@Hrshk15 yes all merged PRs or PRs labeled with "hacktoberfest-accepted" will count for Hacktoberfest
