### ISSUE TITLE
While scrolling the Base Icon Button Section after Base Button the other two button and their sub section are not visible .

### ISSUE THREAD

**Issue by SARVESHKHANDELWAL** [sButtons/sbuttons#862]
**Bug Description**
    While scrolling on getStarted.html page in Base Icon Button Section after Base Button the other two button are not visible or 
    becomes hidden on further scroll after base button and also its sub section are also not visible while scrolling down.

<img width="941" alt="Screenshot 2020-10-19 002231" src="https://user-images.githubusercontent.com/62640264/96377183-62cde680-11a1-11eb-87eb-6d4e1557e76f.png">

**For Base Button Working fine but its sub section are not visible while scroll.**

<img width="936" alt="Screenshot 2020-10-19 002315" src="https://user-images.githubusercontent.com/62640264/96377196-8db83a80-11a1-11eb-95db-9a29b17b54f0.png">

**But for Rounded Button and Block Button there is no base icon button section  visible in side navbar just after the base button.**

**Comment by shahednasser** [comment]
Thank you for reporting this bug @SARVESHKHANDELWAL . Would you like to work on it?

**Comment by glebkema** [comment]
Hello!
The sidebar on this page is three levels deep. And the script, if I understand correctly, has been debugged only for a depth of two levels and starts to fail at the third level.
Can I work on this?

**Comment by shahednasser** [comment]
Since @SARVESHKHANDELWAL hasn't replied about working on this, @glebkema you may go ahead
