### ISSUE TITLE
Ripple button border and fill issue

### ISSUE THREAD

**Issue by drewren25** [sButtons/sbuttons#864]
Ripple buttons: For whatever reason the buttons display normally but when I hover over them and cause the ripple animation to happen, some of the fill of the buttons don't reach the border of the button. I tested it out on my laptop and it happens to any button based on where the button was placed on the page. I tried fixing it but came up with nothing so hoping someone can fix it!

Below I attached a screenshot of an example of this issue. This shows up on other buttons as well and it's not consistently in the same edges of the button either. For example, sometimes it was only the bottom edge, or the right and top, or all 4 edges even. It really came in any combination as far as I was aware.
![Screenshot 2020-10-19 203348](https://user-images.githubusercontent.com/31221181/96537183-7da86580-124a-11eb-9714-fb612529f0cc.png)

@shahednasser was saying she didn't see this error on her end so I'm not sure if this is just an issue for me or if anyone else is able to see it when they use the ripple button/load the website.

**Comment by drewren25** [comment]
Also this is probably a dumb question but how do I add labels to this issue? It says that I added the bug label but I think it was applied automatically when I posted the issue. I'm reading that I'm supposed to click a checkbox on the list of issues but I'm not seeing that checkbox anywhere.

**Comment by mayankmohak** [comment]
think that only maintainer can apply labels as per my experience on this repo.

**Comment by drewren25** [comment]
@mayankmohak ohh ok I see thanks!

**Comment by shahednasser** [comment]
Hi @drewren25 thank you for reporting this issue and for providing a screenshot. As you said I was not able to reproduce this issue before. This issue is similar to #54 as we could not reproduce it on some devices at all, but other devices this issue kept happening. Someone worked on a fix for it so we'd probably have to review that. I'll leave this issue up in case someone can work on it. Again thank you!

**Comment by drewren25** [comment]
Hi @shahednasser, no problem! Yeah it's weird that it only happens on some devices but hopefully as you said someone can work and fix it.
