### ISSUE TITLE
over lapping of download and getsttarted buttons

### ISSUE THREAD

**Issue by mayankmohak** [sButtons/sbuttons#871]
**1 - Describe the bug**
The two buttons are overlapping with each other on mobile view.

**2 - Expected behavior of what should have happened (if applicable)**
There should be a gap in between them. i have fixed the issue.

**3 - Screenshots (if applicable)**
![error](https://user-images.githubusercontent.com/63801800/96596074-f3bfd180-1309-11eb-8c19-1f00844c76df.jpg)

**4 - Additional notes**
I have the fix  can i make PR?
Also worth to mention that i have see this issue mentioned before by some one but still it is unfixed so i would like to raise a PR

**Comment by shahednasser** [comment]
Hi @mayankmohak thank you for reporting this. I think someone might have worked on this before but due to the constant changes in the website it might have occurred again. We are currently on changing up the design of the website so these issues will no longer happen.

I'll assign you to this.

**Comment by mayankmohak** [comment]
shall i make a pr for now. @shahednasser

**Comment by shahednasser** [comment]
@mayankmohak yes please

**Comment by mayankmohak** [comment]
I have made a PR.

Btw what changes are being expected and what all are going to change on this repo can i get prior of it.


> We are currently on changing up the design of the website so these issues will no longer happen.

**Comment by shahednasser** [comment]
@mayankmohak I actually added you to the reviewers team of this project. Once you accept it you can see a discussion about it.
