### ISSUE TITLE
[BUTTON IDEA]: Funky Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#876]
**1. Name of button**: Funky Button

**2. Description**: A button that's color is originally outside the border but on hover becomes inside

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: No if you want to work on it please comment to be assigned.

Here's an example of what the button should act like:
[https://codepen.io/halvo/full/pRdeja](https://codepen.io/halvo/full/pRdeja)

**Comment by mayankmohak** [comment]
I want to do this.

**Comment by lejell0** [comment]
I would like to work on this please!

**Comment by shahednasser** [comment]
@lejell0 you may go ahead

**Comment by Anshu-Pandey-codes** [comment]
I could pull this off really well

**Comment by shahednasser** [comment]
Hello @Anshu-Pandey-codes thank you but someone is working on this.

**Comment by shahednasser** [comment]
Hi @lejell0 any update on this?

**Comment by UpasanaGhosh** [comment]
In case this still needs to be fixed, I would like to work on it. Thank you! :)

**Comment by shahednasser** [comment]
Yes @UpasanaGhosh please work on it.
