### ISSUE TITLE
[BUTTON IDEA]: Striped Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#877]
**1. Name of button**: Striped Button

**2. Description**: A button that has a striped background. For each button color on the website, it should use the color and a darker shade of it for the stripes

**3. Button Type (Animated, Special, etc...)**: Button Style

**4. Will you work on it?**: No, please comment on this to be assigned to it.

**Comment by Ovillena** [comment]
I would like to work on this issue

**Comment by lejell0** [comment]
I would like to work on this please!

**Comment by shahednasser** [comment]
@Ovillena you may go ahead
