### ISSUE TITLE
[BUTTON IDEA]: Diagonal Fill Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#878]
**1. Name of button**: Diagonal Fill Button

**2. Description**: Similar to the current fill buttons (right, left, etc...) it should fill the button diagonally. The code should also be placed inside `src/components/animated/_fill.less` like other fill types.

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: No, please comment on this to be assigned

**Comment by Deveshgsk** [comment]
Can I do this one?

**Comment by shahednasser** [comment]
Sure @Deveshgsk I'll assign you

**Comment by ArshdeepSingh98** [comment]
Can I do this If no one works on this ?

**Comment by shahednasser** [comment]
@ArshdeepSingh98 someone is assigned to this

**Comment by Soumi150** [comment]
I would like to work on this. Please assign me.

**Comment by shahednasser** [comment]
Assigning you @Soumi150

**Comment by richierubel** [comment]
Can I do this one? as @Soumi150 has removed the assignment yesterday

**Comment by shahednasser** [comment]
Yes @richierubel I'll assign you

**Comment by shahednasser** [comment]
Hi @richierubel are you still working on this?

**Comment by richierubel** [comment]
Hi Shahed,

yes I'm still wokring on it. But I view the Button more of a learning 
opportunity. I am currently working myself through a css transitions 
course on linkedin learning and will start working on the buttons code 
this week.

Kind regards, Richie

Am 2020-11-21 19:06, schrieb Shahed Nasser:

> Hi @richierubel [1] are you still working on this?
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].



Links:
------
[1] https://github.com/richierubel
[2] 
https://github.com/sButtons/sbuttons/issues/878#issuecomment-731614604
[3]

**Comment by shahednasser** [comment]
Thank you for letting me know @richierubel you can take your time
