### ISSUE TITLE
[BUTTON IDEA]: Sideways Fill Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#880]
**1. Name of button**: Sideways fill button

**2. Description**: Similar to the current Fill Buttons (left, right, etc...) this button should fill starting from the center and sideways (kind of like opening a door). The code should also be placed in `src/components/animated/_fill.less` similar to the current fill buttons.

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: No, please comment on this to be assigned

**Comment by DhrutikPatel** [comment]
Hello @shahednasser can I work on it ?

**Comment by shahednasser** [comment]
Sure @DhrutikPatel I'll assign you
