### ISSUE TITLE
[BUTTON IDEA]: Grow Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#881]
**1. Name of button**: Grow Button

**2. Description**: A button that starts with just an icon but on hover extends to show a word. It should work on any icon/text.

**3. Button Type (Animated, Special, etc...)**: Icon Button

**4. Will you work on it?**: No, please comment on this to be assigned

**Comment by DrHowdyDoo** [comment]
Can i try ?

**Comment by parresh77** [comment]
Please assign this to me. You can take a look at my existing work on button designs - https://pareshwadhwani-css-buttons.netlify.app/

**Comment by shahednasser** [comment]
@parresh77 I'll assign you
