### ISSUE TITLE
[BUTTON IDEA]: Rainbow Border Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#882]
**1. Name of button**: Rainbow Border

**2. Description**: a black background button with a radio border

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**:No, please comment on this to be assigned

This button is similar to the button you see on codepen

**Comment by Soumi150** [comment]
I want to work on this. Please assign me.

**Comment by shahednasser** [comment]
@Soumi150 I'll assign you
