### ISSUE TITLE
[BUTTON IDEA]: Blob Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#883]
**1. Name of button**: Blob Button

**2. Description**: Button that fills up in a blob style

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: No, please comment on this to be assigned

You can see an example of it [here](https://codepen.io/suez/pen/aOgMxy).

**Comment by wisetok12680** [comment]
I would like to work on this..

**Comment by kavinsingh28** [comment]
I am new to this , but i wanna give this a try, can you please elabore more !

**Comment by mrSidSat** [comment]
Can i work on this???

**Comment by shahednasser** [comment]
Yes @mrSidSat I'll assign you

**Comment by mrSidSat** [comment]
Here in this issue i Dont think this example can be implemented without any markup. i tried for a valid solution but this requires use of minimal markup for the blob effect...So i would like to ask if there is any provision to use JS here as it would make this job a lot easy...

**Comment by shahednasser** [comment]
@mrSidSat this project is a CSS only project as of now. I understand your problem but I provided the example just as a reference. You don't have to do it exactly the same. Just try to make use of `:before` and `:after` and do it the way you find best.

**Comment by mrSidSat** [comment]
okay thanks i would try..

**Comment by Sumit2399** [comment]
Hi @shahednasser,I am new to open source contribution.Can you provide me with some more pointer on what has to be done on this issue.Help would be appreciated.

**Comment by marcoscalia** [comment]
Hi @shahednasser, maybe can be helpful this [solution](https://codepen.io/marcoscalia/pen/wvWgRbg)

**Comment by shahednasser** [comment]
@Sumit2399 @marcoscalia someone is working on this issue.

**Comment by Sumit2399** [comment]
Hi @shahednasser,I am trying to add a new button color .Most of the buttons are working fine but some animated buttons are causing issue.Can you help me to understand what could be the problem?

**Comment by divyanshutewari17** [comment]
Can I Work on this?

**Comment by shahednasser** [comment]
I am unassigning @mrSidSat as he is working on a different approach

**Comment by shahednasser** [comment]
@divyanshutewari17 let me know if you still want to work on this

**Comment by viktoraronfarkas** [comment]
@shahednasser I could work on this

**Comment by UpasanaGhosh** [comment]
Can I please take this up if there isn't anyone else working on it? Thanks!

**Comment by shahednasser** [comment]
Sure @UpasanaGhosh I'll assign you

**Comment by mrSidSat** [comment]
Can You assign it to me again??

**Comment by shahednasser** [comment]
Sure @mrSidSat

**Comment by shahednasser** [comment]
Hello @mrSidSat are you working on this?

**Comment by mrSidSat** [comment]
Sorry , you can assign someone else...

**Comment by shahednasser** [comment]
It's ok @mrSidSat thank you for letting me know.

**Comment by RgnDunes** [comment]
If no one is working on this issue then I'll love to work on it. It would be great if you could assign it to me.

**Comment by shahednasser** [comment]
Sure @RgnDunes I'll assign you
