### ISSUE TITLE
[BUTTON IDEA]: Neon Border Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#884]
**1. Name of button**: Neon Border Button

**2. Description**: A transparent background button with neon borders

**3. Button Type (Animated, Special, etc...)**: Button Style

**4. Will you work on it?**: No, please comment on this to be assigned

You can see an example [here](https://codepen.io/half-fuller/pen/GJwVLP)

**Comment by RakshitaTantry28** [comment]
I would like to work on it!

**Comment by sandeep3136** [comment]
assign me

**Comment by srinivasan-cloud** [comment]
hi i would like to contribute my work

**Comment by shahednasser** [comment]
@RakshitaTantry28 I'll assign you
