### ISSUE TITLE
Enhance Gradient Button's Look

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#885]
**1 - Describe the bug**
Gradient button's style needs an enhancement. Maybe in the gradient being used or in the transition. Also the box-shadow looks a bit too much.

**2 - Expected behavior of what should have happened (if applicable)**
Make it something more sleek

**Comment by mayankmohak** [comment]
i want to work on this issue.

**Comment by shahednasser** [comment]
Sure @mayankmohak I'll assign you

**Comment by Anamika810** [comment]
I want to work on this issue. @shahednasser

**Comment by ArshdeepSingh98** [comment]
Can I also work on this issue?
