### ISSUE TITLE
Removing border from splash button

### ISSUE THREAD

**Issue by Hrshk15** [sButtons/sbuttons#889]
**Is your feature request related to a problem? Please describe.**
Splash button is having borders of very odd colors , which don't go good  with the gradient inside of them. 

**Describe the solution you'd like**
After removing the borders, it will have a good sleek n elegant look.

**How the button currently looks \ How it'll look after removing wierd borders :-**
The gradient is animated in this button so it looks good with no borders.
![Screenshot (420)](https://user-images.githubusercontent.com/56513758/96821563-ced07900-1445-11eb-94b8-677d4aad8e2e.png)

**Additional notes**
I'll make a pull request as soon as possible if assigned.

**Comment by shahednasser** [comment]
Makes sense. I'll assign you @Hrshk15
