### ISSUE TITLE
On getStarted.html page all heading tag should have same font-style ,it is different after Base Icon Button.

### ISSUE THREAD

**Issue by SARVESHKHANDELWAL** [sButtons/sbuttons#890]
**Describe the bug**
On getStarted.html page there is different heading font-style ,it should be same for all the heading on the page.

##**Here it has correct heading style.**
<img width="938" alt="1" src="https://user-images.githubusercontent.com/62640264/96827818-080fe580-1454-11eb-811c-a691fb556bc8.png">

##**But here the font style of heading is different it should be similar.**
<img width="937" alt="2" src="https://user-images.githubusercontent.com/62640264/96827865-1d850f80-1454-11eb-8ab8-60497eae18b3.png">

**Comment by shahednasser** [comment]
Makes sense. Would you like to work on it @SARVESHKHANDELWAL ?

**Comment by MorganGodden** [comment]
Hello @shahednasser, I have created a PR that fixes this issue. 
Also, do issues like this qualify for hacktoberfest contributions? I am unsure as only some issues have the hacktoberfest tag.
