### ISSUE TITLE
[BUTTON IDEA]: Vibrate Button

### ISSUE THREAD

**Issue by adrsh79086** [sButtons/sbuttons#897]
**1. Name of button**: 
 vibrate button

**2. Description**: 
[viberate btn (1).zip](https://github.com/sButtons/sbuttons/files/5422588/viberate.btn.1.zip)

when we move crusher on button it get vibrate.

**3. Button Type (Animated, Special, etc...)**:
Animation

**4. Will you work on it?**:
yes
[viberate btn (1).zip](https://github.com/sButtons/sbuttons/files/5422595/viberate.btn.1.zip)

**Comment by shahednasser** [comment]
Thank you @adrsh79086 but the idea doesn't look that good to be honest. I'll still assign you and you can submit a PR, maybe it'll look better after seeing it on the website.

P.S: even if we don't merge the PR I'll still label it "hacktoberfest-accepted"
