### ISSUE TITLE
Dark Mode support for neumorphic button

### ISSUE THREAD

**Issue by HADES-01** [sButtons/sbuttons#902]
**1 - Describe the bug**
In dark mode the neumorphic button looks flat and loses its neumorphic-ness (if that's a word).

**2 - Expected behavior of what should have happened (if applicable)**
The box shadow applied should get inverted in the dark mode.

**3 - Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/52060608/96953379-8d57d080-150e-11eb-97c1-6b8b812e1532.png)

**Comment by MorganGodden** [comment]
Hey @HADES-01, are you taking this? If not then would I be able to ask @SahanAmarsha if I could be assigned?

I don't believe the box shadows should be inverted, rather the values of the highlight and shadow should be adjusted to fit on darkmode pages - making them more neumorphic.

**Comment by HADES-01** [comment]
@MorganGodden I guess you are right. I will assign you this.
