### ISSUE TITLE
Fill button in case of white color not showing any changes on hover

### ISSUE THREAD

**Issue by ArshdeepSingh98** [sButtons/sbuttons#906]
**1 - Fill button (white) not shows any changes on hover**

**2 - I think white button should be removed or some shade of white should be shown**

**3 - Demo**
![fill_issue](https://user-images.githubusercontent.com/29947024/96991588-4ede0800-1546-11eb-98f8-e795e9d7dfdb.gif)

**4 - I can work on this issue if assigned**

**Comment by shahednasser** [comment]
@ArshdeepSingh98 this is due to the background. If you switch to "Dark Mode" You can see it works fine. A fix here is not necessary, as the button's functionality needs to be like this. Thank you for reporting this!

**Comment by ArshdeepSingh98** [comment]
Ok, Thanks for clearing it.
