### ISSUE TITLE
Button text not visible in dark mode in some cases.

### ISSUE THREAD

**Issue by ArshdeepSingh98** [sButtons/sbuttons#909]
**1 - Text of some of the buttons is not clearly visible**

**2 - Text should be clearly visible in dark mode**

**3 - Screenshot**
![Screenshot 2020-10-23 at 4 02 36 PM](https://user-images.githubusercontent.com/29947024/96993785-68348380-1549-11eb-970b-ffd9ca6407b2.png)

**4 - I think making text color white/some shade of white should fix this issue.<br> I can work on this if assigned**

**Comment by shahednasser** [comment]
@Archis19 thank you for reporting this! As I mentioned on the other issue, this is important for the button's functionality. 

However, your issues have made me realize maybe we need a "dark-mode" class for these cases. I'll create a new issue on this and you can work on it if you reply to it. Thank you!

**Comment by ArshdeepSingh98** [comment]
Ok, Thanks for the reply.
