### ISSUE TITLE
[BUTTON IDEA]: Hover Button with revolving item.

### ISSUE THREAD

**Issue by harjotkarwal** [sButtons/sbuttons#918]
**1. Name of button**: Neutron Button

**2. Description**: On hovering, neutron/atomic entity would revolve around on border.

**3. Button Type (Animated, Special, etc...)**: Special

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
@harjotkarwal I'll assign you

**Comment by harjotkarwal** [comment]
#927

**Comment by harjotkarwal** [comment]
#942

**Comment by harjotkarwal** [comment]
@shahednasser Here's my updated code #942
