### ISSUE TITLE
[BUTTON IDEA]: loading button in fill type 

### ISSUE THREAD

**Issue by DhrutikPatel** [sButtons/sbuttons#920]
**1. Name of button**: loading fill button

**2. Description**: The fill color of certain size square or rectangle will move from left to right 

**3. Button Type (Animated, Special, etc...)**: Animated type

**4. Will you work on it?**: yes

**Comment by shahednasser** [comment]
Do you mean it will be like an animation?

**Comment by DhrutikPatel** [comment]
Yes, rectangle of some size will go from left to right within the button

**Comment by shahednasser** [comment]
I understand but this usually requires some javascript mechanism, so without that the button would be redundant, as we are doing this project CSS only.
