### ISSUE TITLE
Add a class to support Dark Mode

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#922]
Currently all of our animations support light mode. We need a way to make it support dark mode as well, to give users a more flexible way of using the buttons. So, we should add a global class (a class that can work on all types) called `dark-mode` that makes any necessary changes to the button to make it look better (for example maybe change the color of the text, depends on each button). If a button type does not need any change then no changes need to be made to it. It should also support the [dark mode media query](https://css-tricks.com/dark-modes-with-css/). 

This is a lot of work so before asking to be assigned please be aware of what you're signing up for. You also need a good understanding of Less.

**Comment by ArshdeepSingh98** [comment]
I would like to work on this feature/issue.
Also when dark mode is toggled from navbar, dark-mode class will be added to all the buttons?

**Comment by shahednasser** [comment]
@ArshdeepSingh98 that's a good idea. Yes, I guess it should. Let's see what's the best way to do it.

I'll assign you.

**Comment by Anshu-Pandey-codes** [comment]
this seems to be a good challenge. I think ill learn a lot in this process.
I am new to the open-source community and want to do this project

**Comment by shahednasser** [comment]
Hello @Anshu-Pandey-codes someone is already working on this. Please pick unassigned issues or create a "new button idea" issue if you want to create a new issue.

**Comment by ArshdeepSingh98** [comment]
Hi, @shahednasser, sorry to inform that I will not be able to work on this issue. Feel free to assign it to anyone.

**Comment by shahednasser** [comment]
@ArshdeepSingh98 it's ok thank you for informing me!
