### ISSUE TITLE
[BUTTON IDEA]: Icon Door

### ISSUE THREAD

**Issue by MorganGodden** [sButtons/sbuttons#924]
**1. Name of button**: Icon Door

**2. Description**:  An icon style button that when hovered over appears as though it is rotating with a door that is being opened behind it. Essentially symbolizing going from this page to another.

> **Unfinished examples (darkmode) -**
> ![2020-10-24_01-42-19](https://user-images.githubusercontent.com/52884391/97064056-6693ab80-159b-11eb-86cf-9cc8c08af10b.gif)
> ![2020-10-24_01-29-20](https://user-images.githubusercontent.com/52884391/97064057-67c4d880-159b-11eb-95b6-7a481d3ea6be.gif)
> 

**3. Button Type (Animated, Special, etc...)**: Icon/Animated

**4. Will you work on it?**: I would be pleased to work on this further :)

**Comment by shahednasser** [comment]
Hi @MorganGodden looks good. If it just works on icons then place it in icons. But if it can work on text then use text and place it in Animated. You figure out the best way to do it.
