### ISSUE TITLE
[BUTTON IDEA]: 3d button

### ISSUE THREAD

**Issue by kleyla** [sButtons/sbuttons#925]
**1. Name of button**: 3d button

**2. Description**: 
[3d_button.zip](https://github.com/sButtons/sbuttons/files/5432253/3d_button.zip)

**3. Button Type (Animated, Special, etc...)**: Styles

**4. Will you work on it?**: yes

**Comment by shahednasser** [comment]
@kleyla thank you for the button idea but we already have a key button and it's basically the same
