### ISSUE TITLE
Google Font error while compiling.

### ISSUE THREAD

**Issue by harjotkarwal** [sButtons/sbuttons#926]
**1 - Describe the bug**: Compilation error

**2 - Expected behavior of what should have happened (if applicable)**: No google font error while compiling.

**3 - Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/73360250/97065632-7f688500-15cc-11eb-9a75-4605f7706a8f.png)

**4 - Additional notes**

**Comment by shahednasser** [comment]
Thank you @harjotkarwal for reporting this error. I'm guessing you weren't connected to the internet when this happened?

Maybe we can make the import of the font optional for similar cases

**Comment by harjotkarwal** [comment]
I don't know about the internet because I used 'Lato' font in my PR and it didn't show any error.

 I managed to compile it by terminate and re-run git command after each change.

**Comment by shahednasser** [comment]
The error shows a connection error so I'm pretty sure it was an internet problem. Let's keep this issue up for now to see if any other contributors have a similar issue or not.
