### ISSUE TITLE
[BUTTON IDEA]:Signin with Gitlab and bitbucket button

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#936]
**1. Name of button**:  social button

**2. Description**:  for detail you can refer to this link https://app.netlify.com/signup?_ga=2.199206703.1086808665.1603537944-387436929.1595247223
 

**3. Button Type (Animated, Special, etc...)**:

**4. Will you work on it?**:

**Comment by dasari810** [comment]
@shahednasser  I'm interested to work on this , can you assign me .

**Comment by dsnehasish74** [comment]
yes go head

**Comment by dasari810** [comment]
@dsnehasish74  i made a pull request #947   for this issue , please review it
