### ISSUE TITLE
Language Support in Readme

### ISSUE THREAD

**Issue by HADES-01** [sButtons/sbuttons#938]
**1 - Describe the bug**
Currently some of the code element in the `readme.md` doesn't have support for language markdown..

**2 - Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/52060608/97083972-562e1000-1631-11eb-8fa0-ffb69d2d7d5b.png)

**Comment by AaqibAhamed** [comment]
Can anyone explain more this issue .Then I can work on it.

**Comment by Ajax-Light** [comment]
Hey! Do you mean syntax highlighting in the code block? If you can assign this to me, I'll be glad to Help!

**Comment by shahednasser** [comment]
hi @HADES-01 can you please provide some link or reference on "language markdown" so contributors can understand more what this is about? Thank you!

**Comment by Ajax-Light** [comment]
@shahednasser Hey, I think he means that the first 2 code blocks in the README.md file are not syntax highlighted and rest of them are. This is because they haven't been enclosed in the html``` markdown. Can I open a PR regarding this?

**Comment by Ajax-Light** [comment]
@HADES-01 Thanks, I'm on it. Will open a PR first thing in the morning.

**Comment by shahednasser** [comment]
@Ajax-Light @HADES-01 thank you for explaining. I'll assign you @Ajax-Light

**Comment by Ajax-Light** [comment]
@shahednasser I've opened PR #962. I had some concerns which I've commented there. Please Review.
