### ISSUE TITLE
Add a data-theme option for buttons in the buttons-examples.js file.

### ISSUE THREAD

**Issue by MorganGodden** [sButtons/sbuttons#943]
**Is your feature request related to a problem? Please describe.**
At the moment the website does not have an easy way for the user to compare between when a button is in darkmode or lightmode. Currently the user would need to navigate to the darkmode/lightmode button and keep switching between the two modes.

**Describe the solution you'd like**
To merge my PR that adds the ability to assign a button's _data-theme_ in the buttons-examples.js file for the website - allowing for the displaying of both lightmode and darkmode buttons on the same page despite what mode the page is currently in.

**Additional notes**
> ![2020-10-25_02-45-58](https://user-images.githubusercontent.com/52884391/97097745-631c2500-166c-11eb-9933-04109d0c8a68.gif)

**Comment by shahednasser** [comment]
@MorganGodden Thank you for this issue. Someone is working on adding a class for dark mode that would add support for buttons on dark mode not just on the website, but when used by others in their projects as well and I find that more convenient. I still appreciate your work so I'll be labeling your PR as "hacktoberfest-accepted" and I look forward to more contributions from you!

**Comment by MorganGodden** [comment]
Ah okay @shahednasser, no problem!
