### ISSUE TITLE
[BUTTON IDEA]: Like the plus Icon button there can be a minus button

### ISSUE THREAD

**Issue by Hrshk15** [sButtons/sbuttons#948]
**1. Name of button**: 
Minus Button
**2. Description**: 
Like the plus button is used to increase value mostly , the minus button will be used to decrease the respective value.
**Just the plus will be replaced by minus.**
![Screenshot (427)](https://user-images.githubusercontent.com/56513758/97105329-e6c32980-16df-11eb-94ed-fed20812cdd0.png)

**3. Button Type (Animated, Special, etc...)**:
Icon Type Button
**4. Will you work on it?**:
Yes , its simple to implement.

**Comment by shahednasser** [comment]
Thank you @Hrshk15 but we are actually removing many of these icon buttons soon, as we have a base icon now and there won't be any need for buttons like the "Plus button"
