### ISSUE TITLE
[BUTTON IDEA]: Isometric Button

### ISSUE THREAD

**Issue by googol88** [sButtons/sbuttons#954]
**1. Name of button**: Isometric Button

**2. Description**: a 3D button following the isometric projection (rotated and skewed) which appears pressed on when clicked. Here's an example:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/57511576/97174546-9e038300-1768-11eb-98a7-bdef4cb4641b.png">

**3. Button Type (Animated, Special, etc...)**: Styles

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Ok @googol88 you may go ahead

**Comment by shahednasser** [comment]
Hi @googol88 any update on this?

**Comment by googol88** [comment]
Hi, apologies for the delay, I'm still working on it!

**Comment by shahednasser** [comment]
No problem @googol88

**Comment by googol88** [comment]
Hi @shahednasser , I'm still having a couple problems with this button. Specifically, I haven't adjusted the margins properly and there's some strange flickering with the `::before` and `::after` pseudo classes. On Safari, it looks fine until you click it, then part of it disappears... it's weird. And on Chrome the pseudo classes don't even show up at all! Here's a deployment of [my fork](https://github.com/googol88/sbuttons): [https://cranky-spence-756c7c.netlify.app/#isometric](https://cranky-spence-756c7c.netlify.app/#isometric)

Strangely there's no issue with this button on the [CodePen](https://codepen.io/googol88/pen/KKMagGy) I created.
I think I'm not going to work on this issue for now. If you want to assign it to someone else that's fine.

**Comment by shahednasser** [comment]
I understand @googol88 if you want you can send in a PR to see how I can help you

**Comment by shahednasser** [comment]
Hello @googol88 are you still working on this?
