### ISSUE TITLE
[BUTTON IDEA]: Blinking Text

### ISSUE THREAD

**Issue by adrsh79086** [sButtons/sbuttons#956]
**1. Name of button**: 
 blinking text

**2. Description**:   
on hover the text on button is starting blinking.

**3. Button Type (Animated, Special, etc...)**:
Animated.

**4. Will you work on it?**:
yes 
[blinking.zip](https://github.com/sButtons/sbuttons/files/5439068/blinking.zip)

**Comment by shahednasser** [comment]
Ok @adrsh79086 you may go ahead.
