### ISSUE TITLE
Fill color Button issue

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#961]
**1 - Describe the bug** in the fill color button some white space remains in the border sides for some buttons. can any one fix this issue . I am adding one of the screenshot .
![Screenshot (358)](https://user-images.githubusercontent.com/58779604/97251922-d7062b00-182e-11eb-91c2-c74e2acdd59a.png)

**Comment by divyanshutewari17** [comment]
Can I work on this?

**Comment by Shivam-Shandilya1** [comment]
HEY! CAN I SOLVE THIS PROBLEM AND CONTRIBUTE  TO THIS WEB PAGE TO BECOME MORE EFFICIENT AND BUG FREE.

**Comment by dsnehasish74** [comment]
@divyanshutewari17  ok can work . I am assigning you this task . 
@Shivam-Shandilya1 thank you but @divyanshutewari17  commented first so you can look for other unassigned issues .

**Comment by divyanshutewari17** [comment]
@dsnehasish74 it is not showing this problem on all the systems. It didn't show the problem on my laptop but it was showing this bug on my PC. So, I resolved the problem and now it is not showing it on my PC also.
![Screenshot 2020-10-27 at 7 32 09 PM](https://user-images.githubusercontent.com/51994346/97312226-427de600-188b-11eb-9b9e-f3d107e9b499.png)

**Comment by shahednasser** [comment]
Thank you @dsnehasish74 for reporting this. There seems to be an ongoing issue with fill buttons as described in #54 and other issues as well. I will keep this issue unassigned in case anyone can solve it. If anyone can solve it please submit a PR. Thank you all.

**Comment by ramkrishn123** [comment]
I want to try to fix this issue.
