### ISSUE TITLE
Transparent hover button- white color issue

### ISSUE THREAD

**Issue by Hrshk15** [sButtons/sbuttons#963]
**1 - Describe the bug**
White colored button in  transparent hover button , on hover shows nothing on it. The text inside disappears  because its color remains white. 
**2 - Expected behavior of what should have happened (if applicable)**
On hovering on transparent white button the text color should be changed to black (**or black with low intensity** ) on hover.
**3 - Screenshots (if applicable)**
Left image shows white button before hover      /   right image shows on hover
**We should change the text color to black or low intensity black on hover , which will give a transparent effect.**
![Screenshot (435)](https://user-images.githubusercontent.com/56513758/97264984-e0ea5700-184b-11eb-8278-dba4044592a5.png)

**4 - Additional notes**

**Comment by mrSidSat** [comment]
can i work on this

**Comment by Hrshk15** [comment]
I have worked upon it... but maintainer will decide whether this is to be solved or not.

**Comment by mrSidSat** [comment]
Okay

**Comment by jithinjohnkaniyampoikayil** [comment]
I also have it ready. Is the PR opened for this already?? cant find any!!

**Comment by dsnehasish74** [comment]
@Hrshk15  Thank you for mentioning it . But I think it is ok if the background color is deferent . Here background color is white so that you can not see the text but if this button is used in a different background color then it will be fine .

**Comment by shahednasser** [comment]
thank you @Hrshk15 but I agree with @dsnehasish74 . We currently have an issue #922 for adding dark mode classes for all buttons, we'll look into adding a light mode classes but at the moment I think it's unnecessary.
