### ISSUE TITLE
In Round Bottom Button and Animated Buttons headings in side navbar the sub section headings are not visible completely.

### ISSUE THREAD

**Issue by SARVESHKHANDELWAL** [sButtons/sbuttons#965]
**Describe the bug**
   In **Rounded Bottom** button in side nav bar the sub heading i.e Rounded Diagonal (Top Left) and Rounded Diagonal (Top Right) is not visible completely and i have attached the screenshot below.And same issue with **Animated Buttons** also.

**Supported Screenshots** 

**##In Rounded Button Section**
<img width="293" alt="1" src="https://user-images.githubusercontent.com/62640264/97273980-03836c80-185a-11eb-9a83-1dada3fb105c.png">

**##In Animated Buttons Section**
<img width="251" alt="2" src="https://user-images.githubusercontent.com/62640264/97274053-1c8c1d80-185a-11eb-92ba-54d98c906ec8.png">

**4 - Additional notes**
Can you please assign me this task so that I can look after this bug.

**Comment by shahednasser** [comment]
You are right @SARVESHKHANDELWAL thank you for reporting this!

**Comment by divyanshutewari17** [comment]
@SARVESHKHANDELWAL @shahednasser Can I work on this?

**Comment by shahednasser** [comment]
Yes @divyanshutewari17 I'll assign you

**Comment by shahednasser** [comment]
This issue has been resolved by new website update. Thank you all
