### ISSUE TITLE
[BUTTON IDEA]:Rainbow button

### ISSUE THREAD

**Issue by Hrshk15** [sButtons/sbuttons#968]
**1. Name of button**: 
Rainbow Button
**2. Description**: 
Copy paste this url in browser to see this button working live-
[https://codepen.io/hrshk/pen/KKMmgpK](url)
**3. Button Type (Animated, Special, etc...)**:
Animated
**4. Will you work on it?**:
I have worked upon it .

**Comment by shahednasser** [comment]
You can go ahead @Hrshk15

**Comment by Hrshk15** [comment]
Thanks!!
