### ISSUE TITLE
sbtn class is added globally to all

### ISSUE THREAD

**Issue by mrSidSat** [sButtons/sbuttons#972]
**Is your feature request related to a problem? Please describe.**
 **The sbtn class is defined for each and every button which has some properties which interfere with the user defined classes for buttons
**Describe the solution you'd like**
**The sbtn class check should be given if the developer is facing the issue for representing the button in the main site which otherwise works good..**
**Modify the doc / readme to address the same**
**Additional notes**
_**I would like to work on this issue**_

**Comment by shahednasser** [comment]
Hello @mrSidSat can you please explain more what you mean? I couldn't really understand.
