### ISSUE TITLE
Paper Curl button border 

### ISSUE THREAD

**Issue by dsnehasish74** [sButtons/sbuttons#974]
I think the border should not be there in the paper curl button .
I am adding the screenshot of both with border and without border . Fell free to give your opinion on this  .
With border
![Screenshot (362)](https://user-images.githubusercontent.com/58779604/97403500-879d2900-191a-11eb-880b-6a47ed0ee209.png)

solution without border
![Screenshot (361)](https://user-images.githubusercontent.com/58779604/97403524-95eb4500-191a-11eb-8cbe-5d0eba370cf2.png)

**Comment by Hrshk15** [comment]
@dsnehasish74  yes, it looks better without  the border.

**Comment by SARVESHKHANDELWAL** [comment]
@dsnehasish74 yes, it looks better without the border.

**Comment by dsnehasish74** [comment]
so any one want to work on this ????????????

**Comment by shahednasser** [comment]
Great idea @dsnehasish74

**Comment by adrianmendez03** [comment]
I'd like to take a crack at it!

**Comment by Hrshk15** [comment]
I have solved this issue. @shahednasser 
![Screenshot (437)](https://user-images.githubusercontent.com/56513758/97521939-9b9d6500-19c4-11eb-96d5-6e1e75f59a50.png)

**Comment by anillama** [comment]
Green without the border looks good.

**Comment by shahednasser** [comment]
@adrianmendez03 you may go ahead as you have commented first.

**Comment by adrianmendez03** [comment]
> @adrianmendez03 you may go ahead as you have commented first.

I believe @Hrshk15 already solved the problem.

**Comment by shahednasser** [comment]
The issue is not resolved yet so will you work on it @adrianmendez03 ?

**Comment by Hrshk15** [comment]
2 days have passed since this comment was made @shahednasser , I think he  is busy with something else .  If this is  that important I can make a pull-request.

**Comment by dsnehasish74** [comment]
@adrianmendez03 are you working on this on this issue please reply ? if not then let us know .

**Comment by adrianmendez03** [comment]
> @adrianmendez03 are you working on this on this issue please reply ? if not then let us know . 

I'm not working on this. Sorry for the inconvenience.

**Comment by dsnehasish74** [comment]
@adrianmendez03  ok no problem

**Comment by dsnehasish74** [comment]
@Hrshk15 are you interested to work then I will assign this to you.

**Comment by Hrshk15** [comment]
Yes. I am interested.

**Comment by dsnehasish74** [comment]
then you can work on this.

**Comment by Hrshk15** [comment]
Hey @dsnehasish74  someone has already solved this issue, papercurl is working as you wanted it to be .
![image](https://user-images.githubusercontent.com/56513758/98246735-b2c9ed00-1f98-11eb-92a7-e65697d18685.png)

**Comment by dsnehasish74** [comment]
Yah @Hrshk15 thank you for informing that
