### ISSUE TITLE
Add documentation about toggle button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#983]
Toggle Button now can be used for checkboxes and radio buttons. We need to do the following:

1. Add on the get started page a new section for toggle button explaining that it can also be used for checkboxes and radio buttons, and showing an example of it with the button and the code for it. It should be placed before the base icon documentation.
2. Add on the readme the same documentation as above, but without the button as an example (only the code).

**Comment by Anurag-ak99** [comment]
I would like to contribute, so can you assign this issue to me?

**Comment by glebkema** [comment]
@Anurag-ak99 I've assigned you.

**Comment by ramkrishn123** [comment]
I would like to contribute.

**Comment by shahednasser** [comment]
@ramkrishn123 someone else is assigned to this. Please look at other unassigned issues.

**Comment by shahednasser** [comment]
@ramkrishn123 do you still want to work on this?

**Comment by VinayakChopra** [comment]
I would like to contribute, can you assign me this issue?

**Comment by glebkema** [comment]
@VinayakChopra I've assigned you.

**Comment by VinayakChopra** [comment]
Thanks, just needed to know if I need to just display the toggle buttons and Write the use case as check box and radio button as text or 
actually show the use case along with code on the getting started page

**Comment by shahednasser** [comment]
Hello @VinayakChopra We need you to write documentation about it as well as show the button. You need to include a checkbox with the classes related to toggle and same for the radio button. Make sure to also include the code block to how to do it under each example (you can refer to other parts of the documentation on help on that)
