### ISSUE TITLE
[BUTTON IDEA]: subtract button

### ISSUE THREAD

**Issue by crnguyen** [sButtons/sbuttons#985]
**1. Name of button**: subtract button

**2. Description**: 
Button with a - sign 
**3. Button Type (Animated, Special, etc...)**: normal

**4. Will you work on it?**:
Yes

**Comment by crnguyen** [comment]
finished this and opened a pull request: https://github.com/sButtons/sbuttons/pull/987

**Comment by shahednasser** [comment]
Thank you @crnguyen but we are currently only accepting icon buttons that have a certain functionality to them, not just an icon button with an icon in it.
