### ISSUE TITLE
[BUTTON IDEA]: Home Button

### ISSUE THREAD

**Issue by crnguyen** [sButtons/sbuttons#986]
**1. Name of button**: Home Button

**2. Description**: button that says Home, when clicked takes the user to a homepage. I can either use an icon or the word "Home"

**3. Button Type (Animated, Special, etc...)**: normal

**4. Will you work on it?**: yes

**Comment by shahednasser** [comment]
I'm sorry @crnguyen but this button does not fit in our project. We don't need a button that has an action to it, we just want different button designs or different animations
