### ISSUE TITLE
Move documentation from getStarted.html to documentation.html

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#995]
There are some messing documentation in `documentation.html`. They should be moved from `getStarted.html` as this file will be deleted after this.

**Comment by priyaChaturvedi11** [comment]
Hi there! If you could provide a little more detail on what has to be done, I would like to work on this. Thanks!

**Comment by priyaChaturvedi11** [comment]
Alright! Stuff after 'Disabled Buttons' section isn't present in documentation.html and I guess has to be moved from getStarted.html  Is that all what has to be done?

**Comment by shahednasser** [comment]
Hello @priyaChaturvedi11 we're currently under discussion about that actually, so I'll get back to you on that.
